/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class AVPlayerViewController;

@interface _TtCC10Notability27GenericVideoIntroControllerP33_6D35B0DEF9AC1E6BB4FDB9378591094415SlideController : UIViewController {

	 info;
	 observers;
	 playerView;
	 player.storage;
	 playerController.storage;
	 imageView;
	 isPlaying;
	 isVisible;
	 shouldLoop;
	 separator;
	 titleLabel;
	 descriptionLabel;
	 textGroup;

}

@property (retain,nonatomic) AVPlayerViewController * playerController; 
-(id)initWithCoder:(id)arg1 ;
-(void)dealloc;
-(void)loadView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)setPlayerController:(AVPlayerViewController *)arg1 ;
-(AVPlayerViewController *)playerController;
@end

