/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface _TtCC10Notability27GenericVideoIntroControllerP33_6D35B0DEF9AC1E6BB4FDB937859109448PageInfo : _UKNOWN_SUPERCLASS_ {

	 videoName;
	 title;
	 description;
	 assetURL.storage;
	 asset.storage;
	 imageGenerator.storage;
	 item.storage;

}
@end

