/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, NSString, UIApplication;

@interface ANSApplication : NSObject {

	NSDictionary* _infoPlistDict;

}

@property (nonatomic,readonly) NSDictionary * infoPlistDict;                              //@synthesize infoPlistDict=_infoPlistDict - In the implementation block
@property (nonatomic,readonly) NSString * bundleIdentifier; 
@property (nonatomic,readonly) NSString * bundleVersion; 
@property (nonatomic,readonly) NSString * shortVersionString; 
@property (nonatomic,readonly) NSDictionary * extensionDefinitionDictionary; 
@property (nonatomic,readonly) NSString * extensionPointIdentifier; 
@property (nonatomic,readonly) char isExtension; 
@property (nonatomic,readonly) UIApplication * appSharedInstance; 
+(id)hostApplication;
-(id)initWithInfoPlistDictionary:(id)arg1 ;
-(NSDictionary *)infoPlistDict;
-(NSDictionary *)extensionDefinitionDictionary;
-(UIApplication *)appSharedInstance;
-(NSString *)bundleIdentifier;
-(NSString *)extensionPointIdentifier;
-(NSString *)bundleVersion;
-(char)isExtension;
-(NSString *)shortVersionString;
@end

