/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface ANSBackoffTimer : NSObject {

	unsigned _retryCount;
	double _initialValue;
	double _jitterCoefficient;

}

@property (assign,nonatomic) double initialValue;                     //@synthesize initialValue=_initialValue - In the implementation block
@property (nonatomic,readonly) double jitterCoefficient;              //@synthesize jitterCoefficient=_jitterCoefficient - In the implementation block
@property (assign,nonatomic) unsigned retryCount;                     //@synthesize retryCount=_retryCount - In the implementation block
+(char)jitterCoefficientIsValid:(double)arg1 ;
-(id)initWithInitialValue:(double)arg1 jitterCoefficient:(double)arg2 ;
-(double)computeDelayForInitialValue:(double)arg1 retryCount:(unsigned)arg2 ;
-(double)jitterCoefficient;
-(double)randomDoubleWithMin:(double)arg1 max:(double)arg2 ;
-(double)generateRandomJitter;
-(void)executeBlockAfterNextInterval:(/*^block*/id)arg1 ;
-(id)initWithInitialValue:(double)arg1 ;
-(id)init;
-(void)setRetryCount:(unsigned)arg1 ;
-(unsigned)retryCount;
-(double)initialValue;
-(void)setInitialValue:(double)arg1 ;
@end

