/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface ANSFirebaseAnalyticsBridge : NSObject {

	id _firebaseAnalytics;
	NSArray* _firebaseReservedKeys;

}

@property (nonatomic,retain) id firebaseAnalytics;                        //@synthesize firebaseAnalytics=_firebaseAnalytics - In the implementation block
@property (nonatomic,retain) NSArray * firebaseReservedKeys;              //@synthesize firebaseReservedKeys=_firebaseReservedKeys - In the implementation block
+(id)sanitizeEventName:(id)arg1 ;
+(id)customParametersFromCustomAttributes:(id)arg1 ;
+(id)firebaseEventNameForAnswersEventName:(id)arg1 predefinedAttributes:(id)arg2 ;
+(id)firebaseEventParametersForPredefinedAttributes:(id)arg1 customAttributes:(id)arg2 firebaseEventName:(id)arg3 ;
+(char)shouldUseFailedEventName:(id)arg1 predefinedAttributes:(id)arg2 ;
+(id)failedEventName:(id)arg1 ;
+(char)isFailableEvent:(id)arg1 ;
+(id)predefinedParametersFromPredefinedAttributes:(id)arg1 forFirebaseEventName:(id)arg2 ;
+(id)combinedParametersFromPredefinedParameters:(id)arg1 customParameters:(id)arg2 ;
+(id)sanitizeAttributeName:(id)arg1 ;
+(id)extractBaseParameterDictionaryFromPredefinedAttributes:(id)arg1 withKeyMapping:(id)arg2 ;
+(id)transformedBaseParameters:(id)arg1 forFirebaseEventName:(id)arg2 ;
+(id)firebaseReservedKeys;
+(id)sanitizeKeyName:(id)arg1 ;
-(id)initWithFirebaseAnalyticsClass:(Class)arg1 ;
-(void)setFirebaseAnalytics:(id)arg1 ;
-(id)firebaseAnalytics;
-(void)logCustomEvent:(id)arg1 ;
-(void)logPredefinedEvent:(id)arg1 ;
-(void)logPredefinedEventToFirebaseWithEventName:(id)arg1 parameters:(id)arg2 ;
-(NSArray *)firebaseReservedKeys;
-(void)setFirebaseReservedKeys:(NSArray *)arg1 ;
-(id)init;
-(void)logEvent:(id)arg1 ;
@end

