/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_dispatch_source;
@class NSObject, NSString, NSDate;

@interface APMAlarm : NSObject {

	NSObject*<OS_dispatch_queue> _queue;
	NSObject*<OS_dispatch_source> _timer;
	NSString* _name;
	NSDate* _scheduledTimestamp;

}

@property (nonatomic,readonly) NSDate * scheduledTimestamp;              //@synthesize scheduledTimestamp=_scheduledTimestamp - In the implementation block
-(char)hasActiveTimer;
-(id)initWithDispatchQueue:(id)arg1 name:(id)arg2 ;
-(void)runAfterDelay:(double)arg1 withBlock:(/*^block*/id)arg2 ;
-(NSDate *)scheduledTimestamp;
-(void)cancel;
-(void)dealloc;
@end

