/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDecimalNumber;

@interface APMAudienceComparisonValues : NSObject {

	char _valid;
	NSDecimalNumber* _comparisonValue;
	NSDecimalNumber* _maxComparisonValue;
	NSDecimalNumber* _minComparisonValue;

}

@property (nonatomic,retain) NSDecimalNumber * comparisonValue;                 //@synthesize comparisonValue=_comparisonValue - In the implementation block
@property (nonatomic,retain) NSDecimalNumber * maxComparisonValue;              //@synthesize maxComparisonValue=_maxComparisonValue - In the implementation block
@property (nonatomic,retain) NSDecimalNumber * minComparisonValue;              //@synthesize minComparisonValue=_minComparisonValue - In the implementation block
@property (assign,getter=isValid,nonatomic) char valid;                         //@synthesize valid=_valid - In the implementation block
-(void)setComparisonValue:(NSDecimalNumber *)arg1 ;
-(NSDecimalNumber *)maxComparisonValue;
-(void)setMaxComparisonValue:(NSDecimalNumber *)arg1 ;
-(NSDecimalNumber *)minComparisonValue;
-(void)setMinComparisonValue:(NSDecimalNumber *)arg1 ;
-(char)isValid;
-(void)setValid:(char)arg1 ;
-(NSDecimalNumber *)comparisonValue;
@end

