/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class NSString, NSUserDefaults;

@interface APMUserDefaults : NSObject {

	NSString* _suiteName;
	CFStringRef _appNameRef;
	NSUserDefaults* _userDefaults;
	char _useCFPreferencesLibrary;
	char _isPreferenceFileExcluded;

}

@property (assign) char isPreferenceFileExcluded;                       //@synthesize isPreferenceFileExcluded=_isPreferenceFileExcluded - In the implementation block
@property (assign,nonatomic) char useCFPreferencesLibrary;              //@synthesize useCFPreferencesLibrary=_useCFPreferencesLibrary - In the implementation block
+(char)userPreferenceEnabled;
+(id)standardUserDefaults;
-(void)clearAllData;
-(void)setIsPreferenceFileExcluded:(char)arg1 ;
-(char)isPreferenceFileExcluded;
-(char)useCFPreferencesLibrary;
-(void)setUseCFPreferencesLibrary:(char)arg1 ;
-(void)scheduleSynchronize;
-(void)setFloat:(float)arg1 forKey:(id)arg2 ;
-(id)init;
-(void)dealloc;
-(id)objectForKey:(id)arg1 ;
-(void)removeObjectForKey:(id)arg1 ;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(void)synchronize;
-(id)initWithSuiteName:(id)arg1 ;
-(char)boolForKey:(id)arg1 ;
-(id)stringForKey:(id)arg1 ;
-(void)setBool:(char)arg1 forKey:(id)arg2 ;
-(int)integerForKey:(id)arg1 ;
-(float)floatForKey:(id)arg1 ;
-(id)dictionaryForKey:(id)arg1 ;
-(void)setDouble:(double)arg1 forKey:(id)arg2 ;
-(id)arrayForKey:(id)arg1 ;
-(void)setInteger:(int)arg1 forKey:(id)arg2 ;
-(double)doubleForKey:(id)arg1 ;
@end

