/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <libobjc.A.dylib/CALayerDelegate.h>

@class CALayer, Figure, NSString;

@interface BackgroundLayerDelegate : NSObject <CALayerDelegate> {

	CALayer* layer;
	Figure* figure;
	CGAffineTransform transform;

}

@property (nonatomic,retain) CALayer * layer; 
@property (nonatomic,__weak,readonly) Figure * figure; 
@property (assign,nonatomic) CGAffineTransform transform; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithFigure:(id)arg1 ;
-(Figure *)figure;
-(CALayer *)layer;
-(void)setTransform:(CGAffineTransform)arg1 ;
-(void)dealloc;
-(void)setLayer:(CALayer *)arg1 ;
-(CGAffineTransform)transform;
-(void)drawLayer:(id)arg1 inContext:(CGContextRef)arg2 ;
@end

