/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class NSMutableArray;

@interface CGContextQueue : NSObject {

	CGContextRef context;
	NSMutableArray* executeOperation;
	NSMutableArray* cleanupOperation;
	char immediateMode;
	char renderIsCanceled;
	char isRendering;

}

@property (nonatomic,readonly) CGContextRef context; 
@property (nonatomic,readonly) NSMutableArray * executeOperation; 
@property (nonatomic,readonly) NSMutableArray * cleanupOperation; 
@property (nonatomic,readonly) char immediateMode; 
@property (assign) char renderIsCanceled; 
-(NSMutableArray *)executeOperation;
-(char)renderIsCanceled;
-(id)initWithContext:(CGContextRef)arg1 immediateMode:(char)arg2 ;
-(void)cancelRender;
-(void)_setupQueues;
-(void)setRenderIsCanceled:(char)arg1 ;
-(void)dealloc;
-(CGContextRef)context;
-(void)render;
-(char)immediateMode;
-(NSMutableArray *)cleanupOperation;
@end

