/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:09 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class UIColor;

@interface CheckerPattern : NSObject {

	UIColor* firstColor;
	UIColor* secondColor;
	CGSize size;
	CGColorRef colorRef;
	float scale;

}

@property (nonatomic,readonly) UIColor * firstColor; 
@property (nonatomic,readonly) UIColor * secondColor; 
@property (nonatomic,readonly) CGSize size; 
@property (nonatomic,readonly) CGColorRef colorRef; 
-(id)initWithSize:(CGSize)arg1 firstColor:(id)arg2 secondColor:(id)arg3 ;
-(id)initWithSize:(CGSize)arg1 firstColor:(id)arg2 secondColor:(id)arg3 scale:(float)arg4 ;
-(CGColorRef)colorRef;
-(CGSize)size;
-(void)dealloc;
-(UIColor *)firstColor;
-(UIColor *)secondColor;
@end

