/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSURLSessionDelegate.h>

@protocol CLSBetaControllerDelegate, OS_dispatch_queue;
@class NSString, FABNetworkClient, CLSBetaUpdate, NSTimer, NSObject;

@interface CLSBetaController : NSObject <NSURLSessionDelegate> {

	NSString* _betaToken;
	char _checksSuspended;
	char _retrying;
	id<CLSBetaControllerDelegate> _delegate;
	FABNetworkClient* _networkClient;
	CLSBetaUpdate* _activeUpdate;
	NSTimer* _checkSuspensionTimer;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,readonly) FABNetworkClient * networkClient;                         //@synthesize networkClient=_networkClient - In the implementation block
@property (nonatomic,retain) CLSBetaUpdate * activeUpdate;                               //@synthesize activeUpdate=_activeUpdate - In the implementation block
@property (nonatomic,retain) NSTimer * checkSuspensionTimer;                             //@synthesize checkSuspensionTimer=_checkSuspensionTimer - In the implementation block
@property (assign,nonatomic) char checksSuspended;                                       //@synthesize checksSuspended=_checksSuspended - In the implementation block
@property (assign,nonatomic) char retrying;                                              //@synthesize retrying=_retrying - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> queue;                       //@synthesize queue=_queue - In the implementation block
@property (assign,nonatomic,__weak) id<CLSBetaControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy,readonly) NSString * betaToken; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(char)isBetaSupported;
+(id)pinnnedCertificates;
-(NSString *)betaToken;
-(void)fabricSettingsDownloaded:(id)arg1 ;
-(id)betaEndpoint;
-(id)appBuildVersion;
-(id)appDisplayVersion;
-(id)appInstanceIdentifier;
-(id)appInstallationSource;
-(void)didGetUpdate:(id)arg1 ;
-(void)maybeGetUpdate:(/*^block*/id)arg1 ;
-(char)shouldGetUpdates;
-(void)loadUpdateWithCompletionBlock:(/*^block*/id)arg1 ;
-(id)betaUpdateURL;
-(FABNetworkClient *)networkClient;
-(void)handledCompletedBetaRequestWithData:(id)arg1 error:(id)arg2 completionBlock:(/*^block*/id)arg3 ;
-(void)temporarilySuspendChecks;
-(id)updateWithData:(id)arg1 error:(id*)arg2 ;
-(id)betaUpdateSuspendDurationSecs;
-(void)allowChecks;
-(void)showBetaAlertForUpdate:(id)arg1 ;
-(void)setActiveUpdate:(CLSBetaUpdate *)arg1 ;
-(CLSBetaUpdate *)activeUpdate;
-(NSTimer *)checkSuspensionTimer;
-(void)setCheckSuspensionTimer:(NSTimer *)arg1 ;
-(char)checksSuspended;
-(void)setChecksSuspended:(char)arg1 ;
-(char)retrying;
-(void)setRetrying:(char)arg1 ;
-(id)APIKey;
-(void)setDelegate:(id<CLSBetaControllerDelegate>)arg1 ;
-(void)dealloc;
-(id<CLSBetaControllerDelegate>)delegate;
-(id)settings;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(char)start;
-(id)initWithDelegate:(id)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(id)appBundleIdentifier;
-(void)applicationWillEnterForeground;
-(void)checkForUpdate;
@end

