/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSFileManager, NSArray;

@interface CLSFileManager : NSObject {

	NSString* _rootPath;
	NSFileManager* _underlyingFileManager;

}

@property (nonatomic,readonly) NSFileManager * underlyingFileManager;              //@synthesize underlyingFileManager=_underlyingFileManager - In the implementation block
@property (nonatomic,copy,readonly) NSString * rootPath;                           //@synthesize rootPath=_rootPath - In the implementation block
@property (nonatomic,copy,readonly) NSString * structurePath; 
@property (nonatomic,copy,readonly) NSString * activePath; 
@property (nonatomic,copy,readonly) NSString * processingPath; 
@property (nonatomic,copy,readonly) NSString * pendingPath; 
@property (nonatomic,copy,readonly) NSString * preparedPath; 
@property (nonatomic,readonly) NSArray * activePathContents; 
@property (nonatomic,readonly) NSArray * preparedPathContents; 
@property (nonatomic,readonly) NSArray * processingPathContents; 
-(id)pathNamespace;
-(NSFileManager *)underlyingFileManager;
-(char)removeItemAtPath:(id)arg1 ;
-(void)enumerateFilesInDirectory:(id)arg1 usingBlock:(/*^block*/id)arg2 ;
-(char)moveItemAtPath:(id)arg1 toDirectory:(id)arg2 ;
-(NSString *)structurePath;
-(NSString *)activePath;
-(id)contentsOfDirectory:(id)arg1 ;
-(NSString *)preparedPath;
-(NSString *)processingPath;
-(char)createDirectoryAtPath:(id)arg1 ;
-(char)moveItemsFromDirectory:(id)arg1 toDirectory:(id)arg2 ;
-(NSString *)pendingPath;
-(char)removeContentsOfDirectoryAtPath:(id)arg1 ;
-(char)removeContentsOfProcessingPath;
-(char)removeContentsOfPendingPath;
-(NSArray *)activePathContents;
-(NSArray *)preparedPathContents;
-(NSArray *)processingPathContents;
-(char)prepareForNewLaunch;
-(id)setupNewPathForExecutionIdentifier:(id)arg1 ;
-(void)removeLegacyDirectories;
-(void)enumerateReportsInProcessingDirectoryUsingBlock:(/*^block*/id)arg1 ;
-(void)enumerateFilesInActiveDirectoryUsingBlock:(/*^block*/id)arg1 ;
-(void)enumerateFilesInPreparedDirectoryUsingBlock:(/*^block*/id)arg1 ;
-(char)moveProcessingContentsToPrepared;
-(char)movePendingToProcessing;
-(char)removeContentsOfAllPaths;
-(id)init;
-(NSString *)rootPath;
-(id)fileSizeAtPath:(id)arg1 ;
@end

