/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CLSStackFrame : NSObject {

	NSString* _symbol;
	NSString* _rawSymbol;
	NSString* _library;
	NSString* _fileName;
	unsigned _lineNumber;
	unsigned long long _offset;
	unsigned long long _address;

}

@property (nonatomic,copy) NSString * symbol;                         //@synthesize symbol=_symbol - In the implementation block
@property (nonatomic,copy) NSString * rawSymbol;                      //@synthesize rawSymbol=_rawSymbol - In the implementation block
@property (nonatomic,copy) NSString * library;                        //@synthesize library=_library - In the implementation block
@property (nonatomic,copy) NSString * fileName;                       //@synthesize fileName=_fileName - In the implementation block
@property (assign,nonatomic) unsigned lineNumber;                     //@synthesize lineNumber=_lineNumber - In the implementation block
@property (assign,nonatomic) unsigned long long offset;               //@synthesize offset=_offset - In the implementation block
@property (assign,nonatomic) unsigned long long address;              //@synthesize address=_address - In the implementation block
+(id)stackFrameWithAddress:(unsigned)arg1 ;
+(id)stackFrame;
+(id)stackFrameWithSymbol:(id)arg1 ;
-(NSString *)rawSymbol;
-(void)setRawSymbol:(NSString *)arg1 ;
-(unsigned)lineNumber;
-(id)description;
-(void)setOffset:(unsigned long long)arg1 ;
-(unsigned long long)offset;
-(NSString *)symbol;
-(void)setSymbol:(NSString *)arg1 ;
-(void)setAddress:(unsigned long long)arg1 ;
-(NSString *)library;
-(void)setLibrary:(NSString *)arg1 ;
-(void)setLineNumber:(unsigned)arg1 ;
-(unsigned long long)address;
-(NSString *)fileName;
-(void)setFileName:(NSString *)arg1 ;
@end

