/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
#import <Notability/Notability-Structs.h>
@class NSURL, NSDictionary, NSMutableDictionary, NSObject;

@interface CLSUserDefaults : NSObject {

	char _synchronizeWroteToDisk;
	NSURL* _directoryURL;
	NSURL* _fileURL;
	NSDictionary* _persistedDataDictionary;
	NSMutableDictionary* _dataDictionary;
	NSObject*<OS_dispatch_queue> _serialDictionaryQueue;
	NSObject*<OS_dispatch_queue> _synchronizationQueue;

}

@property (assign,nonatomic) char synchronizeWroteToDisk;                                       //@synthesize synchronizeWroteToDisk=_synchronizeWroteToDisk - In the implementation block
@property (nonatomic,copy,readonly) NSURL * directoryURL;                                       //@synthesize directoryURL=_directoryURL - In the implementation block
@property (nonatomic,copy,readonly) NSURL * fileURL;                                            //@synthesize fileURL=_fileURL - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * persistedDataDictionary;                     //@synthesize persistedDataDictionary=_persistedDataDictionary - In the implementation block
@property (nonatomic,copy,readonly) NSMutableDictionary * dataDictionary;                       //@synthesize dataDictionary=_dataDictionary - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> serialDictionaryQueue;              //@synthesize serialDictionaryQueue=_serialDictionaryQueue - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> synchronizationQueue;               //@synthesize synchronizationQueue=_synchronizationQueue - In the implementation block
+(id)standardUserDefaults;
-(NSObject*<OS_dispatch_queue>)serialDictionaryQueue;
-(id)generateDirectoryURL;
-(id)getEscapedAppBundleIdentifier;
-(id)generateDirectoryURLForBaseURL:(id)arg1 hostAppBundleIdentifier:(id)arg2 ;
-(void)migrateFromNSUserDefaults:(id)arg1 ;
-(id)objectForKeyByMigratingFromNSUserDefaults:(id)arg1 ;
-(char)synchronizeWroteToDisk;
-(void)setSynchronizeWroteToDisk:(char)arg1 ;
-(NSDictionary *)persistedDataDictionary;
-(NSMutableDictionary *)dataDictionary;
-(id)init;
-(void)removeAllObjects;
-(id)objectForKey:(id)arg1 ;
-(void)removeObjectForKey:(id)arg1 ;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(void)synchronize;
-(char)boolForKey:(id)arg1 ;
-(id)stringForKey:(id)arg1 ;
-(void)setBool:(char)arg1 forKey:(id)arg2 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(NSURL *)fileURL;
-(void)setString:(id)arg1 forKey:(id)arg2 ;
-(NSObject*<OS_dispatch_queue>)synchronizationQueue;
-(id)loadDefaults;
-(NSURL *)directoryURL;
@end

