/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDictionary, NSURLCache;

@interface CLSURLSessionConfiguration : NSObject <NSCopying> {

	NSDictionary* _additionalHeaders;
	NSURLCache* _URLCache;
	unsigned _cookiePolicy;
	char _allowsCellularAccess;
	double _timeoutIntervalForRequest;
	double _timeoutIntervalForResource;

}

@property (nonatomic,copy) NSDictionary * HTTPAdditionalHeaders;              //@synthesize additionalHeaders=_additionalHeaders - In the implementation block
@property (nonatomic,retain) NSURLCache * URLCache;                           //@synthesize URLCache=_URLCache - In the implementation block
@property (assign,nonatomic) unsigned HTTPCookieAcceptPolicy;                 //@synthesize cookiePolicy=_cookiePolicy - In the implementation block
@property (assign,nonatomic) char sessionSendsLaunchEvents; 
@property (assign,nonatomic) double timeoutIntervalForRequest;                //@synthesize timeoutIntervalForRequest=_timeoutIntervalForRequest - In the implementation block
@property (assign,nonatomic) double timeoutIntervalForResource;               //@synthesize timeoutIntervalForResource=_timeoutIntervalForResource - In the implementation block
@property (assign,nonatomic) char allowsCellularAccess;                       //@synthesize allowsCellularAccess=_allowsCellularAccess - In the implementation block
+(id)backgroundSessionConfiguration:(id)arg1 ;
+(id)ephemeralSessionConfiguration;
+(id)defaultSessionConfiguration;
+(id)backgroundSessionConfigurationWithIdentifier:(id)arg1 ;
-(NSDictionary *)HTTPAdditionalHeaders;
-(void)setHTTPAdditionalHeaders:(NSDictionary *)arg1 ;
-(unsigned)HTTPCookieAcceptPolicy;
-(void)setSessionSendsLaunchEvents:(char)arg1 ;
-(char)sessionSendsLaunchEvents;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setAllowsCellularAccess:(char)arg1 ;
-(void)setURLCache:(NSURLCache *)arg1 ;
-(NSURLCache *)URLCache;
-(char)allowsCellularAccess;
-(double)timeoutIntervalForResource;
-(void)setHTTPCookieAcceptPolicy:(unsigned)arg1 ;
-(void)setTimeoutIntervalForRequest:(double)arg1 ;
-(double)timeoutIntervalForRequest;
-(void)setTimeoutIntervalForResource:(double)arg1 ;
@end

