/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>

@class UIColor, NSArray, UIScrollView;

@interface ColorSelectorView : UIView {

	UIColor* selectedColor;
	id delegate;
	char ignoreAlpha;
	NSArray* colorButtonArray;
	UIScrollView* iconRowScrollView;
	int numRowsForScrollingView;
	NSArray* _colors;

}

@property (retain) NSArray * colors;                                   //@synthesize colors=_colors - In the implementation block
@property (assign,nonatomic,__weak) id delegate; 
@property (assign,nonatomic) char ignoreAlpha; 
@property (assign,nonatomic) int numRowsForScrollingView; 
@property (nonatomic,retain) UIColor * selectedColor; 
+(CGSize)colorViewSize;
+(CGSize)colorViewMarginSize;
+(CGRect)frameForRows:(int)arg1 columns:(int)arg2 ;
-(void)colorButtonAction:(id)arg1 ;
-(void)setNumRowsForScrollingView:(int)arg1 ;
-(int)numRowsForScrollingView;
-(void)setIgnoreAlpha:(char)arg1 ;
-(int)findColorIndex:(id)arg1 ;
-(void)updateSelectedColorUI;
-(id)initWithColumns:(int)arg1 rows:(int)arg2 ;
-(id)initInScrollingViewWithFrame:(CGRect)arg1 ;
-(char)ignoreAlpha;
-(void)layoutSubviews;
-(void)setColors:(NSArray *)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(NSArray *)colors;
-(void)willMoveToWindow:(id)arg1 ;
-(id)colorPalette;
-(UIColor *)selectedColor;
-(void)setSelectedColor:(UIColor *)arg1 ;
@end

