/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSNumber;

@interface ControlPoint : NSObject <NSCopying> {

	char _isPredictive;
	char _expectsUpdateToForce;
	float _force;
	NSNumber* _estimationUpdateIndex;
	CGPoint _p;
	double _t;

}

@property (assign,p,nonatomic) CGPoint p;                                   //@synthesize p=_p - In the implementation block
@property (assign,t,nonatomic) double t;                                    //@synthesize t=_t - In the implementation block
@property (assign,nonatomic) char isPredictive;                             //@synthesize isPredictive=_isPredictive - In the implementation block
@property (assign,nonatomic) float force;                                   //@synthesize force=_force - In the implementation block
@property (nonatomic,retain) NSNumber * estimationUpdateIndex;              //@synthesize estimationUpdateIndex=_estimationUpdateIndex - In the implementation block
@property (assign,nonatomic) char expectsUpdateToForce;                     //@synthesize expectsUpdateToForce=_expectsUpdateToForce - In the implementation block
-(id)initWithLocation:(CGPoint)arg1 timestamp:(double)arg2 predictive:(char)arg3 ;
-(char)isPredictive;
-(char)expectsUpdateToForce;
-(id)initWithLocation:(CGPoint)arg1 timestamp:(double)arg2 predictive:(char)arg3 force:(float)arg4 estimationUpdateIndex:(id)arg5 expectsUpdateToForce:(char)arg6 ;
-(void)setExpectsUpdateToForce:(char)arg1 ;
-(id)updatedCopyWithForce:(float)arg1 estimated:(char)arg2 ;
-(void)setP:(CGPoint)arg1 ;
-(void)setT:(double)arg1 ;
-(void)setIsPredictive:(char)arg1 ;
-(void)setEstimationUpdateIndex:(NSNumber *)arg1 ;
-(id)description;
-(void)setForce:(float)arg1 ;
-(float)force;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSNumber *)estimationUpdateIndex;
-(double)t;
-(CGPoint)p;
@end

