/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSStreamDelegate.h>

@class NSString, NSOutputStream, NSData;

@interface FABMultipartMimeStreamEncoder : NSObject <NSStreamDelegate> {

	unsigned _length;
	NSString* _boundary;
	NSOutputStream* _outputStream;

}

@property (assign,nonatomic) unsigned length;                                             //@synthesize length=_length - In the implementation block
@property (nonatomic,copy) NSString * boundary;                                           //@synthesize boundary=_boundary - In the implementation block
@property (nonatomic,copy,readonly) NSData * headerData; 
@property (nonatomic,copy,readonly) NSData * footerData; 
@property (nonatomic,retain) NSOutputStream * outputStream;                               //@synthesize outputStream=_outputStream - In the implementation block
@property (nonatomic,copy,readonly) NSString * contentTypeHTTPHeaderValue; 
@property (nonatomic,copy,readonly) NSString * contentLengthHTTPHeaderValue; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)generateBoundary;
+(id)encoderWithStream:(id)arg1 andBoundary:(id)arg2 ;
+(id)contentTypeHTTPHeaderValueWithBoundary:(id)arg1 ;
+(void)populateRequest:(id)arg1 withDataFromEncoder:(/*^block*/id)arg2 ;
-(void)addValue:(id)arg1 fieldName:(id)arg2 ;
-(void)encode:(/*^block*/id)arg1 ;
-(void)addFile:(id)arg1 fileName:(id)arg2 mimeType:(id)arg3 fieldName:(id)arg4 ;
-(id)initWithStream:(id)arg1 andBoundary:(id)arg2 ;
-(NSString *)contentTypeHTTPHeaderValue;
-(NSString *)contentLengthHTTPHeaderValue;
-(void)beginEncoding;
-(NSData *)footerData;
-(void)addFileData:(id)arg1 fileName:(id)arg2 mimeType:(id)arg3 fieldName:(id)arg4 ;
-(char)writeBytes:(const void*)arg1 ofLength:(unsigned)arg2 ;
-(void)setBoundary:(NSString *)arg1 ;
-(NSString *)boundary;
-(unsigned)length;
-(void)setLength:(unsigned)arg1 ;
-(void)writeData:(id)arg1 ;
-(NSOutputStream *)outputStream;
-(void)setOutputStream:(NSOutputStream *)arg1 ;
-(void)endEncoding;
-(NSData *)headerData;
@end

