/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/FABDownloadAndSaveSettingsOperationDelegate.h>
#import <Notability/FABOnboardingOperationDelegate.h>

@class FABApplicationIdentiferModel, FABSettings, FABOnboardingOperation, NSFileManager, NSDictionary, NSString, FABNetworkClient;

@interface FABSettingsOnboardingManager : NSObject <FABDownloadAndSaveSettingsOperationDelegate, FABOnboardingOperationDelegate> {

	char _hasAttemptedAppConfigure;
	FABApplicationIdentiferModel* _appIdentifierModel;
	FABSettings* _settingsModel;
	FABOnboardingOperation* _onboardingOperation;
	NSFileManager* _fileManager;
	NSDictionary* _configuration;
	NSDictionary* _defaultConfiguration;
	NSString* _APIKey;
	NSDictionary* _kitVersionsByKitBundleIdentifier;
	FABNetworkClient* _networkClient;

}

@property (nonatomic,retain) FABSettings * settingsModel;                                    //@synthesize settingsModel=_settingsModel - In the implementation block
@property (nonatomic,retain) FABOnboardingOperation * onboardingOperation;                   //@synthesize onboardingOperation=_onboardingOperation - In the implementation block
@property (nonatomic,retain) FABApplicationIdentiferModel * appIdentifierModel;              //@synthesize appIdentifierModel=_appIdentifierModel - In the implementation block
@property (nonatomic,retain) NSFileManager * fileManager;                                    //@synthesize fileManager=_fileManager - In the implementation block
@property (assign,nonatomic) char hasAttemptedAppConfigure;                                  //@synthesize hasAttemptedAppConfigure=_hasAttemptedAppConfigure - In the implementation block
@property (nonatomic,retain) NSDictionary * configuration;                                   //@synthesize configuration=_configuration - In the implementation block
@property (nonatomic,retain) NSDictionary * defaultConfiguration;                            //@synthesize defaultConfiguration=_defaultConfiguration - In the implementation block
@property (nonatomic,copy) NSString * APIKey;                                                //@synthesize APIKey=_APIKey - In the implementation block
@property (nonatomic,copy) NSDictionary * kitVersionsByKitBundleIdentifier;                  //@synthesize kitVersionsByKitBundleIdentifier=_kitVersionsByKitBundleIdentifier - In the implementation block
@property (nonatomic,readonly) FABNetworkClient * networkClient;                             //@synthesize networkClient=_networkClient - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)settingsDirectoryPath;
-(FABNetworkClient *)networkClient;
-(void)setKitVersionsByKitBundleIdentifier:(NSDictionary *)arg1 ;
-(void)beginSettingsDownload;
-(id)settingsURL;
-(id)settingsPath;
-(FABApplicationIdentiferModel *)appIdentifierModel;
-(FABOnboardingOperation *)onboardingOperation;
-(NSDictionary *)kitVersionsByKitBundleIdentifier;
-(void)setOnboardingOperation:(FABOnboardingOperation *)arg1 ;
-(id)advertisingToken;
-(void)finishNetworkingSession;
-(FABSettings *)settingsModel;
-(char)hasAttemptedAppConfigure;
-(void)postSettingsDownloadCompletedNotification;
-(void)setHasAttemptedAppConfigure:(char)arg1 ;
-(void)beginOnboarding:(char)arg1 endpointString:(id)arg2 ;
-(void)operation:(id)arg1 didDownloadAndSaveSettingsWithError:(id)arg2 ;
-(void)onboardingOperation:(id)arg1 didCompleteAppUpdateWithError:(id)arg2 ;
-(void)onboardingOperation:(id)arg1 didCompleteAppCreationWithError:(id)arg2 ;
-(id)initWithApplicationIdentifierModel:(id)arg1 ;
-(void)beginSettingsAndOnboardingOperationsWithAPIKey:(id)arg1 kitVersionsByKitBundleIdentifier:(id)arg2 ;
-(void)setAppIdentifierModel:(FABApplicationIdentiferModel *)arg1 ;
-(void)setSettingsModel:(FABSettings *)arg1 ;
-(void)setDefaultConfiguration:(NSDictionary *)arg1 ;
-(void)setAPIKey:(NSString *)arg1 ;
-(NSString *)APIKey;
-(NSDictionary *)defaultConfiguration;
-(void)setConfiguration:(NSDictionary *)arg1 ;
-(NSDictionary *)configuration;
-(void)setFileManager:(NSFileManager *)arg1 ;
-(id)valueForConfigurationKey:(id)arg1 ;
-(NSFileManager *)fileManager;
@end

