/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/NIViewController.h>
#import <UIKit/UIToolbarDelegate.h>
#import <Notability/GLPopoverControllerDelegate.h>
#import <Notability/TabbedColorSelectorDelegate.h>

@protocol FigureEditorDelegate;
@class FigureEditorToolbar, PaintingView, ImageMediaObject, NSArray, NSString;

@interface FigureEditorViewController : NIViewController <UIToolbarDelegate, GLPopoverControllerDelegate, TabbedColorSelectorDelegate> {

	FigureEditorToolbar* toolbar;
	PaintingView* paintingView;
	ImageMediaObject* mediaObjectToEdit;
	id<FigureEditorDelegate> delegate;
	NSArray* _customConstraints;
	int _universalSizeClass;

}

@property (retain) NSArray * customConstraints;                                     //@synthesize customConstraints=_customConstraints - In the implementation block
@property (assign,nonatomic) int universalSizeClass;                                //@synthesize universalSizeClass=_universalSizeClass - In the implementation block
@property (assign,nonatomic,__weak) id<FigureEditorDelegate> delegate; 
@property (nonatomic,readonly) ImageMediaObject * mediaObjectToEdit; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setUniversalSizeClass:(int)arg1 ;
-(int)universalSizeClass;
-(void)selectToolAction:(id)arg1 ;
-(void)strokeFillAction:(id)arg1 ;
-(void)strokeWidthAction:(id)arg1 ;
-(void)undoAction:(id)arg1 ;
-(void)redoAction:(id)arg1 ;
-(void)cropAction:(id)arg1 ;
-(void)lineWidthSliderAction:(id)arg1 ;
-(void)resetFramesForSizeChange;
-(NSArray *)customConstraints;
-(void)setCustomConstraints:(NSArray *)arg1 ;
-(void)selectedShapeDidChange:(id)arg1 ;
-(void)setUIToMatchDrawModeAndParameters;
-(void)updateConstraintsForView;
-(void)setSelectToolIcon;
-(void)setStrokeWidthUI;
-(void)setCropUI;
-(void)tabbledColorSelectorView:(id)arg1 didSwitchTabs:(char)arg2 ;
-(void)tabbedColorSelectorView:(id)arg1 didSelectFirstColor:(id)arg2 ;
-(void)tabbedColorSelectorView:(id)arg1 didSelectSecondColor:(id)arg2 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 mediaObject:(id)arg3 ;
-(void)loadMediaObject:(id)arg1 ;
-(ImageMediaObject *)mediaObjectToEdit;
-(void)setDelegate:(id<FigureEditorDelegate>)arg1 ;
-(void)dealloc;
-(id<FigureEditorDelegate>)delegate;
-(void)viewWillLayoutSubviews;
-(int)positionForBar:(id)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)viewDidLoad;
-(CGRect)canvasFrame;
-(void)cancelAction:(id)arg1 ;
-(void)modeSelected:(id)arg1 ;
-(void)doneAction:(id)arg1 ;
@end

