/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FIRClearcutRequest : NSObject {

	int _logSource;
	NSString* _account;
	NSString* _path;

}

@property (nonatomic,readonly) int logSource;                        //@synthesize logSource=_logSource - In the implementation block
@property (nonatomic,copy,readonly) NSString * account;              //@synthesize account=_account - In the implementation block
@property (nonatomic,copy,readonly) NSString * path;                 //@synthesize path=_path - In the implementation block
-(id)initWithLogSource:(int)arg1 account:(id)arg2 path:(id)arg3 ;
-(int)logSource;
-(NSString *)path;
-(NSString *)account;
@end

