/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/GULNetworkReachabilityDelegate.h>

@protocol OS_dispatch_queue, FIRClearcutLoggerDelegate;
@class NSObject, NSString, NSURL, NSMutableDictionary, GULNetwork, NSMutableArray;

@interface FIRClearcutLogger : NSObject <GULNetworkReachabilityDelegate> {

	NSObject*<OS_dispatch_queue> _queue;
	AI _backgroundTaskId;
	NSObject* _pendingRequestsLock;
	char _sendScheduled;
	NSString* _applicationBuild;
	unsigned _maxRequestNumBytes;
	NSString* _installIdentifier;
	NSURL* _serverURL;
	NSString* _zwiebackCookie;
	int _fetcherCookieStorageMethod;
	id<FIRClearcutLoggerDelegate> _delegate;
	NSString* _logDirectory;
	NSMutableDictionary* _accounts;
	int _uploadRetriesRemaining;
	GULNetwork* _network;
	NSMutableArray* _pendingRequests;
	long long _sendDelayMillis;

}

@property (nonatomic,copy) NSString * logDirectory;                                      //@synthesize logDirectory=_logDirectory - In the implementation block
@property (nonatomic,copy,readonly) NSMutableDictionary * accounts;                      //@synthesize accounts=_accounts - In the implementation block
@property (assign,nonatomic) long long sendDelayMillis;                                  //@synthesize sendDelayMillis=_sendDelayMillis - In the implementation block
@property (assign,nonatomic) int uploadRetriesRemaining;                                 //@synthesize uploadRetriesRemaining=_uploadRetriesRemaining - In the implementation block
@property (assign,nonatomic) char sendScheduled;                                         //@synthesize sendScheduled=_sendScheduled - In the implementation block
@property (nonatomic,retain) GULNetwork * network;                                       //@synthesize network=_network - In the implementation block
@property (nonatomic,copy,readonly) NSMutableArray * pendingRequests;                    //@synthesize pendingRequests=_pendingRequests - In the implementation block
@property (assign,nonatomic) unsigned backgroundTaskId; 
@property (copy) NSString * applicationBuild;                                            //@synthesize applicationBuild=_applicationBuild - In the implementation block
@property (assign) unsigned maxRequestNumBytes;                                          //@synthesize maxRequestNumBytes=_maxRequestNumBytes - In the implementation block
@property (copy) NSString * installIdentifier;                                           //@synthesize installIdentifier=_installIdentifier - In the implementation block
@property (copy) NSURL * serverURL;                                                      //@synthesize serverURL=_serverURL - In the implementation block
@property (copy) NSString * zwiebackCookie;                                              //@synthesize zwiebackCookie=_zwiebackCookie - In the implementation block
@property (assign,nonatomic) int fetcherCookieStorageMethod;                             //@synthesize fetcherCookieStorageMethod=_fetcherCookieStorageMethod - In the implementation block
@property (assign,nonatomic,__weak) id<FIRClearcutLoggerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)sharedInstance;
-(NSString *)installIdentifier;
-(void)flushWriters;
-(void)scheduleNextSend;
-(void)setBackgroundTaskId:(unsigned)arg1 ;
-(void)sendLogsWithCompletionHandler:(/*^block*/id)arg1 ;
-(id)accountDataForAccount:(id)arg1 ;
-(unsigned)maxRequestNumBytes;
-(NSString *)applicationBuild;
-(NSString *)zwiebackCookie;
-(unsigned)backgroundTaskId;
-(void)updatePendingRequests;
-(void)sendNextPendingRequestWithCompletionHandler:(/*^block*/id)arg1 ;
-(char)sendScheduled;
-(void)setSendScheduled:(char)arg1 ;
-(long long)sendDelayMillis;
-(int)uploadRetriesRemaining;
-(id)nextPendingRequest;
-(id)logRequestFromPath:(id)arg1 logSource:(int)arg2 ;
-(void)setUploadRetriesRemaining:(int)arg1 ;
-(void)logEvent:(id)arg1 logSource:(int)arg2 account:(id)arg3 ;
-(void)setApplicationBuild:(NSString *)arg1 ;
-(void)setMaxRequestNumBytes:(unsigned)arg1 ;
-(void)setInstallIdentifier:(NSString *)arg1 ;
-(void)setZwiebackCookie:(NSString *)arg1 ;
-(int)fetcherCookieStorageMethod;
-(void)setFetcherCookieStorageMethod:(int)arg1 ;
-(void)setLogDirectory:(NSString *)arg1 ;
-(void)setSendDelayMillis:(long long)arg1 ;
-(void)reachabilityDidChange;
-(void)flushWithCompletionHandler:(/*^block*/id)arg1 ;
-(NSURL *)serverURL;
-(id)init;
-(void)setDelegate:(id<FIRClearcutLoggerDelegate>)arg1 ;
-(void)dealloc;
-(id<FIRClearcutLoggerDelegate>)delegate;
-(void)applicationDidEnterBackground:(id)arg1 ;
-(NSString *)logDirectory;
-(GULNetwork *)network;
-(void)setNetwork:(GULNetwork *)arg1 ;
-(void)setServerURL:(NSURL *)arg1 ;
-(NSMutableDictionary *)accounts;
-(NSMutableArray *)pendingRequests;
@end

