/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/FIRInstanceIDStoreDelegate.h>

@class FIRInstanceIDAuthService, FIRInstanceIDStore, NSOperationQueue, FIRInstanceIDAPNSInfo, NSString;

@interface FIRInstanceIDTokenManager : NSObject <FIRInstanceIDStoreDelegate> {

	FIRInstanceIDAuthService* _authService;
	FIRInstanceIDStore* _instanceIDStore;
	NSOperationQueue* _tokenOperations;
	FIRInstanceIDAPNSInfo* _currentAPNSInfo;

}

@property (nonatomic,retain) FIRInstanceIDStore * instanceIDStore;                 //@synthesize instanceIDStore=_instanceIDStore - In the implementation block
@property (nonatomic,retain) FIRInstanceIDAuthService * authService;               //@synthesize authService=_authService - In the implementation block
@property (nonatomic,readonly) NSOperationQueue * tokenOperations;                 //@synthesize tokenOperations=_tokenOperations - In the implementation block
@property (nonatomic,retain) FIRInstanceIDAPNSInfo * currentAPNSInfo;              //@synthesize currentAPNSInfo=_currentAPNSInfo - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)stopAllTokenOperations;
-(id)cachedTokenInfoWithAuthorizedEntity:(id)arg1 scope:(id)arg2 ;
-(FIRInstanceIDAuthService *)authService;
-(void)fetchNewTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 keyPair:(id)arg3 options:(id)arg4 handler:(/*^block*/id)arg5 ;
-(void)deleteTokenWithAuthorizedEntity:(id)arg1 scope:(id)arg2 keyPair:(id)arg3 handler:(/*^block*/id)arg4 ;
-(void)deleteAllTokensWithKeyPair:(id)arg1 handler:(/*^block*/id)arg2 ;
-(char)deleteAllTokensLocallyWithError:(id*)arg1 ;
-(char)checkForTokenRefreshPolicy;
-(id)updateTokensToAPNSDeviceToken:(id)arg1 isSandbox:(char)arg2 ;
-(void)store:(id)arg1 didDeleteFCMScopedTokensForCheckin:(id)arg2 ;
-(void)configureTokenOperations;
-(id)createFetchOperationWithAuthorizedEntity:(id)arg1 scope:(id)arg2 options:(id)arg3 keyPair:(id)arg4 ;
-(FIRInstanceIDStore *)instanceIDStore;
-(NSOperationQueue *)tokenOperations;
-(id)createDeleteOperationWithAuthorizedEntity:(id)arg1 scope:(id)arg2 checkinPreferences:(id)arg3 keyPair:(id)arg4 action:(int)arg5 ;
-(FIRInstanceIDAPNSInfo *)currentAPNSInfo;
-(void)setCurrentAPNSInfo:(FIRInstanceIDAPNSInfo *)arg1 ;
-(void)setAuthService:(FIRInstanceIDAuthService *)arg1 ;
-(void)setInstanceIDStore:(FIRInstanceIDStore *)arg1 ;
-(id)init;
-(void)dealloc;
@end

