/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/FIRInstanceIDTokenOperation.h>

@interface FIRInstanceIDTokenFetchOperation : FIRInstanceIDTokenOperation
-(void)handleResponseWithData:(id)arg1 response:(id)arg2 error:(id)arg3 ;
-(id)parseFetchTokenResponse:(id)arg1 ;
-(void)performTokenOperation;
-(id)initWithAuthorizedEntity:(id)arg1 scope:(id)arg2 options:(id)arg3 checkinPreferences:(id)arg4 keyPair:(id)arg5 ;
@end

