/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FontMetricsProvider <NSObject>
@required
-(id)characterBoundingBoxes:(shared_ptr<myscript::iink::text::Text>*)arg1 spans:(vector<myscript::iink::text::TextSpan, std::__1::allocator<myscript::iink::text::TextSpan> >Ref)arg2;
-(float)getFontSizePixelsWithStyle:(const Style*)arg1;

@end

