/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@interface GingerLabsCircularAudioBuffer : NSObject {

	AudioStreamBasicDescription format;
	AudioBufferList* bufferList;
	unsigned long currentFrameIndex;
	unsigned long frames;
	float duration;

}

@property (assign) AudioStreamBasicDescription format; 
@property (assign) unsigned long frames; 
@property (assign) unsigned long currentFrameIndex; 
@property (assign) AudioBufferList* bufferList; 
@property (assign) float duration; 
-(id)initWithInternalFormat:(AudioStreamBasicDescription)arg1 duration:(float)arg2 ;
-(void)recordBuffers:(AudioBufferList*)arg1 numFrames:(int)arg2 ;
-(void)copyFramesFromIndex:(int)arg1 numFrames:(int)arg2 destinationBuffers:(AudioBufferList*)arg3 ;
-(AudioBufferList*)bufferList;
-(void)setBufferList:(AudioBufferList*)arg1 ;
-(void)dealloc;
-(float)duration;
-(void)setDuration:(float)arg1 ;
-(AudioStreamBasicDescription)format;
-(void)setFormat:(AudioStreamBasicDescription)arg1 ;
-(void)setCurrentFrameIndex:(unsigned long)arg1 ;
-(unsigned long)currentFrameIndex;
-(void)setFrames:(unsigned long)arg1 ;
-(unsigned long)frames;
@end

