/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>

@class UIImageView;

@interface GLActivityIndicatorView : UIView {

	char _shouldAnimate;
	UIImageView* _maskView;
	UIImageView* _spinnerView;

}

@property (nonatomic,retain) UIImageView * maskView;                 //@synthesize maskView=_maskView - In the implementation block
@property (nonatomic,retain) UIImageView * spinnerView;              //@synthesize spinnerView=_spinnerView - In the implementation block
@property (assign,nonatomic) char shouldAnimate;                     //@synthesize shouldAnimate=_shouldAnimate - In the implementation block
@property (nonatomic,readonly) char isAnimating; 
-(void)restartAnimationIfNeeded;
-(void)dealloc;
-(char)shouldAnimate;
-(void)setMaskView:(UIImageView *)arg1 ;
-(UIImageView *)maskView;
-(CGSize)intrinsicContentSize;
-(id)initWithStyle:(int)arg1 ;
-(char)isAnimating;
-(void)stopAnimating;
-(void)startAnimating;
-(void)setShouldAnimate:(char)arg1 ;
-(UIImageView *)spinnerView;
-(void)setSpinnerView:(UIImageView *)arg1 ;
@end

