/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@protocol GLAlbumPickerDelegate;
@class NSArray, UITableView, NSString;

@interface GLAlbumPickerView : UIView <UITableViewDelegate, UITableViewDataSource> {

	NSArray* _sections;
	id<GLAlbumPickerDelegate> _delegate;
	UITableView* _tableView;

}

@property (retain) UITableView * tableView;                                          //@synthesize tableView=_tableView - In the implementation block
@property (nonatomic,retain) NSArray * sections; 
@property (assign,nonatomic,__weak) id<GLAlbumPickerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)toplevelSections;
+(char)collectionFetchResultContainsImages:(id)arg1 recursive:(char)arg2 ;
+(char)collectionContainsImages:(id)arg1 recursive:(char)arg2 ;
+(id)arrayOfCollectionsInCollectionFetchResults:(id)arg1 ;
+(id)sectionsForCollection:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<GLAlbumPickerDelegate>)arg1 ;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2 ;
-(id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id<GLAlbumPickerDelegate>)delegate;
-(void)setTableView:(UITableView *)arg1 ;
-(UITableView *)tableView;
-(void)setSections:(NSArray *)arg1 ;
-(NSArray *)sections;
-(id)collectionAtIndexPath:(id)arg1 ;
@end

