/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol GLCloudRequestProtocol <NSObject>
@required
+(Class)metadataClass;
+(char)fileImportable:(id)arg1;
+(id)requestWithAction:(int)arg1;
+(id)hugeImage;
+(char)canDeleteLocalPathAfterExport;
+(void)loggedIn:(char)arg1 withRequest:(id)arg2;
+(char)authorizeWithPresentationController:(id)arg1 window:(id)arg2 completion:(/*^block*/id)arg3;
+(int)pathStyle;
+(id)serviceOptions;
+(id)localizedActionTextForSendingMultiple:(char)arg1;
+(char)authorize:(/*^block*/id)arg1;
+(id)mediumImage;
+(char)fileBatchImportable:(id)arg1;
+(id)supportedImportFormats;
+(id)supportedBatchImportFormats;
+(id)supportedExportFormats;
+(char)isLinked;
+(id)displayName;
+(id)plistName;
+(char)available;
+(id)smallImage;
+(id)largeImage;
-(void)cancel;
-(void)begin;

@end

