/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:07 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/GLCollectionViewContentProvider.h>

@protocol GLCollectionViewColorProviderDirectionDelegate;
@class NSString, UIColor;

@interface GLCollectionViewColorContentProvider : GLCollectionViewContentProvider {

	char _blank;
	char _plusSymbol;
	char _isCustomizable;
	id<GLCollectionViewColorProviderDirectionDelegate> _delegate;
	NSString* _identifier;
	UIColor* _color;
	int _direction;

}

@property (assign,nonatomic,__weak) id<GLCollectionViewColorProviderDirectionDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString * identifier;                                                             //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,retain) UIColor * color;                                                                 //@synthesize color=_color - In the implementation block
@property (assign,nonatomic) int direction;                                                                   //@synthesize direction=_direction - In the implementation block
@property (assign,nonatomic) char blank;                                                                      //@synthesize blank=_blank - In the implementation block
@property (assign,nonatomic) char plusSymbol;                                                                 //@synthesize plusSymbol=_plusSymbol - In the implementation block
@property (assign,nonatomic) char isCustomizable;                                                             //@synthesize isCustomizable=_isCustomizable - In the implementation block
+(id)reuseIdentifier;
+(Class)cellClass;
-(id)initBlankContent;
-(id)initPlusSymbol;
-(id)initPageControlWithDirection:(int)arg1 ;
-(char)blank;
-(void)setBlank:(char)arg1 ;
-(char)plusSymbol;
-(void)setPlusSymbol:(char)arg1 ;
-(char)isCustomizable;
-(void)setIsCustomizable:(char)arg1 ;
-(void)setDelegate:(id<GLCollectionViewColorProviderDirectionDelegate>)arg1 ;
-(id<GLCollectionViewColorProviderDirectionDelegate>)delegate;
-(NSString *)identifier;
-(UIColor *)color;
-(void)setColor:(UIColor *)arg1 ;
-(void)setIdentifier:(NSString *)arg1 ;
-(void)setDirection:(int)arg1 ;
-(int)direction;
-(id)initWithColor:(id)arg1 ;
@end

