/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/GLCollectionViewContentProvider.h>

@class UIImage;

@interface GLCollectionViewPDFPageContentProvider : GLCollectionViewContentProvider {

	UIImage* _thumbnail;
	int _pageNumber;
	CGPDFPageRef _page;
	CGPDFDocumentRef _document;

}

@property (assign,nonatomic) int pageNumber;                         //@synthesize pageNumber=_pageNumber - In the implementation block
@property (assign,nonatomic) CGPDFPageRef page;                      //@synthesize page=_page - In the implementation block
@property (assign,nonatomic) CGPDFDocumentRef document;              //@synthesize document=_document - In the implementation block
+(id)pdfPageContentProviderWithPageNumber:(int)arg1 pdfPage:(CGPDFPageRef)arg2 pdfDocument:(CGPDFDocumentRef)arg3 ;
+(id)contentProvidersFromPDFURL:(id)arg1 ;
+(id)reuseIdentifier;
+(Class)cellClass;
-(id)init;
-(void)dealloc;
-(CGPDFDocumentRef)document;
-(CGPDFPageRef)page;
-(void)setPage:(CGPDFPageRef)arg1 ;
-(id)thumbnail;
-(void)setDocument:(CGPDFDocumentRef)arg1 ;
-(int)pageNumber;
-(void)setPageNumber:(int)arg1 ;
@end

