/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UICollectionViewController.h>

@protocol GLCollectionViewControllerDelegate;
@class NSArray;

@interface GLCollectionViewController : UICollectionViewController {

	char _isVisible;
	NSArray* _contentProviders;
	id<GLCollectionViewControllerDelegate> _delegate;
	float _minimumLineSpacing;
	float _minimumInteritemSpacing;
	int _scrollDirection;
	UIEdgeInsets _insets;

}

@property (assign,nonatomic) char isVisible;                                                      //@synthesize isVisible=_isVisible - In the implementation block
@property (nonatomic,retain) NSArray * contentProviders;                                          //@synthesize contentProviders=_contentProviders - In the implementation block
@property (assign,nonatomic,__weak) id<GLCollectionViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) float minimumLineSpacing;                                            //@synthesize minimumLineSpacing=_minimumLineSpacing - In the implementation block
@property (assign,nonatomic) float minimumInteritemSpacing;                                       //@synthesize minimumInteritemSpacing=_minimumInteritemSpacing - In the implementation block
@property (assign,nonatomic) UIEdgeInsets insets;                                                 //@synthesize insets=_insets - In the implementation block
@property (assign,nonatomic) int scrollDirection;                                                 //@synthesize scrollDirection=_scrollDirection - In the implementation block
+(id)collectionViewControllerWithContentProviders:(id)arg1 ;
+(id)paperLineCollectionViewControllerWithSelectedPaperIndex:(int)arg1 shouldShowNoLinesCellLarge:(char)arg2 ;
+(id)allContentProviders;
+(id)paperCollectionViewController;
+(id)paperLineCollectionViewControllerWithSelectedPaperIndex:(int)arg1 ;
-(id)initWithContentProviders:(id)arg1 ;
-(void)setIsVisible:(char)arg1 ;
-(id)initWithContentProviders:(id)arg1 collectionViewLayout:(id)arg2 ;
-(void)setContentProviders:(id)arg1 reloadData:(char)arg2 ;
-(id)selectedContentProvider;
-(id)__contentProviderAtRow:(int)arg1 ;
-(CGRect)rectForCollectionViewToFitColumns:(int)arg1 ;
-(void)sizeCollectionViewToFitContent;
-(id)contentProviderAtIndexPath:(id)arg1 ;
-(void)selectFirstIndexPassingTest:(/*^block*/id)arg1 ;
-(void)preserveSelectionAfterPerformingBlock:(/*^block*/id)arg1 ;
-(int)firstIndexPassingTest:(/*^block*/id)arg1 ;
-(void)deselectAllIndexesAnimated:(char)arg1 ;
-(void)selectFirstIndexPassingTest:(/*^block*/id)arg1 animated:(char)arg2 ;
-(NSArray *)contentProviders;
-(char)isSelectedItemAtIndexPath:(id)arg1 ;
-(void)setContentProviders:(NSArray *)arg1 ;
-(void)sizeCollectionViewToFitColumns:(int)arg1 ;
-(id)selectedContentProviders;
-(void)reloadDataAndPreserveSelection;
-(void)performIfIsVisibleWithBlock:(/*^block*/id)arg1 ;
-(void)setDelegate:(id<GLCollectionViewControllerDelegate>)arg1 ;
-(id<GLCollectionViewControllerDelegate>)delegate;
-(void)setScrollDirection:(int)arg1 ;
-(void)setMinimumInteritemSpacing:(float)arg1 ;
-(void)setMinimumLineSpacing:(float)arg1 ;
-(float)minimumLineSpacing;
-(float)minimumInteritemSpacing;
-(int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInCollectionView:(id)arg1 ;
-(char)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2 ;
-(char)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2 ;
-(char)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2 ;
-(UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(int)arg3 ;
-(float)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(int)arg3 ;
-(float)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(int)arg3 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3 ;
-(char)isVisible;
-(void)invalidateLayout;
-(int)scrollDirection;
-(UIEdgeInsets)insets;
-(void)setInsets:(UIEdgeInsets)arg1 ;
@end

