/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>

@class NSDictionary, UIView, UIGestureRecognizer, NSDate, UIDynamicAnimator, UIDynamicBehavior;

@interface GLDraggableView : UIView {

	char _haveAddedContentView;
	char _isChildDraggableView;
	char _ignoringGestureRecognizer;
	NSDictionary* _attributes;
	UIView* _contentView;
	UIView* _draggableAreaView;
	UIGestureRecognizer* _gestureRecognizer;
	/*^block*/id _completion;
	/*^block*/id _progress;
	NSDate* _beginAnimationDate;
	UIDynamicAnimator* _animator;
	UIDynamicBehavior* _addedBehavior;
	CGPoint _beginPoint;
	CGPoint _beginOrigin;
	CGPoint _differenceBetweenBeginOriginAndPoint;

}

@property (nonatomic,retain) UIView * contentView;                                      //@synthesize contentView=_contentView - In the implementation block
@property (nonatomic,retain) UIView * draggableAreaView;                                //@synthesize draggableAreaView=_draggableAreaView - In the implementation block
@property (nonatomic,retain) UIGestureRecognizer * gestureRecognizer;                   //@synthesize gestureRecognizer=_gestureRecognizer - In the implementation block
@property (nonatomic,copy) id completion;                                               //@synthesize completion=_completion - In the implementation block
@property (nonatomic,copy) id progress;                                                 //@synthesize progress=_progress - In the implementation block
@property (assign,nonatomic) char haveAddedContentView;                                 //@synthesize haveAddedContentView=_haveAddedContentView - In the implementation block
@property (assign,nonatomic) char isChildDraggableView;                                 //@synthesize isChildDraggableView=_isChildDraggableView - In the implementation block
@property (assign,nonatomic) CGPoint beginPoint;                                        //@synthesize beginPoint=_beginPoint - In the implementation block
@property (assign,nonatomic) CGPoint beginOrigin;                                       //@synthesize beginOrigin=_beginOrigin - In the implementation block
@property (assign,nonatomic) CGPoint differenceBetweenBeginOriginAndPoint;              //@synthesize differenceBetweenBeginOriginAndPoint=_differenceBetweenBeginOriginAndPoint - In the implementation block
@property (nonatomic,retain) NSDate * beginAnimationDate;                               //@synthesize beginAnimationDate=_beginAnimationDate - In the implementation block
@property (nonatomic,retain) UIDynamicAnimator * animator;                              //@synthesize animator=_animator - In the implementation block
@property (nonatomic,retain) UIDynamicBehavior * addedBehavior;                         //@synthesize addedBehavior=_addedBehavior - In the implementation block
@property (assign,nonatomic) char ignoringGestureRecognizer;                            //@synthesize ignoringGestureRecognizer=_ignoringGestureRecognizer - In the implementation block
@property (nonatomic,retain) NSDictionary * attributes;                                 //@synthesize attributes=_attributes - In the implementation block
-(void)ignoreGestureRecognizer;
-(id)initWithContentView:(id)arg1 draggableArea:(id)arg2 gestureRecognizer:(id)arg3 progressBlock:(/*^block*/id)arg4 completion:(/*^block*/id)arg5 ;
-(id)initWithContentView:(id)arg1 aimingForDraggableView:(id)arg2 angle:(float)arg3 delay:(double)arg4 completion:(/*^block*/id)arg5 ;
-(void)setIsChildDraggableView:(char)arg1 ;
-(void)setBeginPoint:(CGPoint)arg1 ;
-(void)setDraggableAreaView:(UIView *)arg1 ;
-(void)setHaveAddedContentView:(char)arg1 ;
-(CGPoint)beginOrigin;
-(CGPoint)beginPoint;
-(void)setDifferenceBetweenBeginOriginAndPoint:(CGPoint)arg1 ;
-(char)ignoringGestureRecognizer;
-(void)transformWithAngle:(float)arg1 ;
-(void)setAddedBehavior:(UIDynamicBehavior *)arg1 ;
-(void)gestureFired:(id)arg1 ;
-(UIView *)draggableAreaView;
-(void)setBeginOrigin:(CGPoint)arg1 ;
-(char)isChildDraggableView;
-(char)haveAddedContentView;
-(CGPoint)differenceBetweenBeginOriginAndPoint;
-(UIDynamicBehavior *)addedBehavior;
-(void)setIgnoringGestureRecognizer:(char)arg1 ;
-(NSDate *)beginAnimationDate;
-(void)setBeginAnimationDate:(NSDate *)arg1 ;
-(void)setContentView:(UIView *)arg1 ;
-(UIView *)contentView;
-(void)dealloc;
-(void)setGestureRecognizer:(UIGestureRecognizer *)arg1 ;
-(UIGestureRecognizer *)gestureRecognizer;
-(void)setProgress:(id)arg1 ;
-(id)completion;
-(void)setCompletion:(id)arg1 ;
-(void)setAnimator:(UIDynamicAnimator *)arg1 ;
-(NSDictionary *)attributes;
-(void)setAttributes:(NSDictionary *)arg1 ;
-(id)progress;
-(UIDynamicAnimator *)animator;
@end

