/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDate;

@interface GLFilePathWithModDate : NSObject {

	NSString* _path;
	NSDate* _modDate;

}

@property (nonatomic,retain) NSString * path;               //@synthesize path=_path - In the implementation block
@property (nonatomic,retain) NSDate * modDate;              //@synthesize modDate=_modDate - In the implementation block
-(NSDate *)modDate;
-(void)setModDate:(NSDate *)arg1 ;
-(NSString *)path;
-(void)setPath:(NSString *)arg1 ;
@end

