/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:10 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>

@class UITapGestureRecognizer, UIPanGestureRecognizer, GLGridView, UIButton, UIColor, UIView;

@interface GLGridViewCell : UIView {

	UITapGestureRecognizer* _tapRecognizer;
	UIPanGestureRecognizer* _panRecognizer;
	GLGridView* _parentGridView;
	UIButton* hiddenButton;
	UIColor* _selectionColor;
	UIColor* _unselectionColor;
	struct {
		unsigned isSelected : 1;
		unsigned isFlexibleWidth : 1;
		unsigned isWiggling : 1;
		unsigned wiggleState : 2;
	}  _flags;
	float _scale;
	char _allowsRearranging;
	UIView* _itemView;

}

@property (assign,nonatomic,__weak) GLGridView * parentGridView;              //@synthesize parentGridView=_parentGridView - In the implementation block
@property (nonatomic,retain) UIView * itemView;                               //@synthesize itemView=_itemView - In the implementation block
@property (assign,getter=isSelected,nonatomic) char selected; 
@property (assign,nonatomic) char isFlexibleWidth; 
@property (assign,getter=isWiggling,nonatomic) char wiggling; 
@property (assign,nonatomic) float scale;                                     //@synthesize scale=_scale - In the implementation block
@property (nonatomic,retain) UIColor * selectionColor;                        //@synthesize selectionColor=_selectionColor - In the implementation block
@property (nonatomic,retain) UIColor * unselectionColor;                      //@synthesize unselectionColor=_unselectionColor - In the implementation block
@property (assign,nonatomic) char allowsRearranging;                          //@synthesize allowsRearranging=_allowsRearranging - In the implementation block
-(void)setAllowsRearranging:(char)arg1 ;
-(void)setParentGridView:(GLGridView *)arg1 ;
-(char)isFlexibleWidth;
-(char)allowsRearranging;
-(void)panAction;
-(void)setUnselectionColor:(UIColor *)arg1 ;
-(void)doWiggleAnimation;
-(void)stopWiggleAnimation;
-(void)setIsFlexibleWidth:(char)arg1 ;
-(void)setWiggling:(char)arg1 ;
-(char)isWiggling;
-(GLGridView *)parentGridView;
-(UIColor *)unselectionColor;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setScale:(float)arg1 ;
-(float)scale;
-(void)animationDidStop:(id)arg1 finished:(id)arg2 context:(void*)arg3 ;
-(CGSize)intrinsicContentSize;
-(char)isSelected;
-(void)setSelected:(char)arg1 ;
-(UIColor *)selectionColor;
-(void)setSelectionColor:(UIColor *)arg1 ;
-(void)setItemView:(UIView *)arg1 ;
-(UIView *)itemView;
-(void)tapAction;
@end

