/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:10 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSError;

@interface GLiCloudNBNFolderRecoveryState : NSObject {

	char _recovered;
	char _needsDownload;
	NSError* _error;

}

@property (nonatomic,readonly) char recovered;                  //@synthesize recovered=_recovered - In the implementation block
@property (nonatomic,readonly) char needsDownload;              //@synthesize needsDownload=_needsDownload - In the implementation block
@property (nonatomic,readonly) NSError * error;                 //@synthesize error=_error - In the implementation block
+(id)stateWithRecovered:(char)arg1 needsDownload:(char)arg2 error:(id)arg3 ;
-(char)recovered;
-(id)initWithRecovered:(char)arg1 needsDownload:(char)arg2 error:(id)arg3 ;
-(char)needsDownload;
-(NSError *)error;
@end

