/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol GLiCloudEmergencyBehaviorDelegate;
@interface GLiCloudEmergencyBehavior : NSObject {

	char _lastKnownOnState;
	id<GLiCloudEmergencyBehaviorDelegate> _delegate;
	int _emergencyState;

}

@property (assign,nonatomic) char lastKnownOnState;                                              //@synthesize lastKnownOnState=_lastKnownOnState - In the implementation block
@property (assign) int emergencyState;                                                           //@synthesize emergencyState=_emergencyState - In the implementation block
@property (assign,nonatomic,__weak) id<GLiCloudEmergencyBehaviorDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)troubleshootingLink;
-(id)initWithLifetime:(id)arg1 ;
-(int)emergencyState;
-(void)enterEmergencyState;
-(void)_enterEmergencyStateBecauseOfMemory:(char)arg1 ;
-(char)lastKnownOnState;
-(void)setLastKnownOnState:(char)arg1 ;
-(void)_dispatchSetEmergencyState:(int)arg1 ;
-(void)iCloudConnectionEstablished;
-(void)setEmergencyState:(int)arg1 ;
-(void)_postStateChangeNotification;
-(void)setDelegate:(id<GLiCloudEmergencyBehaviorDelegate>)arg1 ;
-(id<GLiCloudEmergencyBehaviorDelegate>)delegate;
@end

