/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/GLIOFormatDelegate.h>

@protocol GLIOFormatDelegate <GLIOFormatDelegateProtocol,GLIOFormatConversionDelegateProtocol,GLIOFormatOptionViewDelegate,NSObject>
@required
+(id)previewImageForContentsAtURL:(id)arg1;
+(id)previewForContentsAtURL:(id)arg1;
+(char)isPDF;

@end


@class NSString;

@interface GLIOFormatDelegate : NSObject <GLIOFormatDelegate>

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)prerequisiteError;
+(id)associatedFileExtensions;
+(int)bindingStrengthToFileAtPath:(id)arg1 ;
+(id)uncoordinatedPackageNote:(id)arg1 destination:(id)arg2 operation:(id)arg3 fileCoordinator:(id)arg4 ;
+(int)legacyFormat;
+(id)desiredNameFromContentsPath:(id)arg1 ;
+(id)expectedAssociatedFileExtensions;
+(id)associatedUTIs;
+(char)supportsExport;
+(id)uncoordinatedUnpackageNoteAtURL:(id)arg1 toURL:(id)arg2 operation:(id)arg3 error:(id*)arg4 ;
+(id)uncoordinatedPackageNote:(id)arg1 destination:(id)arg2 operation:(id)arg3 ;
+(char)supportsConversion;
+(char)uncoordinatedUnpackageContents:(id)arg1 toNote:(id)arg2 operation:(id)arg3 ;
+(id)previewImageForContentsAtURL:(id)arg1 ;
+(id)hugeImage;
+(char)supportsExportPreview;
+(char)supportsImportToNote;
+(char)supportsPageRangeSelection;
+(id)uncoordinatedExportPreviewForNote:(id)arg1 operation:(id)arg2 ;
+(id)previewForContentsAtURL:(id)arg1 ;
+(char)isPDF;
+(char)supportsImport;
+(id)fileExtensionForExportWithOperation:(id)arg1 ;
+(id)mediumImage;
+(id)cachedBindingStrengthByPathExtension;
+(char)manuallyAssociatedWithFileExtension:(id)arg1 ;
+(int)bindingStrengthToUTIs:(id)arg1 ;
+(id)associatedFileExtensionsFromUTIs;
+(id)localizedDescription;
+(id)displayName;
+(id)plistName;
+(id)smallImage;
+(id)fileManager;
@end

