/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class _TtC10Notability9GLPDFLink, PDFFile;

@interface GLPDFLinkTarget : NSObject {

	_TtC10Notability9GLPDFLink* _link;
	PDFFile* _pdfFile;
	CGRect _originalFrame;

}

@property (nonatomic,retain) _TtC10Notability9GLPDFLink * link;              //@synthesize link=_link - In the implementation block
@property (nonatomic,retain) PDFFile * pdfFile;                              //@synthesize pdfFile=_pdfFile - In the implementation block
@property (assign,nonatomic) CGRect originalFrame;                           //@synthesize originalFrame=_originalFrame - In the implementation block
-(void)setPdfFile:(PDFFile *)arg1 ;
-(PDFFile *)pdfFile;
-(void)setOriginalFrame:(CGRect)arg1 ;
-(_TtC10Notability9GLPDFLink *)link;
-(void)setLink:(_TtC10Notability9GLPDFLink *)arg1 ;
-(CGRect)originalFrame;
@end

