/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>

@interface GLPoint : NSObject <NSCoding> {

	float x;
	float y;

}

@property (assign,nonatomic) float x; 
@property (assign,nonatomic) float y; 
+(id)pointWithCGPoint:(CGPoint)arg1 ;
-(CGPoint)CGPointValueScaled:(float)arg1 ;
-(id)initWithCGPoint:(CGPoint)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(CGPoint)CGPointValue;
-(float)x;
-(void)setX:(float)arg1 ;
-(float)y;
-(void)setY:(float)arg1 ;
@end

