/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:10 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIBarButtonItem.h>

@class NSString, UIImage, UIImageView;

@interface GLRearrangableToolbarItem : UIBarButtonItem {

	char _isFlexibleWidthSpacer;
	char _isFixedWidthSpacer;
	NSString* _iconKey;
	UIImage* _icon;
	UIImageView* _iconView;

}

@property (retain) UIImageView * iconView;                            //@synthesize iconView=_iconView - In the implementation block
@property (nonatomic,retain) UIImage * icon;                          //@synthesize icon=_icon - In the implementation block
@property (nonatomic,retain) NSString * iconKey;                      //@synthesize iconKey=_iconKey - In the implementation block
@property (assign,nonatomic) char isFlexibleWidthSpacer; 
@property (assign,nonatomic) char isFixedWidthSpacer;                 //@synthesize isFixedWidthSpacer=_isFixedWidthSpacer - In the implementation block
-(void)setIconKey:(NSString *)arg1 ;
-(id)initWithPaddedCustomView:(id)arg1 ;
-(void)setIsFlexibleWidthSpacer:(char)arg1 ;
-(char)isFlexibleWidthSpacer;
-(NSString *)iconKey;
-(char)isFixedWidthSpacer;
-(void)setIsFixedWidthSpacer:(char)arg1 ;
-(id)init;
-(void)setIcon:(UIImage *)arg1 ;
-(UIImage *)icon;
-(UIImageView *)iconView;
-(void)setIconView:(UIImageView *)arg1 ;
@end

