/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/NBButton.h>

@interface GLSegmentedControlButton : NBButton {

	float _currentScale;
	float _selectedStateScale;
	double _animationDuration;

}

@property (assign,nonatomic) float selectedStateScale;              //@synthesize selectedStateScale=_selectedStateScale - In the implementation block
@property (assign,nonatomic) double animationDuration;              //@synthesize animationDuration=_animationDuration - In the implementation block
+(id)buttonWithType:(int)arg1 ;
-(void)setSelectedStateScale:(float)arg1 ;
-(void)setCurrentScale:(float)arg1 ;
-(float)selectedStateScale;
-(void)setAnimationDuration:(double)arg1 ;
-(void)tintColorDidChange;
-(void)setImage:(id)arg1 forState:(unsigned)arg2 ;
-(void)setSelected:(char)arg1 ;
-(double)animationDuration;
-(void)_updateBackgroundColor;
@end

