/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIViewController.h>

@class GLCircularProgressView, NILabel, NSArray;

@interface GLSyncProgressViewController : UIViewController {

	char fadingAway;
	GLCircularProgressView* _transferProgressView;
	NILabel* _transferLabel;
	NSArray* _observers;
	CGSize _size;

}

@property (nonatomic,retain) GLCircularProgressView * transferProgressView;              //@synthesize transferProgressView=_transferProgressView - In the implementation block
@property (nonatomic,retain) NILabel * transferLabel;                                    //@synthesize transferLabel=_transferLabel - In the implementation block
@property (assign,nonatomic) CGSize size;                                                //@synthesize size=_size - In the implementation block
@property (nonatomic,retain) NSArray * observers;                                        //@synthesize observers=_observers - In the implementation block
-(void)syncNotNeeded;
-(void)syncCompleted;
-(void)syncStarted;
-(void)syncStopped;
-(void)syncCancelled;
-(void)handleTransferProgressNotification:(id)arg1 ;
-(void)setTransferProgressView:(GLCircularProgressView *)arg1 ;
-(GLCircularProgressView *)transferProgressView;
-(void)setTransferLabel:(NILabel *)arg1 ;
-(NILabel *)transferLabel;
-(void)setTransferProgress:(id)arg1 ;
-(void)setTransferMessage:(id)arg1 withFade:(char)arg2 ;
-(void)transferMessageFadeCompleted:(char)arg1 ;
-(CGSize)size;
-(void)dealloc;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)setSize:(CGSize)arg1 ;
-(void)viewDidLoad;
-(void)setObservers:(NSArray *)arg1 ;
-(NSArray *)observers;
@end

