/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class NSMutableDictionary;

@interface GLThreadsafeMutableDictionary : NSObject {

	opaque_pthread_rwlock_t lock;
	NSMutableDictionary* _backingDictionary;

}

@property (nonatomic,readonly) NSMutableDictionary * backingDictionary;              //@synthesize backingDictionary=_backingDictionary - In the implementation block
-(void)_acquireWriteLock;
-(void)_relinquishLock;
-(void)_acquireReadLock;
-(id)init;
-(void)dealloc;
-(unsigned)count;
-(id)objectForKey:(id)arg1 ;
-(void)removeObjectForKey:(id)arg1 ;
-(void)setObject:(id)arg1 forKey:(id)arg2 ;
-(NSMutableDictionary *)backingDictionary;
@end

