/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIButton.h>

@protocol GLUndoRedoButtonDelegate;
@class UIButton, UILongPressGestureRecognizer, NSUndoManager, UIBarButtonItem, UIAlertController, GLPopoverController;

@interface GLUndoRedoButton : UIButton {

	UIButton* iPhonePopoverUndoButton;
	UIButton* iPhonePopoverRedoButton;
	UILongPressGestureRecognizer* redoGestureRecognizer;
	char shouldShowTip;
	char _shouldShowActionSheetAfterAction;
	NSUndoManager* undoManager;
	UIBarButtonItem* presentationBarItem;
	id<GLUndoRedoButtonDelegate> _delegate;
	UIAlertController* _visibleAlertController;
	GLPopoverController* _visiblePopoverController;

}

@property (nonatomic,retain) UIAlertController * visibleAlertController;                  //@synthesize visibleAlertController=_visibleAlertController - In the implementation block
@property (nonatomic,retain) GLPopoverController * visiblePopoverController;              //@synthesize visiblePopoverController=_visiblePopoverController - In the implementation block
@property (assign,nonatomic) char shouldShowActionSheetAfterAction;                       //@synthesize shouldShowActionSheetAfterAction=_shouldShowActionSheetAfterAction - In the implementation block
@property (assign,nonatomic,__weak) UIBarButtonItem * presentationBarItem; 
@property (nonatomic,retain) NSUndoManager * undoManager; 
@property (assign,nonatomic,__weak) id<GLUndoRedoButtonDelegate> delegate;                //@synthesize delegate=_delegate - In the implementation block
-(void)willEnterBackground:(id)arg1 ;
-(void)dismissActionSheetAnimated:(char)arg1 ;
-(void)setVisiblePopoverController:(GLPopoverController *)arg1 ;
-(GLPopoverController *)visiblePopoverController;
-(void)setVisibleAlertController:(UIAlertController *)arg1 ;
-(void)teardownPopoversActionSheetsAndAlerts;
-(void)updateEnabledState;
-(void)handleUndoManagerChangeNotification;
-(UIAlertController *)visibleAlertController;
-(void)actionFromAlertControllerShouldUndo:(char)arg1 ;
-(UIBarButtonItem *)presentationBarItem;
-(void)showAlertCanUndo:(char)arg1 canRedo:(char)arg2 ;
-(void)showRedoActionSheet;
-(void)setShouldShowActionSheetAfterAction:(char)arg1 ;
-(void)showTipSheet;
-(char)shouldShowActionSheetAfterAction;
-(void)setPresentationBarItem:(UIBarButtonItem *)arg1 ;
-(id)init;
-(void)setDelegate:(id<GLUndoRedoButtonDelegate>)arg1 ;
-(void)dealloc;
-(void)didMoveToWindow;
-(id<GLUndoRedoButtonDelegate>)delegate;
-(void)undo;
-(void)redo;
-(NSUndoManager *)undoManager;
-(void)longPressAction;
-(void)setUndoManager:(NSUndoManager *)arg1 ;
@end

