/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface GLUserActivityCompatibility : NSObject
+(void)work:(/*^block*/id)arg1 ;
+(id)expression:(/*^block*/id)arg1 ;
+(id)preconfiguredNotabilityActivity;
+(void)configureNotabilityActivity:(id)arg1 ;
+(char)userActivitySupported;
+(char)coreSpotlightSupported;
+(char)handoffSupportedAndEnabled;
+(char)desireUserActivityUse;
@end

