/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol HandwritingObjectCurveBuilderDataAcceptor <NSObject>
@required
-(void)curveBuilder:(id)arg1 didChangeUpdateEstimateForCurveUnderConstruction:(id)arg2;
-(void)curveBuilder:(id)arg1 didFinalizePortionsOfCurveUnderConstruction:(id)arg2;
-(void)curveBuilderDidBeginCurve:(id)arg1;
-(void)curveBuilderDidCancel:(id)arg1;
-(void)curveBuilder:(id)arg1 didCompleteCurveWithResults:(id)arg2;

@end

