/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <Notability/HandwritingObjectCurveBuilderDataAcceptor.h>

@protocol HandwritingMediaObjectAssociationDelegate;
@class InkedSpatialHash, NSMutableArray, NSMutableDictionary, NSDate, NBDisplayLinkWrapper, InkCurve, NBCPEventManager, _TtC10Notability10PenManager, SelectionManager, NSUndoManager, NBCPPlayer, HandwritingObjectCurveBuilder, NSMutableSet, NSString;

@interface HandwritingObject : NSObject <NSCoding, HandwritingObjectCurveBuilderDataAcceptor> {

	InkedSpatialHash* spatialHash;
	CGRect boundingRect;
	NSMutableArray* curvesMarkedForDeletion;
	opaque_pthread_rwlock_t drawingLock;
	NSMutableDictionary* eventDictionary;
	char isPlaying;
	char isPaused;
	int currentSegmentIndex;
	float currentCurveDuration;
	NSDate* currentCurvePlaybackStartDate;
	NBDisplayLinkWrapper* displayLink;
	InkCurve* _currentPlaybackCurve;
	NBCPEventManager* _contentPlaybackEventManager;
	_TtC10Notability10PenManager* _penManager;
	id<HandwritingMediaObjectAssociationDelegate> _mediaObjectAssociationDelegate;
	SelectionManager* _selectionManager;
	NSUndoManager* _undoManager;
	NBCPPlayer* _contentPlaybackPlayer;
	HandwritingObjectCurveBuilder* _curveBuilder;
	NSMutableSet* _dragMoveCurves;
	NSMutableSet* _dragCopyCurves;
	double _currentCurveStartTime;

}

@property (nonatomic,retain) InkedSpatialHash * spatialHash; 
@property (assign) double currentCurveStartTime;                                                                               //@synthesize currentCurveStartTime=_currentCurveStartTime - In the implementation block
@property (__weak) HandwritingObjectCurveBuilder * curveBuilder;                                                               //@synthesize curveBuilder=_curveBuilder - In the implementation block
@property (nonatomic,retain) NSMutableSet * dragMoveCurves;                                                                    //@synthesize dragMoveCurves=_dragMoveCurves - In the implementation block
@property (nonatomic,retain) NSMutableSet * dragCopyCurves;                                                                    //@synthesize dragCopyCurves=_dragCopyCurves - In the implementation block
@property (assign,nonatomic,__weak) id<HandwritingMediaObjectAssociationDelegate> mediaObjectAssociationDelegate;              //@synthesize mediaObjectAssociationDelegate=_mediaObjectAssociationDelegate - In the implementation block
@property (assign,nonatomic,__weak) _TtC10Notability10PenManager * penManager; 
@property (nonatomic,retain) SelectionManager * selectionManager;                                                              //@synthesize selectionManager=_selectionManager - In the implementation block
@property (nonatomic,retain) NSUndoManager * undoManager;                                                                      //@synthesize undoManager=_undoManager - In the implementation block
@property (assign,nonatomic,__weak) NBCPEventManager * contentPlaybackEventManager;                                            //@synthesize contentPlaybackEventManager=_contentPlaybackEventManager - In the implementation block
@property (nonatomic,retain) NBCPPlayer * contentPlaybackPlayer;                                                               //@synthesize contentPlaybackPlayer=_contentPlaybackPlayer - In the implementation block
@property (getter=isEmpty,nonatomic,readonly) char empty; 
@property (readonly) unsigned numberOfStrokes; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)setDrawingParameters:(id)arg1 ;
+(id)keyPathsForValuesAffectingEmpty;
-(void)setContentPlaybackPlayer:(NBCPPlayer *)arg1 ;
-(void)setPenManager:(_TtC10Notability10PenManager *)arg1 ;
-(_TtC10Notability10PenManager *)penManager;
-(void)drawRect:(CGRect)arg1 inContext:(id)arg2 renderFlags:(unsigned)arg3 ;
-(void)unloadPathsInDocumentContentRect:(CGRect)arg1 ;
-(NBCPEventManager *)contentPlaybackEventManager;
-(char)rectIsEmpty:(CGRect)arg1 ;
-(void)setCurrentSegmentIndex:(int)arg1 ;
-(void)setCurrentCurvePlaybackStartDate:(id)arg1 ;
-(NBCPPlayer *)contentPlaybackPlayer;
-(id)currentPlaybackCurve;
-(void)setCurrentPlaybackCurve:(id)arg1 ;
-(void)stepPlaybackOneStep;
-(int)currentSegmentIndex;
-(id)currentCurvePlaybackStartDate;
-(float)currentCurveDuration;
-(void)setCurveEvent:(id)arg1 forCurve:(id)arg2 registerUndo:(char)arg3 ;
-(void)postModifiedNotificationWithStrokesAndRegisterUndo:(id)arg1 ;
-(char)curveIsMarkedAsUnplayed:(id)arg1 ;
-(void)unmapHandwritingObjectEvent:(id)arg1 registerUndo:(char)arg2 ;
-(id)eventForID:(unsigned)arg1 ;
-(void)setCurrentCurveDuration:(float)arg1 ;
-(void)mapHandwritingObjectEvent:(id)arg1 registerUndo:(char)arg2 ;
-(void)initForPlayback;
-(void)cleanupForPlayback;
-(void)handleEventsPermanentlyDeletedNotification:(id)arg1 ;
-(void)handlePlaybackEventNotification:(id)arg1 ;
-(void)initEventDataFromSpatialHash;
-(void)prepareForClosing;
-(void)curveBuilder:(id)arg1 didChangeUpdateEstimateForCurveUnderConstruction:(id)arg2 ;
-(void)curveBuilder:(id)arg1 didFinalizePortionsOfCurveUnderConstruction:(id)arg2 ;
-(id<HandwritingMediaObjectAssociationDelegate>)mediaObjectAssociationDelegate;
-(void)notifySetSelection;
-(void)notifyClearedSelection;
-(void)notifyBeginTransform;
-(void)notifyChangedTransform;
-(void)notifyCancelTransform;
-(void)notifyEndTransformWithCurves:(id)arg1 wasTranslatingForMediaObject:(char)arg2 ;
-(void)notifyDraggingChanged;
-(void)shiftEverythingBelow:(float)arg1 amount:(float)arg2 ;
-(void)addStrokesFromPageContentDictionaries:(id)arg1 shiftedByOffset:(CGPoint)arg2 ;
-(void)pasteStrokes:(id)arg1 selectionRepresentation:(id)arg2 atPoint:(CGPoint)arg3 ;
-(id)clearStrokesInRect:(CGRect)arg1 ;
-(id)strokesInRect:(CGRect)arg1 ;
-(id)removeScaleFactorFromStrokes:(id)arg1 ;
-(void)setContentPlaybackEventManager:(NBCPEventManager *)arg1 ;
-(void)cutStrokes:(id)arg1 withPasteboard:(id)arg2 ;
-(id)pasteboardItemsForStrokes:(id)arg1 selectionRepresentation:(id)arg2 rescale:(char)arg3 ;
-(void)deleteStrokes:(id)arg1 ;
-(id)setWidth:(float)arg1 forStrokes:(id)arg2 ;
-(id)setColor:(id)arg1 forStrokes:(id)arg2 ;
-(id)strokesInPath:(CGPathRef)arg1 ;
-(id)transformStrokes:(id)arg1 withAffineTransform:(CGAffineTransform)arg2 notifyAddRemove:(char)arg3 ;
-(void)updateForChangeInDraggableWithCurves:(id)arg1 ;
-(void)legacyMergeStrokes:(id)arg1 ;
-(void)setMediaObjectAssociationDelegate:(id<HandwritingMediaObjectAssociationDelegate>)arg1 ;
-(id)allStrokes;
-(void)addStrokes:(id)arg1 shiftedByOffset:(CGPoint)arg2 ;
-(void)curveBuilderDidBeginCurve:(id)arg1 ;
-(void)curveBuilderDidCancel:(id)arg1 ;
-(void)curveBuilder:(id)arg1 didCompleteCurveWithResults:(id)arg2 ;
-(HandwritingObjectCurveBuilder *)curveBuilder;
-(void)setCurveBuilder:(HandwritingObjectCurveBuilder *)arg1 ;
-(void)setCurrentCurveStartTime:(double)arg1 ;
-(double)currentCurveStartTime;
-(void)commitStrokes:(id)arg1 shouldDelete:(char)arg2 fromStrokeCompletion:(char)arg3 ;
-(id)handwritingObjectModifiedUserInfoForOldCurves:(id)arg1 newCurves:(id)arg2 ;
-(void)checkBoundingRectChangedAndNotify:(char)arg1 ;
-(void)unloadPathsForCurves:(id)arg1 ;
-(NSMutableSet *)dragMoveCurves;
-(NSMutableSet *)dragCopyCurves;
-(id)handwritingObjectModifiedUserInfoForCurves:(id)arg1 ;
-(void)checkBoundingRectChangedAndNotify;
-(id)transformStrokes:(id)arg1 withAffineTransform:(CGAffineTransform)arg2 notifyBounds:(char)arg3 ;
-(void)removeStrokes:(id)arg1 registerUndo:(char)arg2 ;
-(void)internalAddHelper:(id)arg1 translation:(CGPoint)arg2 zShift:(int)arg3 registerUndo:(char)arg4 ;
-(void)translateStrokes:(id)arg1 byAmount:(CGPoint)arg2 registerUndo:(char)arg3 ;
-(void)shiftStrokesZ:(id)arg1 byAmount:(int)arg2 registerUndo:(char)arg3 ;
-(void)addStrokes:(id)arg1 registerUndo:(char)arg2 ;
-(id)transformStrokes:(id)arg1 withAffineTransform:(CGAffineTransform)arg2 notifyBounds:(char)arg3 notifyAddRemove:(char)arg4 ;
-(id)strokesInRect:(CGRect)arg1 scale:(char)arg2 ;
-(void)addCurvesWhichIntersectCurve:(id)arg1 toArray:(id)arg2 ;
-(void)deleteStrokes:(id)arg1 registerUndo:(char)arg2 ;
-(void)putStrokes:(id)arg1 onPasteboard:(id)arg2 selectionRepresentation:(id)arg3 ;
-(id)setWidths:(id)arg1 forStrokes:(id)arg2 ;
-(id)transformStrokes:(id)arg1 withAffineTransform:(CGAffineTransform)arg2 ;
-(void)copyStrokes:(id)arg1 withPasteboard:(id)arg2 ;
-(InkedSpatialHash *)spatialHash;
-(void)setSpatialHash:(InkedSpatialHash *)arg1 ;
-(void)setDragMoveCurves:(NSMutableSet *)arg1 ;
-(void)setDragCopyCurves:(NSMutableSet *)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(NSUndoManager *)undoManager;
-(char)isEmpty;
-(void)setDisplayLink:(id)arg1 ;
-(id)displayLink;
-(unsigned)numberOfStrokes;
-(char)commonInit;
-(CGRect)boundingRect;
-(void)setUndoManager:(NSUndoManager *)arg1 ;
-(void)memoryWarning:(id)arg1 ;
-(SelectionManager *)selectionManager;
-(void)stopPlayback;
-(void)startPlayback;
-(id)eventManager;
-(void)handleDisplayLink:(id)arg1 ;
-(void)setSelectionManager:(SelectionManager *)arg1 ;
@end

