/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:10 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>
#import <Notability/SelectionUIObjectTextSystemDelegate.h>
#import <Notability/ProformancePaneViewControllerPaneBehaviorDelegate.h>
#import <Notability/ToggleSelectionColorPaletteInteractionTarget.h>

@protocol HandwritingZoomViewDelegate;
@class RichMediaDocument, NSTimer, UIView, _TtC10Notability10PenManager, SelectionManager, NBCPPlayer, NBThumbnailCache, ProformancePaneViewController, NSString;

@interface HandwritingZoomView : UIView <SelectionUIObjectTextSystemDelegate, ProformancePaneViewControllerPaneBehaviorDelegate, ToggleSelectionColorPaletteInteractionTarget> {

	RichMediaDocument* document;
	CGRect sourceRect;
	float farthestDrawingPointSinceLastAdvance;
	char hasEnteredAutoAdvanceRegion;
	NSTimer* autoAdvanceTimer;
	id<HandwritingZoomViewDelegate> delegate;
	char isDrawing;
	UIView* mainView;
	float scaleFactor;
	float animatingScale;
	char isWritingLTR;
	char isAdvancing;
	float autoAdvanceOffset;
	_TtC10Notability10PenManager* _penManager;
	SelectionManager* _selectionManager;
	NBCPPlayer* _contentPlaybackPlayer;
	NBThumbnailCache* _thumbnailCache;
	ProformancePaneViewController* _paneViewController;

}

@property (nonatomic,retain) ProformancePaneViewController * paneViewController;              //@synthesize paneViewController=_paneViewController - In the implementation block
@property (assign) float scaleFactor; 
@property (assign,nonatomic,__weak) RichMediaDocument * document; 
@property (assign,nonatomic) CGRect sourceRect; 
@property (assign,nonatomic,__weak) id<HandwritingZoomViewDelegate> delegate; 
@property (assign,nonatomic) char isWritingLTR; 
@property (assign,nonatomic) float autoAdvanceOffset; 
@property (assign,nonatomic) char isAdvancing; 
@property (nonatomic,readonly) float farthestDrawingPointSinceLastAdvance; 
@property (nonatomic,retain) _TtC10Notability10PenManager * penManager;                       //@synthesize penManager=_penManager - In the implementation block
@property (nonatomic,retain) SelectionManager * selectionManager;                             //@synthesize selectionManager=_selectionManager - In the implementation block
@property (nonatomic,retain) NBCPPlayer * contentPlaybackPlayer;                              //@synthesize contentPlaybackPlayer=_contentPlaybackPlayer - In the implementation block
@property (nonatomic,retain) NBThumbnailCache * thumbnailCache;                               //@synthesize thumbnailCache=_thumbnailCache - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setContentPlaybackPlayer:(NBCPPlayer *)arg1 ;
-(void)setPenManager:(_TtC10Notability10PenManager *)arg1 ;
-(_TtC10Notability10PenManager *)penManager;
-(int)maxBackgroundPanes;
-(char)ignoreUpdatePanes;
-(CGSize)hysterisisInsetSizeForScale:(float)arg1 ;
-(CGSize)prefetchInsetSizeForScale:(float)arg1 ;
-(char)selectionUIObject:(id)arg1 shouldRespondToGestureRecognizer:(id)arg2 ;
-(void)setDocumentNeedsDisplay:(char)arg1 ;
-(void)toggleSelectionColorPalette;
-(NBCPPlayer *)contentPlaybackPlayer;
-(void)selectionUIObject:(id)arg1 textSystemInsertTextBlockInRect:(CGRect)arg2 withText:(id)arg3 ;
-(void)setMainViewTransform;
-(void)setScaleFactor:(float)arg1 isGestureActive:(char)arg2 ;
-(id)applePencilTouchFromSet:(id)arg1 ;
-(char)acceptTouchesForAutoAdvance:(id)arg1 ;
-(void)trackTouchesInAutoAdvanceRegion:(id)arg1 ;
-(void)autoAdvanceTimerAction;
-(void)mediaObjectShouldRedraw:(id)arg1 ;
-(int)maxOffscreenBackgroundPanes;
-(void)resetAdvanceState;
-(char)isWritingLTR;
-(void)setIsWritingLTR:(char)arg1 ;
-(float)autoAdvanceOffset;
-(void)setAutoAdvanceOffset:(float)arg1 ;
-(float)farthestDrawingPointSinceLastAdvance;
-(char)isAdvancing;
-(void)setIsAdvancing:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<HandwritingZoomViewDelegate>)arg1 ;
-(void)dealloc;
-(id<HandwritingZoomViewDelegate>)delegate;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(CGRect)sourceRect;
-(void)setSourceRect:(CGRect)arg1 ;
-(void)touchesEstimatedPropertiesUpdated:(id)arg1 ;
-(void)teardown;
-(float)scaleFactor;
-(RichMediaDocument *)document;
-(void)setScaleFactor:(float)arg1 ;
-(void)setDocument:(RichMediaDocument *)arg1 ;
-(NBThumbnailCache *)thumbnailCache;
-(void)setThumbnailCache:(NBThumbnailCache *)arg1 ;
-(void)startup;
-(SelectionManager *)selectionManager;
-(void)setPaneViewController:(ProformancePaneViewController *)arg1 ;
-(ProformancePaneViewController *)paneViewController;
-(void)setSelectionManager:(SelectionManager *)arg1 ;
@end

