/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/RectObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class UIColor, HandwritingObjectEvent;

@interface InkCurve : NSObject <RectObject, NSCopying> {

	CGPathRef path;
	float baseWidth;
	UIColor* color;
	int zOrder;
	int style;
	char isMarkedForDeletion;
	SCD_Struct_In35* internalDataRep;
	HandwritingObjectEvent* _startEvent;

}

@property (readonly) CGRect rect; 
@property (assign) char isMarkedForDeletion; 
@property (assign,nonatomic) float baseWidth; 
@property (nonatomic,retain) UIColor * color; 
@property (assign) int zOrder; 
@property (readonly) CGPathRef path; 
@property (assign) int style; 
@property (retain) HandwritingObjectEvent * startEvent;              //@synthesize startEvent=_startEvent - In the implementation block
+(id)curveForSelectionRect:(CGRect)arg1 ;
-(void)buildPath;
-(void)drawWithContext:(id)arg1 renderFlags:(unsigned)arg2 ;
-(id)initWithP0:(CGPoint)arg1 p1:(CGPoint)arg2 p2:(CGPoint)arg3 p3:(CGPoint)arg4 baseWidth:(float)arg5 fractionalWidth1:(float)arg6 fractionalWidth2:(float)arg7 color:(id)arg8 zOrder:(int)arg9 isForSelection:(char)arg10 ;
-(CGPoint)getPoint:(unsigned)arg1 ;
-(unsigned)numSegments;
-(id)curveFromSegmentAtIndex:(int)arg1 ;
-(HandwritingObjectEvent *)startEvent;
-(void)setStartEvent:(HandwritingObjectEvent *)arg1 ;
-(id)initWithPoints:(CGPoint*)arg1 numPoints:(unsigned)arg2 baseWidth:(float)arg3 fractionalWidths:(float*)arg4 color:(id)arg5 zOrder:(int)arg6 ;
-(unsigned)numFractionalWidths;
-(void)enumeratePointsWithBlock:(/*^block*/id)arg1 ;
-(void)enumerateFractionalWidthsWithBlock:(/*^block*/id)arg1 ;
-(float)baseWidth;
-(id)initWithPoint:(CGPoint)arg1 baseWidth:(float)arg2 color:(id)arg3 zOrder:(int)arg4 isForSelection:(char)arg5 ;
-(void)setIsMarkedForDeletion:(char)arg1 ;
-(float)getFractionalWidth:(unsigned)arg1 ;
-(void)buildPathFixedWidth;
-(void)buildPathVariableWidthMergeSegments;
-(id)initWithInternalDataRep:(SCD_Struct_In36*)arg1 baseWidth:(float)arg2 color:(id)arg3 zOrder:(int)arg4 isForSelection:(char)arg5 ;
-(id)initWithPoints:(CGPoint*)arg1 numPoints:(unsigned)arg2 baseWidth:(float)arg3 fractionalWidths:(float*)arg4 color:(id)arg5 zOrder:(int)arg6 isForSelection:(char)arg7 ;
-(void)drawWithContext:(id)arg1 renderFlags:(unsigned)arg2 mode:(int)arg3 ;
-(void)translateByAmount:(CGPoint)arg1 ;
-(void)unloadPath;
-(char)needsBuildPath;
-(id)initWithCurves:(id)arg1 baseWidth:(float)arg2 color:(id)arg3 zOrder:(int)arg4 isForSelection:(char)arg5 ;
-(char)intersectsInkCurve:(id)arg1 ;
-(char)intersectsPoint:(CGPoint)arg1 distance:(float*)arg2 ;
-(id)shiftedCopy:(CGPoint)arg1 ;
-(void)setBaseWidth:(float)arg1 ;
-(id)copyWithConstantWidth:(float)arg1 ;
-(void)dealloc;
-(id)description;
-(CGPathRef)path;
-(int)style;
-(id)copyWithZone:(NSZone*)arg1 ;
-(UIColor *)color;
-(void)setColor:(UIColor *)arg1 ;
-(void)setStyle:(int)arg1 ;
-(CGRect)rect;
-(char)validate;
-(void)setZOrder:(int)arg1 ;
-(char)isMarkedForDeletion;
-(int)zOrder;
-(unsigned)numPoints;
-(void)transform:(CGAffineTransform)arg1 ;
-(char)isLine;
@end

