/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIButton.h>
#import <Notability/GLViewWithHoverImageProtocol.h>

@protocol InsertMediaPopoverCellDelegate;
@class UIImageView, NILabel, NSString;

@interface InsertMediaPopoverCellView : UIButton <GLViewWithHoverImageProtocol> {

	UIImageView* imageView;
	NILabel* label;
	UIImageView* mediaHoverView;
	CGSize sizeToReturnToAfterHover;
	SEL selector;
	int mediaType;
	id<InsertMediaPopoverCellDelegate> delegate;

}

@property (assign,nonatomic) SEL selector; 
@property (assign,nonatomic) int mediaType; 
@property (assign,nonatomic,__weak) id<InsertMediaPopoverCellDelegate> delegate; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setShowHoverImage:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setImage:(id)arg1 ;
-(void)setDelegate:(id<InsertMediaPopoverCellDelegate>)arg1 ;
-(void)dealloc;
-(id<InsertMediaPopoverCellDelegate>)delegate;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)setText:(id)arg1 ;
-(void)setSelector:(SEL)arg1 ;
-(SEL)selector;
-(id)label;
-(void)layoutLabel;
-(int)mediaType;
-(void)setMediaType:(int)arg1 ;
@end

