/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:09 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>
#import <Notability/LibraryNotesViewProtocol.h>
#import <Notability/GLUpdatingView.h>

@protocol LibraryNotesViewDelegateLibraryNotesViewThumbnailDraggingProtocol, LibraryControllerDelegate;
@class GLUpdatingViewContext, NSArray, NBSubject, NSString;

@interface LibraryNoteView : UIView <LibraryNotesViewProtocol, GLUpdatingView> {

	char editing;
	char clouding;
	char selectedAllSubjects;
	char movingWithoutSelection;
	char allowsDeletion;
	id<LibraryNotesViewDelegate><LibraryNotesViewThumbnailDraggingProtocol> _delegate;
	id<LibraryControllerDelegate> _controllerDelegate;
	GLUpdatingViewContext* _updatingViewContext;
	NSArray* _documents;
	NBSubject* _selectedSubject;
	int _iCloudEmergencyState;

}

@property (assign,nonatomic,__weak) id<LibraryNotesViewDelegate><LibraryNotesViewThumbnailDraggingProtocol> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) id<LibraryControllerDelegate> controllerDelegate;                                              //@synthesize controllerDelegate=_controllerDelegate - In the implementation block
@property (nonatomic,retain) GLUpdatingViewContext * updatingViewContext;                                                          //@synthesize updatingViewContext=_updatingViewContext - In the implementation block
@property (nonatomic,retain) NSArray * documents;                                                                                  //@synthesize documents=_documents - In the implementation block
@property (nonatomic,retain) NBSubject * selectedSubject;                                                                          //@synthesize selectedSubject=_selectedSubject - In the implementation block
@property (assign,nonatomic) char clouding; 
@property (assign) char selectedAllSubjects; 
@property (assign,nonatomic) char editing; 
@property (assign) char movingWithoutSelection; 
@property (assign) char allowsDeletion; 
@property (assign,nonatomic) int iCloudEmergencyState;                                                                             //@synthesize iCloudEmergencyState=_iCloudEmergencyState - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)redrawNotesAnimated:(char)arg1 ;
-(void)updatedSortState:(id)arg1 ;
-(NBSubject *)selectedSubject;
-(void)setSelectedSubject:(NBSubject *)arg1 ;
-(int)iCloudEmergencyState;
-(void)setICloudEmergencyState:(int)arg1 ;
-(char)clouding;
-(void)setClouding:(char)arg1 ;
-(void)setUpdatingViewContext:(GLUpdatingViewContext *)arg1 ;
-(GLUpdatingViewContext *)updatingViewContext;
-(void)updatedSortStyle:(int)arg1 ;
-(void)endCellsShowingSwipeToDeleteControlIfNeeded;
-(void)setNotes:(id)arg1 selected:(char)arg2 ;
-(id)updateAndReturnContextForNextUpdate:(id)arg1 ;
-(void)redrawNotes;
-(CGPoint)getOffset;
-(char)isEditingOrCellsEditing;
-(void)animateInsertionOfNotes:(id)arg1 ;
-(void)noteMoveCompleted:(char)arg1 ;
-(char)thumbnailFound:(id)arg1 forDocument:(id)arg2 ;
-(char)selectedAllSubjects;
-(void)setSelectedAllSubjects:(char)arg1 ;
-(char)movingWithoutSelection;
-(void)setMovingWithoutSelection:(char)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<LibraryNotesViewDelegate><LibraryNotesViewThumbnailDraggingProtocol>)arg1 ;
-(id<LibraryNotesViewDelegate><LibraryNotesViewThumbnailDraggingProtocol>)delegate;
-(void)setScrollEnabled:(char)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidAppear:(char)arg1 ;
-(char)editing;
-(void)setEditing:(char)arg1 ;
-(id)forwardingTargetForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)setOffset:(CGPoint)arg1 ;
-(id<LibraryControllerDelegate>)controllerDelegate;
-(void)setControllerDelegate:(id<LibraryControllerDelegate>)arg1 ;
-(char)allowsDeletion;
-(void)setAllowsDeletion:(char)arg1 ;
-(void)startObserving;
-(NSArray *)documents;
-(void)setDocuments:(NSArray *)arg1 ;
-(void)stopObserving;
@end

