/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NBColorCollectionViewControllerCustomizableColorSource <NBColorCollectionViewControllerColorSource>
@required
-(void)setColors:(id)arg1 atIndexRange:(NSRange)arg2;
-(void)setColor:(id)arg1 atIndex:(int)arg2;

@end

