/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:09 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UIPageViewControllerDataSource.h>
#import <UIKit/UIPageViewControllerDelegate.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <Notability/GLCollectionViewColorProviderDirectionDelegate.h>
#import <Notability/NBColorCollectionViewControllerDelegate.h>

@protocol NBColorPageViewControllerDelegate;
@class UIPageViewController, NSArray, UIPageControl, GLCollectionViewColorContentProvider, NSString;

@interface NBColorPageViewController : UIViewController <UIPageViewControllerDataSource, UIPageViewControllerDelegate, UIScrollViewDelegate, GLCollectionViewColorProviderDirectionDelegate, NBColorCollectionViewControllerDelegate> {

	char _isCustomizable;
	char _showPageControl;
	id<NBColorPageViewControllerDelegate> _colorDelegate;
	UIPageViewController* _pageViewController;
	id _targetContext;
	NSArray* _colorRangeValues;
	unsigned _currentPage;
	UIPageControl* _customPageControl;
	int _pageLayout;
	NSArray* _colorViewControllers;
	GLCollectionViewColorContentProvider* _lastSelectedColorProvider;

}

@property (nonatomic,retain) NSArray * colorRangeValues;                                                    //@synthesize colorRangeValues=_colorRangeValues - In the implementation block
@property (assign,nonatomic) unsigned currentPage;                                                          //@synthesize currentPage=_currentPage - In the implementation block
@property (nonatomic,retain) UIPageViewController * pageViewController;                                     //@synthesize pageViewController=_pageViewController - In the implementation block
@property (nonatomic,retain) UIPageControl * customPageControl;                                             //@synthesize customPageControl=_customPageControl - In the implementation block
@property (assign,nonatomic) int pageLayout;                                                                //@synthesize pageLayout=_pageLayout - In the implementation block
@property (assign,nonatomic) char showPageControl;                                                          //@synthesize showPageControl=_showPageControl - In the implementation block
@property (nonatomic,retain) NSArray * colorViewControllers;                                                //@synthesize colorViewControllers=_colorViewControllers - In the implementation block
@property (nonatomic,retain) GLCollectionViewColorContentProvider * lastSelectedColorProvider;              //@synthesize lastSelectedColorProvider=_lastSelectedColorProvider - In the implementation block
@property (assign,nonatomic,__weak) id<NBColorPageViewControllerDelegate> colorDelegate;                    //@synthesize colorDelegate=_colorDelegate - In the implementation block
@property (assign,nonatomic) char isCustomizable;                                                           //@synthesize isCustomizable=_isCustomizable - In the implementation block
@property (nonatomic,retain) id targetContext;                                                              //@synthesize targetContext=_targetContext - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(char)isCustomizable;
-(void)setIsCustomizable:(char)arg1 ;
-(void)colorProviderNavigateWithDirection:(int)arg1 ;
-(id)initWithType:(int)arg1 layout:(int)arg2 showPageControl:(char)arg3 isCustomizable:(char)arg4 callback:(/*^block*/id)arg5 ;
-(unsigned)colorsPerPage;
-(char)isCustomColorSection:(int)arg1 ;
-(NSArray *)colorViewControllers;
-(void)setTargetContext:(id)arg1 ;
-(void)jumpToColorViewController:(id)arg1 ;
-(void)jumpToPageNumber:(unsigned)arg1 ;
-(void)setCustomPageControl:(UIPageControl *)arg1 ;
-(char)showPageControl;
-(UIPageControl *)customPageControl;
-(unsigned)indexForVC:(id)arg1 ;
-(void)setLastSelectedColorProvider:(GLCollectionViewColorContentProvider *)arg1 ;
-(id<NBColorPageViewControllerDelegate>)colorDelegate;
-(void)presentViewController:(id)arg1 forColorCollectionViewController:(id)arg2 animated:(char)arg3 ;
-(void)dismissViewController:(id)arg1 forColorCollectionViewController:(id)arg2 animated:(char)arg3 ;
-(CGRect)frameForColorPickerPresentationInView:(id)arg1 ;
-(GLCollectionViewColorContentProvider *)lastSelectedColorProvider;
-(char)colorCollectionViewControllerIsFirst:(id)arg1 ;
-(char)colorCollectionViewControllerIsLast:(id)arg1 ;
-(void)colorCollectionViewController:(id)arg1 didSelectColorProvider:(id)arg2 ;
-(void)colorCollectionViewControllerWillAppear:(id)arg1 ;
-(char)colorCollectionViewController:(id)arg1 shouldSelectCellWithColorProvider:(id)arg2 withColor:(id)arg3 ;
-(void)presentColorCollectionViewController:(id)arg1 ;
-(void)dismissColorCollectionViewController:(id)arg1 ;
-(void)colorCollectionViewControllerRequestsPageScrollingEnabled:(char)arg1 ;
-(id)initWithType:(int)arg1 layout:(int)arg2 isCustomizable:(char)arg3 callback:(/*^block*/id)arg4 ;
-(void)setPageInsets:(UIEdgeInsets)arg1 ;
-(void)notifyDelegateOfPageChange:(unsigned)arg1 ;
-(void)setColorDelegate:(id<NBColorPageViewControllerDelegate>)arg1 ;
-(id)targetContext;
-(NSArray *)colorRangeValues;
-(void)setColorRangeValues:(NSArray *)arg1 ;
-(void)setShowPageControl:(char)arg1 ;
-(void)setColorViewControllers:(NSArray *)arg1 ;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(void)scrollViewDidEndScrollingAnimation:(id)arg1 ;
-(unsigned)numberOfColumns;
-(void)viewDidLoad;
-(void)setCurrentPage:(unsigned)arg1 ;
-(unsigned)currentPage;
-(CGSize)layoutSize;
-(unsigned)pageCount;
-(id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2 ;
-(id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2 ;
-(UIPageViewController *)pageViewController;
-(void)setPageViewController:(UIPageViewController *)arg1 ;
-(char)setSelectedColor:(id)arg1 ;
-(int)pageLayout;
-(void)setPageLayout:(int)arg1 ;
@end

