/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>

@protocol NBInputToolTrayDelegate;
@class _TtC10Notability10PenManager, NSArray, UIColor, UIImageView;

@interface NBInputToolTrayView : UIView {

	UIEdgeInsets trayGraphicInsets;
	float trayCornerRadius;
	int numColumns;
	int numRows;
	float buttonWidth;
	float buttonHeight;
	CGRect trayRect;
	CGRect bottomButtonRect;
	char _bottomViewHighlighted;
	int selectedButtonIndex;
	id<NBInputToolTrayDelegate> _delegate;
	_TtC10Notability10PenManager* _penManager;
	int _highlightedButtonIndex;
	NSArray* _iconViews;
	UIColor* _trayBackgroundColor;
	UIColor* _traySeparatorColor;
	UIColor* _buttonFillColor;
	UIImageView* _bottomView;

}

@property (assign,nonatomic) int highlightedButtonIndex;                               //@synthesize highlightedButtonIndex=_highlightedButtonIndex - In the implementation block
@property (nonatomic,retain) NSArray * iconViews;                                      //@synthesize iconViews=_iconViews - In the implementation block
@property (nonatomic,retain) UIColor * trayBackgroundColor;                            //@synthesize trayBackgroundColor=_trayBackgroundColor - In the implementation block
@property (nonatomic,retain) UIColor * traySeparatorColor;                             //@synthesize traySeparatorColor=_traySeparatorColor - In the implementation block
@property (nonatomic,retain) UIColor * buttonFillColor;                                //@synthesize buttonFillColor=_buttonFillColor - In the implementation block
@property (nonatomic,retain) UIImageView * bottomView;                                 //@synthesize bottomView=_bottomView - In the implementation block
@property (assign,nonatomic) char bottomViewHighlighted;                               //@synthesize bottomViewHighlighted=_bottomViewHighlighted - In the implementation block
@property (assign,nonatomic) int selectedButtonIndex; 
@property (assign,nonatomic,__weak) id<NBInputToolTrayDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) _TtC10Notability10PenManager * penManager;                //@synthesize penManager=_penManager - In the implementation block
-(void)setPenManager:(_TtC10Notability10PenManager *)arg1 ;
-(_TtC10Notability10PenManager *)penManager;
-(char)bottomViewHighlighted;
-(void)setTrayBackgroundColor:(UIColor *)arg1 ;
-(void)setTraySeparatorColor:(UIColor *)arg1 ;
-(void)setButtonFillColor:(UIColor *)arg1 ;
-(void)_updateIconViewTintColorsBySelectionAndHighlightStateWithPersonality:(id)arg1 ;
-(int)highlightedButtonIndex;
-(void)setBottomViewHighlighted:(char)arg1 ;
-(CGRect)buttonFrameForRow:(int)arg1 column:(int)arg2 ;
-(void)iterateIconsWithAction:(/*^block*/id)arg1 ;
-(UIColor *)trayBackgroundColor;
-(UIColor *)traySeparatorColor;
-(UIColor *)buttonFillColor;
-(int)buttonIndexForPoint:(CGPoint)arg1 ;
-(void)setHighlightedButtonIndex:(int)arg1 ;
-(void)takePhotoAction;
-(void)setSelectedButtonIndex:(int)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)arg1 ;
-(void)setDelegate:(id<NBInputToolTrayDelegate>)arg1 ;
-(id<NBInputToolTrayDelegate>)delegate;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)inputModeDidChange;
-(UIImageView *)bottomView;
-(void)setBottomView:(UIImageView *)arg1 ;
-(int)selectedButtonIndex;
-(void)setIconViews:(NSArray *)arg1 ;
-(NSArray *)iconViews;
@end

