/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIView, UIImageView;

@interface NBMacIntroiOSDeviceView : UIView {

	UIView* _thumbnailsLayoutGuide;
	UIImageView* _deviceFrame;
	UIImageView* _deviceInterface;
	UIView* _deviceScreen;

}

@property (nonatomic,readonly) UIImageView * deviceFrame;                   //@synthesize deviceFrame=_deviceFrame - In the implementation block
@property (nonatomic,readonly) UIImageView * deviceInterface;               //@synthesize deviceInterface=_deviceInterface - In the implementation block
@property (nonatomic,readonly) UIView * deviceScreen;                       //@synthesize deviceScreen=_deviceScreen - In the implementation block
@property (nonatomic,readonly) UIView * thumbnailsLayoutGuide;              //@synthesize thumbnailsLayoutGuide=_thumbnailsLayoutGuide - In the implementation block
-(UIView *)thumbnailsLayoutGuide;
-(UIImageView *)deviceInterface;
-(UIImageView *)deviceFrame;
-(UIView *)deviceScreen;
-(id)init;
-(void)setContentAlpha:(float)arg1 ;
@end

