/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/NIPromoModalViewController.h>

@class NBMacIntroiOSDeviceView, NBMacIntroLaptopView, NBMacIntroThumbnailsView, NSArray, UILabel;

@interface NBMacIntroViewController : NIPromoModalViewController {

	char _hasFinishedAnimation;
	char _useEnglishLayout;
	NBMacIntroiOSDeviceView* _iPadView;
	NBMacIntroLaptopView* _laptopView;
	NBMacIntroThumbnailsView* _thumbnailsView;
	NSArray* _macIntroConstraints;
	UILabel* _notabilityLabel;
	UILabel* _messageLabel;
	UILabel* _appStorePromptLabel;
	UILabel* _yourNotesLabel;
	NSArray* _thumbnailsViewConstraints;

}

@property (nonatomic,readonly) NBMacIntroiOSDeviceView * iPadView;                     //@synthesize iPadView=_iPadView - In the implementation block
@property (nonatomic,readonly) NBMacIntroLaptopView * laptopView;                      //@synthesize laptopView=_laptopView - In the implementation block
@property (nonatomic,readonly) NBMacIntroThumbnailsView * thumbnailsView;              //@synthesize thumbnailsView=_thumbnailsView - In the implementation block
@property (nonatomic,retain) NSArray * macIntroConstraints;                            //@synthesize macIntroConstraints=_macIntroConstraints - In the implementation block
@property (nonatomic,readonly) UILabel * notabilityLabel;                              //@synthesize notabilityLabel=_notabilityLabel - In the implementation block
@property (nonatomic,readonly) UILabel * messageLabel;                                 //@synthesize messageLabel=_messageLabel - In the implementation block
@property (nonatomic,readonly) UILabel * appStorePromptLabel;                          //@synthesize appStorePromptLabel=_appStorePromptLabel - In the implementation block
@property (nonatomic,readonly) UILabel * yourNotesLabel;                               //@synthesize yourNotesLabel=_yourNotesLabel - In the implementation block
@property (nonatomic,retain) NSArray * thumbnailsViewConstraints;                      //@synthesize thumbnailsViewConstraints=_thumbnailsViewConstraints - In the implementation block
@property (assign,nonatomic) char hasFinishedAnimation;                                //@synthesize hasFinishedAnimation=_hasFinishedAnimation - In the implementation block
@property (assign,nonatomic) char useEnglishLayout;                                    //@synthesize useEnglishLayout=_useEnglishLayout - In the implementation block
-(void)setThumbnailsViewConstraints:(NSArray *)arg1 ;
-(NBMacIntroThumbnailsView *)thumbnailsView;
-(NSArray *)thumbnailsViewConstraints;
-(char)dismissEnabled;
-(void)setUseEnglishLayout:(char)arg1 ;
-(void)setHasFinishedAnimation:(char)arg1 ;
-(char)useEnglishLayout;
-(void)setMacIntroConstraints:(NSArray *)arg1 ;
-(void)_startAnimationByFadingIniPadContent;
-(void)_continueIntroAnimationByFadingInYourNotesLabel;
-(void)_continueIntroAnimationByPoppingThumbnailsOffiPad;
-(void)_continueIntroAnimationAfteriPadFadeIn;
-(NBMacIntroiOSDeviceView *)iPadView;
-(void)_continueIntroAnimationAfterThumbnailSettling;
-(void)_continueIntroAnimationAfterMessageFadeIn;
-(void)_continueIntroAnimationAfterNotabilityLogoBump;
-(char)hasFinishedAnimation;
-(void)beginMacIntroAnimation;
-(NBMacIntroLaptopView *)laptopView;
-(NSArray *)macIntroConstraints;
-(UILabel *)notabilityLabel;
-(UILabel *)appStorePromptLabel;
-(UILabel *)yourNotesLabel;
-(void)loadView;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(UILabel *)messageLabel;
@end

