/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class UIView, NBMacIntroThumbnailsView, UIImageView, NSArray;

@interface NBMacIntroLaptopView : UIView {

	char _showingNotabilityLogo;
	UIView* _thumbnailsLayoutGuide;
	NBMacIntroThumbnailsView* _thumbnailsView;
	UIImageView* _laptopFrameView;
	UIImageView* _laptopInterface;
	UIView* _laptopScreen;
	UIImageView* _notabilityLogo;
	NSArray* _gl_constraints;
	NSArray* _thumbnailsViewConstraints;

}

@property (nonatomic,readonly) UIImageView * laptopFrameView;                        //@synthesize laptopFrameView=_laptopFrameView - In the implementation block
@property (nonatomic,readonly) UIImageView * laptopInterface;                        //@synthesize laptopInterface=_laptopInterface - In the implementation block
@property (nonatomic,readonly) UIView * laptopScreen;                                //@synthesize laptopScreen=_laptopScreen - In the implementation block
@property (nonatomic,readonly) UIImageView * notabilityLogo;                         //@synthesize notabilityLogo=_notabilityLogo - In the implementation block
@property (nonatomic,retain) NSArray * gl_constraints;                               //@synthesize gl_constraints=_gl_constraints - In the implementation block
@property (nonatomic,retain) NSArray * thumbnailsViewConstraints;                    //@synthesize thumbnailsViewConstraints=_thumbnailsViewConstraints - In the implementation block
@property (nonatomic,readonly) UIView * thumbnailsLayoutGuide;                       //@synthesize thumbnailsLayoutGuide=_thumbnailsLayoutGuide - In the implementation block
@property (assign,nonatomic) char showingNotabilityLogo;                             //@synthesize showingNotabilityLogo=_showingNotabilityLogo - In the implementation block
@property (nonatomic,retain) NBMacIntroThumbnailsView * thumbnailsView;              //@synthesize thumbnailsView=_thumbnailsView - In the implementation block
-(NSArray *)gl_constraints;
-(char)showingNotabilityLogo;
-(void)setGl_constraints:(NSArray *)arg1 ;
-(UIView *)thumbnailsLayoutGuide;
-(void)setThumbnailsViewConstraints:(NSArray *)arg1 ;
-(UIView *)laptopScreen;
-(void)setThumbnailsView:(NBMacIntroThumbnailsView *)arg1 ;
-(void)setShowingNotabilityLogo:(char)arg1 ;
-(NBMacIntroThumbnailsView *)thumbnailsView;
-(UIImageView *)laptopFrameView;
-(UIImageView *)laptopInterface;
-(UIImageView *)notabilityLogo;
-(NSArray *)thumbnailsViewConstraints;
-(id)init;
-(void)updateConstraints;
-(void)setContentAlpha:(float)arg1 ;
@end

