/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NBNoteDocument, GLMultiNoteViewState;

@interface NBMultiNoteListState : NSObject {

	NBNoteDocument* _leftDocument;
	NBNoteDocument* _rightDocument;
	GLMultiNoteViewState* _viewState;

}

@property (nonatomic,retain) NBNoteDocument * leftDocument;                 //@synthesize leftDocument=_leftDocument - In the implementation block
@property (nonatomic,retain) NBNoteDocument * rightDocument;                //@synthesize rightDocument=_rightDocument - In the implementation block
@property (nonatomic,retain) GLMultiNoteViewState * viewState;              //@synthesize viewState=_viewState - In the implementation block
-(NBNoteDocument *)leftDocument;
-(NBNoteDocument *)rightDocument;
-(void)setLeftDocument:(NBNoteDocument *)arg1 ;
-(void)setRightDocument:(NBNoteDocument *)arg1 ;
-(GLMultiNoteViewState *)viewState;
-(void)setViewState:(GLMultiNoteViewState *)arg1 ;
@end

