/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@interface NBNoteLayoutProperties : NSObject
+(id)sharedProperties;
-(float)devicePageWidthInDocumentPoints;
-(float)noteTitleHeightInDocumentPoints;
-(float)legacyPageWidthInDocumentPoints;
-(id)nativeLayoutDeviceString;
-(float)caretHeightScaleFactorForAutoZoom;
-(float)legacyMarginWidthInDocumentPoints;
-(CGSize)pageSizeInDocumentPointsForPageWidth:(float)arg1 marginWidth:(float)arg2 ;
-(float)marginToPageRatio;
-(UIEdgeInsets)pageInsetsInDocumentPointsForMarginWidth:(float)arg1 ;
-(float)deviceWidthInViewPoints;
-(float)presetDevicePageWidthInDocumentPoints;
-(CGSize)printSizeInInches;
-(UIEdgeInsets)printInsetsInInches;
-(float)pointsPerInchForPageWidth:(float)arg1 marginWidth:(float)arg2 ;
-(float)defaultPDFExportPageWidthInDocumentPoints;
-(CGSize)pageContentSizeInDocumentPointsForPageWidth:(float)arg1 marginWidth:(float)arg2 ;
-(CGSize)pagePrintSizeInDocumentPointsForPageWidth:(float)arg1 marginWidth:(float)arg2 ;
-(CGRect)pagePrintContentRectInDocumentPointsForPageWidth:(float)arg1 marginWidth:(float)arg2 ;
-(CGSize)screenSize;
@end

