/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NBNoteDocumentThumbnailMetadata : NSObject {

	float _rank;
	float _scale;
	float _absoluteScale;

}

@property (nonatomic,readonly) float rank;                       //@synthesize rank=_rank - In the implementation block
@property (nonatomic,readonly) float scale;                      //@synthesize scale=_scale - In the implementation block
@property (nonatomic,readonly) float absoluteScale;              //@synthesize absoluteScale=_absoluteScale - In the implementation block
+(id)thumbnailMetadataWithRank:(float)arg1 scale:(float)arg2 ;
-(id)initWithRank:(float)arg1 scale:(float)arg2 ;
-(float)scale;
-(float)rank;
-(float)absoluteScale;
@end

