/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/NBNotesListCacheDelegate.h>

@protocol NBNotesListCacheDataSource;
@class NSArray;

@interface NBNotesListCache : NSObject <NBNotesListCacheDelegate> {

	id<NBNotesListCacheDataSource> _delegate;
	NSArray* _cache;

}

@property (nonatomic,retain) NSArray * cache;                                             //@synthesize cache=_cache - In the implementation block
@property (assign,nonatomic,__weak) id<NBNotesListCacheDataSource> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)invalidate;
-(void)setDelegate:(id<NBNotesListCacheDataSource>)arg1 ;
-(id<NBNotesListCacheDataSource>)delegate;
-(NSArray *)cache;
-(void)setCache:(NSArray *)arg1 ;
-(int)limit;
@end

