/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>

@class NSDate, NSString, GLCloudFileMetadata, NBNoteDocumentViewState, NSData, NSDictionary;

@interface NBNoteDocumentLocalMetadata : NSObject <NSCoding> {

	char _autosyncBlacklisted;
	NSDate* _lastSyncedDate;
	NSString* _lastSyncedPath;
	GLCloudFileMetadata* _lastSyncedMetadata;
	NBNoteDocumentViewState* _documentViewState;
	NSData* _searchIndexData;
	NSDictionary* _myScriptIndexData;
	NSString* _uuid;
	CGSize _expectedThumbnailSize;

}

@property (nonatomic,retain) NSString * uuid;                                          //@synthesize uuid=_uuid - In the implementation block
@property (nonatomic,retain) NSDate * lastSyncedDate;                                  //@synthesize lastSyncedDate=_lastSyncedDate - In the implementation block
@property (nonatomic,retain) NSString * lastSyncedPath;                                //@synthesize lastSyncedPath=_lastSyncedPath - In the implementation block
@property (nonatomic,retain) GLCloudFileMetadata * lastSyncedMetadata;                 //@synthesize lastSyncedMetadata=_lastSyncedMetadata - In the implementation block
@property (assign,nonatomic) CGSize expectedThumbnailSize;                             //@synthesize expectedThumbnailSize=_expectedThumbnailSize - In the implementation block
@property (nonatomic,retain) NBNoteDocumentViewState * documentViewState;              //@synthesize documentViewState=_documentViewState - In the implementation block
@property (assign,nonatomic) char autosyncBlacklisted;                                 //@synthesize autosyncBlacklisted=_autosyncBlacklisted - In the implementation block
@property (retain) NSData * searchIndexData;                                           //@synthesize searchIndexData=_searchIndexData - In the implementation block
@property (copy) NSDictionary * myScriptIndexData;                                     //@synthesize myScriptIndexData=_myScriptIndexData - In the implementation block
+(CGSize)defaultThumbnailSize;
-(char)autosyncBlacklisted;
-(void)setAutosyncBlacklisted:(char)arg1 ;
-(NSDate *)lastSyncedDate;
-(CGSize)expectedThumbnailSize;
-(void)setExpectedThumbnailSize:(CGSize)arg1 ;
-(NSString *)lastSyncedPath;
-(GLCloudFileMetadata *)lastSyncedMetadata;
-(NBNoteDocumentViewState *)documentViewState;
-(NSData *)searchIndexData;
-(void)setLastSyncedDate:(NSDate *)arg1 ;
-(void)setLastSyncedPath:(NSString *)arg1 ;
-(void)setLastSyncedMetadata:(GLCloudFileMetadata *)arg1 ;
-(void)setDocumentViewState:(NBNoteDocumentViewState *)arg1 ;
-(void)setSearchIndexData:(NSData *)arg1 ;
-(NSDictionary *)myScriptIndexData;
-(void)setMyScriptIndexData:(NSDictionary *)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSString *)uuid;
-(void)setUuid:(NSString *)arg1 ;
@end

