/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class NSMutableArray;

@interface NBPaperCache : NSObject {

	NSMutableArray* _paperLayerCache;

}

@property (nonatomic,readonly) NSMutableArray * paperLayerCache;              //@synthesize paperLayerCache=_paperLayerCache - In the implementation block
+(CGLayerRef)paperLayerForIndex:(int)arg1 scale:(float)arg2 ;
+(id)paperImageForIndex:(int)arg1 ;
+(id)_internalPaperImageForIndex:(int)arg1 scale:(float)arg2 ;
+(CGLayerRef)newCGLayerForPaperImage:(id)arg1 scale:(float)arg2 ;
+(void)purgePaperLayerCache;
+(void)load;
+(id)manager;
-(CGLayerRef)paperLayerForIndex:(int)arg1 scale:(float)arg2 ;
-(void)asynchronouslyInvalidate;
-(NSMutableArray *)paperLayerCache;
-(CGLayerRef)layerForIndex:(int)arg1 scale:(float)arg2 ;
-(void)addLayerToCache:(id)arg1 ;
-(id)init;
-(void)_invalidate;
@end

