/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:09 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NBPageContentManager : NSObject
+(id)allPageDictionaryKeys;
+(id)addPDFPageFromPageContentDictionary:(id)arg1 toFormattedString:(id)arg2 atIndex:(int)arg3 trimBlankPageContentAtEnd:(char)arg4 ;
@end

