/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:07 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NBPageManagerDelegate <NSObject>
@required
-(void)pageManager:(id)arg1 requestsJumpToPage:(int)arg2 animated:(char)arg3;
-(void)pageManager:(id)arg1 requestsInsertPage:(int)arg2;
-(char)pageManager:(id)arg1 requestsDeletePage:(int)arg2;
-(void)pageManager:(id)arg1 requestsClearPage:(int)arg2;
-(void)pageManager:(id)arg1 requestsMovePage:(int)arg2 toIndex:(int)arg3;
-(void)pageManager:(id)arg1 requestsCutPage:(int)arg2;
-(void)pageManager:(id)arg1 requestsCopyPage:(int)arg2;
-(void)pageManager:(id)arg1 requestsPastePage:(int)arg2;
-(void)pageManager:(id)arg1 requestsUpdateBookmarkState:(char)arg2 forPage:(int)arg3;
-(void)pageManager:(id)arg1 requestsSearchFor:(id)arg2;
-(void)pageManagerRequestsClearSearchQuery:(id)arg1;

@end

