/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/NBPageManagerTableViewCell.h>

@class NILabel, UIImageView, UIActivityIndicatorView;

@interface NBPageManagerHelpCell : NBPageManagerTableViewCell {

	char _showActivityIndicator;
	NILabel* _label;
	UIImageView* _imageView;
	UIActivityIndicatorView* _indicatorView;

}

@property (retain) UIImageView * imageView;                              //@synthesize imageView=_imageView - In the implementation block
@property (retain) NILabel * label;                                      //@synthesize label=_label - In the implementation block
@property (retain) UIActivityIndicatorView * indicatorView;              //@synthesize indicatorView=_indicatorView - In the implementation block
@property (assign,nonatomic) char showActivityIndicator;                 //@synthesize showActivityIndicator=_showActivityIndicator - In the implementation block
-(id)initWithText:(id)arg1 andImageKey:(id)arg2 ;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(UIImageView *)imageView;
-(NILabel *)label;
-(void)setLabel:(NILabel *)arg1 ;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)setShowActivityIndicator:(char)arg1 ;
-(UIActivityIndicatorView *)indicatorView;
-(void)setIndicatorView:(UIActivityIndicatorView *)arg1 ;
-(char)showActivityIndicator;
@end

