/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIColor, NSDictionary, NSArray;

@interface NBPDFHighlight : NSObject {

	UIColor* _color;
	NSDictionary* _richMediaPageHighlights;
	NSDictionary* _info;

}

@property (nonatomic,copy) NSDictionary * info;                                   //@synthesize info=_info - In the implementation block
@property (nonatomic,retain) UIColor * color;                                     //@synthesize color=_color - In the implementation block
@property (nonatomic,readonly) NSArray * pdfPageNumbers; 
@property (nonatomic,retain) NSDictionary * richMediaPageHighlights;              //@synthesize richMediaPageHighlights=_richMediaPageHighlights - In the implementation block
-(id)initWithInfo:(id)arg1 color:(id)arg2 ;
-(char)didUnionWithHighlight:(id)arg1 combinedHighlight:(id*)arg2 ;
-(NSArray *)pdfPageNumbers;
-(id)infoForPDFPageNumbers:(id)arg1 ;
-(void)enumerateInfoUsingBlock:(/*^block*/id)arg1 ;
-(void)enumeratePDFPageNumbersUsingBlock:(/*^block*/id)arg1 ;
-(char)isOnPDFPageNumber:(unsigned)arg1 ;
-(char)isOnlyOnPDFPageNumber:(unsigned)arg1 ;
-(id)initWithHighlight:(id)arg1 color:(id)arg2 ;
-(void)setRichMediaPageHighlights:(NSDictionary *)arg1 ;
-(id)changedHighlightWhenRemovingPDFPageNumber:(unsigned)arg1 ;
-(id)subHighlightWithPDFPageNumbers:(id)arg1 ;
-(NSDictionary *)richMediaPageHighlights;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(id)description;
-(UIColor *)color;
-(void)setColor:(UIColor *)arg1 ;
-(NSDictionary *)info;
-(void)setInfo:(NSDictionary *)arg1 ;
@end

