/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/NBPersonalityFlagsMutable.h>
#import <Notability/NBPersonalityFlags.h>

@class NSString, GLGradient, NSNumber, UIColor, NSDictionary;

@interface NBPersonality : NSObject <NBPersonalityFlagsMutable, NBPersonalityFlags> {

	char _useIntrusiveSubjectColors;
	char _prefersNonIntrusiveSubjectColors;
	int _barStyle;
	int _preferredStatusBarStyle;
	NSString* _subjectBackgroundName;
	NSString* _subjectCellBlotOverlayName;
	GLGradient* _subjectBackgroundGradient;
	NSString* _productIdentifier;
	NSNumber* _subjectListBottomSpaceAdjustment;
	UIColor* _organizerBottomToolbarTintColorOverride;
	NSDictionary* _backingColorsDictionary;

}

@property (nonatomic,readonly) NSDictionary * backingColorsDictionary;                       //@synthesize backingColorsDictionary=_backingColorsDictionary - In the implementation block
@property (assign,nonatomic) char useIntrusiveSubjectColors;                                 //@synthesize useIntrusiveSubjectColors=_useIntrusiveSubjectColors - In the implementation block
@property (assign,nonatomic) int barStyle;                                                   //@synthesize barStyle=_barStyle - In the implementation block
@property (assign,nonatomic) int preferredStatusBarStyle;                                    //@synthesize preferredStatusBarStyle=_preferredStatusBarStyle - In the implementation block
@property (nonatomic,retain) NSString * subjectBackgroundName;                               //@synthesize subjectBackgroundName=_subjectBackgroundName - In the implementation block
@property (nonatomic,retain) NSString * subjectCellBlotOverlayName;                          //@synthesize subjectCellBlotOverlayName=_subjectCellBlotOverlayName - In the implementation block
@property (nonatomic,retain) GLGradient * subjectBackgroundGradient;                         //@synthesize subjectBackgroundGradient=_subjectBackgroundGradient - In the implementation block
@property (nonatomic,retain) NSString * productIdentifier;                                   //@synthesize productIdentifier=_productIdentifier - In the implementation block
@property (assign,nonatomic) char prefersNonIntrusiveSubjectColors;                          //@synthesize prefersNonIntrusiveSubjectColors=_prefersNonIntrusiveSubjectColors - In the implementation block
@property (nonatomic,retain) NSNumber * subjectListBottomSpaceAdjustment;                    //@synthesize subjectListBottomSpaceAdjustment=_subjectListBottomSpaceAdjustment - In the implementation block
@property (nonatomic,retain) UIColor * organizerBottomToolbarTintColorOverride;              //@synthesize organizerBottomToolbarTintColorOverride=_organizerBottomToolbarTintColorOverride - In the implementation block
@property (nonatomic,readonly) UIColor * b1; 
@property (nonatomic,readonly) UIColor * b2; 
@property (nonatomic,readonly) UIColor * b3; 
@property (nonatomic,readonly) UIColor * b4; 
@property (nonatomic,readonly) UIColor * b5; 
@property (nonatomic,readonly) UIColor * b6; 
@property (nonatomic,readonly) UIColor * b7; 
@property (nonatomic,readonly) UIColor * f1; 
@property (nonatomic,readonly) UIColor * f2; 
@property (nonatomic,readonly) UIColor * f3; 
@property (nonatomic,readonly) UIColor * f4; 
@property (nonatomic,readonly) UIColor * f5; 
@property (nonatomic,readonly) UIColor * f6; 
@property (nonatomic,readonly) UIColor * f7; 
@property (nonatomic,readonly) UIColor * a1; 
@property (nonatomic,readonly) UIColor * a2; 
@property (nonatomic,readonly) UIColor * a3; 
@property (nonatomic,readonly) UIColor * a4; 
@property (nonatomic,readonly) UIColor * s1; 
@property (nonatomic,readonly) UIColor * s2; 
@property (nonatomic,readonly) UIColor * s3; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)blandPersonality;
+(id)colorDropperPersonality;
+(id)darkPersonality;
+(id)lightPersonality;
+(id)defaultPersonalities;
+(id)bubblegumPersonalityGroup;
+(id)winter1Personality;
+(id)spring1Personality;
+(id)summer1Personality;
+(id)fall1Personality;
+(id)grapePersonality;
+(id)strawberryPersonality;
+(id)mintPersonality;
+(id)allPersonalitiesAndGroups;
+(id)debugPersonalities;
+(id)allPersonalities;
-(UIColor *)b2;
-(UIColor *)a3;
-(UIColor *)s1;
-(UIColor *)f2;
-(UIColor *)s2;
-(UIColor *)s3;
-(UIColor *)b4;
-(UIColor *)b3;
-(UIColor *)f1;
-(UIColor *)f4;
-(UIColor *)b5;
-(UIColor *)b1;
-(NSDictionary *)backingColorsDictionary;
-(id)initWithColorsDictionary:(id)arg1 ;
-(char)useIntrusiveSubjectColors;
-(void)setUseIntrusiveSubjectColors:(char)arg1 ;
-(id)copyWithReplacementAttributes:(id)arg1 ;
-(UIColor *)b6;
-(UIColor *)b7;
-(UIColor *)f3;
-(UIColor *)f5;
-(UIColor *)f6;
-(UIColor *)f7;
-(UIColor *)a4;
-(NSString *)subjectBackgroundName;
-(void)setSubjectBackgroundName:(NSString *)arg1 ;
-(NSString *)subjectCellBlotOverlayName;
-(void)setSubjectCellBlotOverlayName:(NSString *)arg1 ;
-(GLGradient *)subjectBackgroundGradient;
-(void)setSubjectBackgroundGradient:(GLGradient *)arg1 ;
-(char)prefersNonIntrusiveSubjectColors;
-(void)setPrefersNonIntrusiveSubjectColors:(char)arg1 ;
-(NSNumber *)subjectListBottomSpaceAdjustment;
-(void)setSubjectListBottomSpaceAdjustment:(NSNumber *)arg1 ;
-(UIColor *)organizerBottomToolbarTintColorOverride;
-(void)setOrganizerBottomToolbarTintColorOverride:(UIColor *)arg1 ;
-(id)name;
-(int)preferredStatusBarStyle;
-(void)setBarStyle:(int)arg1 ;
-(int)barStyle;
-(id)displayName;
-(void)setPreferredStatusBarStyle:(int)arg1 ;
-(id)fontOfSize:(float)arg1 ;
-(UIColor *)a1;
-(UIColor *)a2;
-(id)lightFontOfSize:(float)arg1 ;
-(id)boldFontOfSize:(float)arg1 ;
-(NSString *)productIdentifier;
-(void)setProductIdentifier:(NSString *)arg1 ;
@end

