/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>

@protocol NBPlaybackManagerTableViewControllerDelegate;
@class UISwitch, RecordingManagerTableViewController, UINavigationController, UISegmentedControl, GingerLabsRecordingsLibrary;

@interface NBPlaybackManagerTableViewController : UITableViewController {

	UISwitch* playbackSwitch;
	RecordingManagerTableViewController* recordingManagerVc;
	UINavigationController* recordingManagerNavController;
	UISegmentedControl* speedControl;
	char _allowsEditing;
	GingerLabsRecordingsLibrary* _recordingLibrary;
	id<NBPlaybackManagerTableViewControllerDelegate> _delegate;

}

@property (nonatomic,retain) GingerLabsRecordingsLibrary * recordingLibrary;                         //@synthesize recordingLibrary=_recordingLibrary - In the implementation block
@property (assign,nonatomic) id<NBPlaybackManagerTableViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign) char allowsEditing;                                                               //@synthesize allowsEditing=_allowsEditing - In the implementation block
-(GingerLabsRecordingsLibrary *)recordingLibrary;
-(void)setRecordingLibrary:(GingerLabsRecordingsLibrary *)arg1 ;
-(void)switchPlayback;
-(void)speedAction:(id)arg1 ;
-(void)showRecordingManager;
-(void)setDelegate:(id<NBPlaybackManagerTableViewControllerDelegate>)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id<NBPlaybackManagerTableViewControllerDelegate>)delegate;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidLoad;
-(char)allowsEditing;
-(void)setAllowsEditing:(char)arg1 ;
@end

