/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:07 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Notability/LibraryNotesViewDelegate.h>
#import <Notability/LibraryNotesViewThumbnailDraggingProtocol.h>
#import <Notability/SearchViewControllerDelegate.h>
#import <Notability/NBSearchControllerDataSource.h>
#import <Notability/NBIPhoneLibrarySortTableViewDelegate.h>
#import <Notability/SearchViewControllerDelegate.h>

@protocol SimpleNotesListDelegate;
@class GLIPhonePopoverView, NBIPhoneLibrarySortTableView, NBSubject, NSString, NINotesView, _TtC10Notability20SearchViewController, GLTouchCatcherView;

@interface NBSimpleNotesListViewController : UIViewController <LibraryNotesViewDelegate, LibraryNotesViewThumbnailDraggingProtocol, SearchViewControllerDelegate, NBSearchControllerDataSource, NBIPhoneLibrarySortTableViewDelegate, SearchViewControllerDelegate> {

	GLIPhonePopoverView* sortPopover;
	NBIPhoneLibrarySortTableView* sortTableView;
	char _searching;
	NBSubject* _subject;
	NSString* _sortState;
	id<SimpleNotesListDelegate> _delegate;
	NINotesView* _notesView;
	_TtC10Notability20SearchViewController* _searchViewController;
	GLTouchCatcherView* _exitSearchTouchCatcher;

}

@property (nonatomic,retain) NINotesView * notesView;                                          //@synthesize notesView=_notesView - In the implementation block
@property (retain) _TtC10Notability20SearchViewController * searchViewController;              //@synthesize searchViewController=_searchViewController - In the implementation block
@property (nonatomic,retain) GLTouchCatcherView * exitSearchTouchCatcher;                      //@synthesize exitSearchTouchCatcher=_exitSearchTouchCatcher - In the implementation block
@property (assign,getter=isSearching,nonatomic) char searching;                                //@synthesize searching=_searching - In the implementation block
@property (nonatomic,retain) NBSubject * subject;                                              //@synthesize subject=_subject - In the implementation block
@property (nonatomic,retain) NSString * sortState;                                             //@synthesize sortState=_sortState - In the implementation block
@property (assign,nonatomic,__weak) id<SimpleNotesListDelegate> delegate;                      //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)touchCatcher:(id)arg1 touchesEnded:(id)arg2 ;
-(void)touchCatcher:(id)arg1 touchesMoved:(id)arg2 ;
-(void)sortTableView:(id)arg1 didSelectSortKey:(id)arg2 ;
-(void)setSortState:(NSString *)arg1 ;
-(void)setNotesView:(NINotesView *)arg1 ;
-(NINotesView *)notesView;
-(NSString *)sortState;
-(GLTouchCatcherView *)exitSearchTouchCatcher;
-(id)subjectToSearch;
-(char)notesView:(id)arg1 didSelectNote:(id)arg2 searchQuery:(id)arg3 ;
-(void)notesView:(id)arg1 didCloud:(char)arg2 document:(id)arg3 ;
-(void)notesView:(id)arg1 didEdit:(char)arg2 document:(id)arg3 ;
-(char)notesView:(id)arg1 requestsEditSelectedDocumentsContains:(id)arg2 ;
-(char)notesView:(id)arg1 requestsCloudSelectedDocumentsContains:(id)arg2 ;
-(void)notesView:(id)arg1 wantsToBeginEditingWithDocument:(id)arg2 ;
-(void)notesViewRequestsRemoveAllEditSelectedNotes:(id)arg1 ;
-(id)notesViewRequestsEditSelectedNotes:(id)arg1 ;
-(void)notesViewRequestsPresentImportUI:(id)arg1 ;
-(char)moving;
-(void)notesViewDidDrag:(id)arg1 ;
-(void)notesView:(id)arg1 isSearching:(char)arg2 query:(id)arg3 ;
-(void)notesViewSortAction:(id)arg1 fromButton:(id)arg2 ;
-(void)notesView:(id)arg1 sortToolDidPickSortStyle:(id)arg2 ;
-(id)notesViewRequestsCurrentSortState:(id)arg1 ;
-(void)notesView:(id)arg1 handleThumbnailMoveGesture:(id)arg2 draggingCell:(id)arg3 draggingThumbnail:(id)arg4 otherVisibleSelectedCells:(id)arg5 ;
-(void)searchViewController:(id)arg1 didSelectDocument:(id)arg2 searchQuery:(id)arg3 withMatchType:(int)arg4 ;
-(void)searchViewController:(id)arg1 showInNoteListForDocument:(id)arg2 ;
-(void)searchViewController:(id)arg1 didChangeSubject:(id)arg2 ;
-(void)willBeginDraggingSearchViewController:(id)arg1 ;
-(id)objectsToSearch;
-(char)notesView:(id)arg1 didSelectNotes:(id)arg2 searchQuery:(id)arg3 ;
-(void)notesView:(id)arg1 didSelectNote:(id)arg2 ;
-(id)requestTopView;
-(void)setExitSearchTouchCatcher:(GLTouchCatcherView *)arg1 ;
-(void)setDelegate:(id<SimpleNotesListDelegate>)arg1 ;
-(void)dealloc;
-(id<SimpleNotesListDelegate>)delegate;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewWillDisappear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(NBSubject *)subject;
-(void)setSubject:(NBSubject *)arg1 ;
-(void)setSearching:(char)arg1 ;
-(char)isSearching;
-(_TtC10Notability20SearchViewController *)searchViewController;
-(void)setSearchViewController:(_TtC10Notability20SearchViewController *)arg1 ;
@end

