/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:09 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/NBUIElement.h>

@class NSString;

@interface NBStackedImageLayerElement : NBUIElement {

	NSString* _contentKey;

}

@property (nonatomic,retain) NSString * contentKey;              //@synthesize contentKey=_contentKey - In the implementation block
-(void)setContentKey:(NSString *)arg1 ;
-(id)yieldViewForOwner:(id)arg1 ;
-(NSString *)contentKey;
@end

