/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>
#import <Notability/NBThemePickerThemeGroupPreviewDelegate.h>

@protocol NBThemePickerTableViewCellDelegate;
@class UIView, NBButton, NILabel, UIImageView, NSString;

@interface NBThemePickerTableViewCell : UITableViewCell <NBThemePickerThemeGroupPreviewDelegate> {

	id<NBThemePickerTableViewCellDelegate> _themePickerCellDelegate;
	UIView* _outerContainer;
	UIView* _previewContainer;
	UIView* _buttonContainer;
	NBButton* _tryButton;
	NBButton* _buyButton;
	UIView* _previewTopBar;
	UIView* _previewHorizontalSeparator;
	NILabel* _previewTitleLabel;
	UIView* _previewBottomArea;
	UIImageView* _checkmark;

}

@property (nonatomic,retain) UIView * outerContainer;                                                            //@synthesize outerContainer=_outerContainer - In the implementation block
@property (nonatomic,retain) UIView * previewContainer;                                                          //@synthesize previewContainer=_previewContainer - In the implementation block
@property (nonatomic,retain) UIView * buttonContainer;                                                           //@synthesize buttonContainer=_buttonContainer - In the implementation block
@property (nonatomic,retain) NBButton * tryButton;                                                               //@synthesize tryButton=_tryButton - In the implementation block
@property (nonatomic,retain) NBButton * buyButton;                                                               //@synthesize buyButton=_buyButton - In the implementation block
@property (nonatomic,retain) UIView * previewTopBar;                                                             //@synthesize previewTopBar=_previewTopBar - In the implementation block
@property (nonatomic,retain) UIView * previewHorizontalSeparator;                                                //@synthesize previewHorizontalSeparator=_previewHorizontalSeparator - In the implementation block
@property (nonatomic,retain) NILabel * previewTitleLabel;                                                        //@synthesize previewTitleLabel=_previewTitleLabel - In the implementation block
@property (nonatomic,retain) UIView * previewBottomArea;                                                         //@synthesize previewBottomArea=_previewBottomArea - In the implementation block
@property (nonatomic,retain) UIImageView * checkmark;                                                            //@synthesize checkmark=_checkmark - In the implementation block
@property (assign,nonatomic,__weak) id<NBThemePickerTableViewCellDelegate> themePickerCellDelegate;              //@synthesize themePickerCellDelegate=_themePickerCellDelegate - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)themeGroupWithIndex:(unsigned)arg1 requestsThemeChangeWithIndex:(unsigned)arg2 ;
-(id)initToRepresentNumberOfPersonalities:(unsigned)arg1 buttonType:(int)arg2 reuseIdentifier:(id)arg3 ;
-(void)setThemePickerCellDelegate:(id<NBThemePickerTableViewCellDelegate>)arg1 ;
-(void)setPersonalityOrGroup:(id)arg1 indexTag:(unsigned)arg2 ;
-(void)setTitle:(id)arg1 priceString:(id)arg2 ;
-(void)singleThemeRequestsThemeChange:(id)arg1 ;
-(void)singleThemeRequestsPreview:(id)arg1 ;
-(void)themeGroupRequestsPreview:(id)arg1 ;
-(void)tryButtonAction:(id)arg1 ;
-(void)buyButtonAction:(id)arg1 ;
-(UIView *)previewTopBar;
-(UIView *)previewContainer;
-(UIView *)previewHorizontalSeparator;
-(UIView *)previewBottomArea;
-(NBButton *)tryButton;
-(NBButton *)buyButton;
-(id<NBThemePickerTableViewCellDelegate>)themePickerCellDelegate;
-(UIView *)outerContainer;
-(void)setOuterContainer:(UIView *)arg1 ;
-(void)setPreviewContainer:(UIView *)arg1 ;
-(void)setTryButton:(NBButton *)arg1 ;
-(void)setBuyButton:(NBButton *)arg1 ;
-(void)setPreviewTopBar:(UIView *)arg1 ;
-(void)setPreviewHorizontalSeparator:(UIView *)arg1 ;
-(void)setPreviewBottomArea:(UIView *)arg1 ;
-(NILabel *)previewTitleLabel;
-(UIImageView *)checkmark;
-(void)setCheckmark:(UIImageView *)arg1 ;
-(void)setPreviewTitleLabel:(NILabel *)arg1 ;
-(UIView *)buttonContainer;
-(void)setButtonContainer:(UIView *)arg1 ;
@end

