/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate;

@interface NBWebClipPasswordManager : NSObject {

	char _isUnlocked;
	NSDate* _backgroundDate;

}

@property (assign,nonatomic) char isUnlocked;                      //@synthesize isUnlocked=_isUnlocked - In the implementation block
@property (nonatomic,retain) NSDate * backgroundDate;              //@synthesize backgroundDate=_backgroundDate - In the implementation block
+(void)performWebClipAction:(/*^block*/id)arg1 ;
+(char)areWebClipsProtected;
+(char)setWebClipPassword:(id)arg1 oldPassword:(id)arg2 ;
+(char)areWebClipsUnlocked;
+(id)sharedManager;
-(void)appDidBackground;
-(void)appWillForeground;
-(void)setBackgroundDate:(NSDate *)arg1 ;
-(NSDate *)backgroundDate;
-(void)setIsUnlocked:(char)arg1 ;
-(id)init;
-(void)dealloc;
-(char)isUnlocked;
@end

