/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/NIExportMenuControllerDelegate.h>
#import <Notability/NotabilityExporterDelegate.h>
#import <Notability/NIFullscreenProgressViewDelegate.h>
#import <UIKit/UIDocumentInteractionControllerDelegate.h>
#import <UIKit/UIPrintInteractionControllerDelegate.h>

@protocol NIExportControllerDelegate;
@class UIViewController, SelectionManager, NIExportMenuController, NotabilityExporter, NIExportDestinationViewController, NIExportConfigurationViewController, NIExportDestinationModalTrayView, UINavigationController, GLPopoverController, UIDocumentInteractionController, NIFullscreenExportProgressView, NSArray, NSString;

@interface NIExportController : NSObject <NIExportMenuControllerDelegate, NotabilityExporterDelegate, NIFullscreenProgressViewDelegate, UIDocumentInteractionControllerDelegate, UIPrintInteractionControllerDelegate> {

	UIViewController* _modalPresentationViewController;
	id<NIExportControllerDelegate> _delegate;
	SelectionManager* _selectionManager;
	NIExportMenuController* _exportMenuController;
	NotabilityExporter* _exporter;
	NIExportDestinationViewController* _destinationViewController;
	NIExportConfigurationViewController* _configurationViewController;
	NIExportDestinationModalTrayView* _exportDestinationGridViewIPhone;
	UINavigationController* _exportMenuNavController;
	GLPopoverController* _exportMenuPopover;
	GLPopoverController* _airDropPopover;
	UIDocumentInteractionController* _documentInteractionController;
	NIFullscreenExportProgressView* _progressView;
	id _presentationViewOrBarButton;
	NSArray* _documentsToExport;
	/*^block*/id _exportWillBeginBlock;
	/*^block*/id _exportProgressBlock;
	/*^block*/id _exportDidCompleteBlock;

}

@property (nonatomic,retain) NIExportMenuController * exportMenuController;                                   //@synthesize exportMenuController=_exportMenuController - In the implementation block
@property (nonatomic,retain) NotabilityExporter * exporter;                                                   //@synthesize exporter=_exporter - In the implementation block
@property (nonatomic,retain) NIExportDestinationViewController * destinationViewController;                   //@synthesize destinationViewController=_destinationViewController - In the implementation block
@property (nonatomic,retain) NIExportConfigurationViewController * configurationViewController;               //@synthesize configurationViewController=_configurationViewController - In the implementation block
@property (nonatomic,retain) NIExportDestinationModalTrayView * exportDestinationGridViewIPhone;              //@synthesize exportDestinationGridViewIPhone=_exportDestinationGridViewIPhone - In the implementation block
@property (nonatomic,retain) UINavigationController * exportMenuNavController;                                //@synthesize exportMenuNavController=_exportMenuNavController - In the implementation block
@property (nonatomic,retain) GLPopoverController * exportMenuPopover;                                         //@synthesize exportMenuPopover=_exportMenuPopover - In the implementation block
@property (nonatomic,retain) GLPopoverController * airDropPopover;                                            //@synthesize airDropPopover=_airDropPopover - In the implementation block
@property (nonatomic,retain) UIDocumentInteractionController * documentInteractionController;                 //@synthesize documentInteractionController=_documentInteractionController - In the implementation block
@property (nonatomic,retain) NIFullscreenExportProgressView * progressView;                                   //@synthesize progressView=_progressView - In the implementation block
@property (assign,nonatomic,__weak) id presentationViewOrBarButton;                                           //@synthesize presentationViewOrBarButton=_presentationViewOrBarButton - In the implementation block
@property (nonatomic,retain) NSArray * documentsToExport;                                                     //@synthesize documentsToExport=_documentsToExport - In the implementation block
@property (nonatomic,copy) id exportWillBeginBlock;                                                           //@synthesize exportWillBeginBlock=_exportWillBeginBlock - In the implementation block
@property (nonatomic,copy) id exportProgressBlock;                                                            //@synthesize exportProgressBlock=_exportProgressBlock - In the implementation block
@property (nonatomic,copy) id exportDidCompleteBlock;                                                         //@synthesize exportDidCompleteBlock=_exportDidCompleteBlock - In the implementation block
@property (assign,nonatomic,__weak) UIViewController * modalPresentationViewController;                       //@synthesize modalPresentationViewController=_modalPresentationViewController - In the implementation block
@property (assign,nonatomic,__weak) id<NIExportControllerDelegate> delegate;                                  //@synthesize delegate=_delegate - In the implementation block
@property (retain) SelectionManager * selectionManager;                                                       //@synthesize selectionManager=_selectionManager - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setModalPresentationViewController:(UIViewController *)arg1 ;
-(void)presentExportViewForDocuments:(id)arg1 fromViewOrBarButton:(id)arg2 exportWillBeginBlock:(/*^block*/id)arg3 progressBlock:(/*^block*/id)arg4 completionBlock:(/*^block*/id)arg5 ;
-(void)exporterExportSucceeded:(id)arg1 ;
-(void)exporterExportFailed:(id)arg1 ;
-(void)exporter:(id)arg1 wantsToPresentPrintInteractionController:(id)arg2 ;
-(void)exporter:(id)arg1 wantsToPresentActivityViewController:(id)arg2 ;
-(void)exporter:(id)arg1 wantsToPresentDocumentInteractionController:(id)arg2 ;
-(void)fullscreenProgressViewDidCancel:(id)arg1 ;
-(void)requestDismissalOfModalUIAnimated:(char)arg1 ;
-(void)exportMenuDidRequestTweet;
-(void)exportMenuFinishedConfiguringCloudManager;
-(char)exportMenuRequestsPreviewWithCompletion:(/*^block*/id)arg1 ;
-(id)exportMenuRequestsCurrentOptions;
-(UIViewController *)modalPresentationViewController;
-(void)setExporter:(NotabilityExporter *)arg1 ;
-(void)setExportMenuController:(NIExportMenuController *)arg1 ;
-(NIExportMenuController *)exportMenuController;
-(void)setConfigurationViewController:(NIExportConfigurationViewController *)arg1 ;
-(void)setDestinationViewController:(NIExportDestinationViewController *)arg1 ;
-(void)setExportMenuNavController:(UINavigationController *)arg1 ;
-(UINavigationController *)exportMenuNavController;
-(void)setExportMenuPopover:(GLPopoverController *)arg1 ;
-(void)setExportDestinationGridViewIPhone:(NIExportDestinationModalTrayView *)arg1 ;
-(NIExportConfigurationViewController *)configurationViewController;
-(void)sharedLazyInit;
-(void)setExportWillBeginBlock:(id)arg1 ;
-(void)setExportProgressBlock:(id)arg1 ;
-(void)setExportDidCompleteBlock:(id)arg1 ;
-(void)setDocumentsToExport:(NSArray *)arg1 ;
-(void)setPresentationViewOrBarButton:(id)arg1 ;
-(NSArray *)documentsToExport;
-(void)lazyInitForIPad;
-(GLPopoverController *)exportMenuPopover;
-(NIExportDestinationModalTrayView *)exportDestinationGridViewIPhone;
-(void)lazyInitForIPhone;
-(void)iPhoneDismissAction;
-(GLPopoverController *)airDropPopover;
-(id)exportProgressBlock;
-(void)hideProgressView;
-(id)exportDidCompleteBlock;
-(id)exportWillBeginBlock;
-(void)showProgressViewForOperation:(id)arg1 ;
-(void)_prepareViewsForExportPresentationWithExportBlock:(/*^block*/id)arg1 ;
-(void)setAirDropPopover:(GLPopoverController *)arg1 ;
-(id)presentationViewOrBarButton;
-(NotabilityExporter *)exporter;
-(id)init;
-(void)setDelegate:(id<NIExportControllerDelegate>)arg1 ;
-(id<NIExportControllerDelegate>)delegate;
-(NIExportDestinationViewController *)destinationViewController;
-(id)documentInteractionControllerViewControllerForPreview:(id)arg1 ;
-(void)documentInteractionControllerDidDismissOptionsMenu:(id)arg1 ;
-(void)documentInteractionControllerDidDismissOpenInMenu:(id)arg1 ;
-(void)setDocumentInteractionController:(UIDocumentInteractionController *)arg1 ;
-(UIDocumentInteractionController *)documentInteractionController;
-(void)printInteractionControllerDidDismissPrinterOptions:(id)arg1 ;
-(SelectionManager *)selectionManager;
-(NIFullscreenExportProgressView *)progressView;
-(void)setProgressView:(NIFullscreenExportProgressView *)arg1 ;
-(void)setSelectionManager:(SelectionManager *)arg1 ;
@end

