/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class NSLayoutConstraint, UIView, GLActivityIndicatorView, UILabel;

@interface NIiCloudEmergencyView : UIView {

	char _didAppear;
	int _iCloudEmergencyState;
	int _viewState;
	NSLayoutConstraint* _heightConstraint;
	UIView* _retryingView;
	GLActivityIndicatorView* _retryingActivityIndicatorView;
	NSLayoutConstraint* _retryingViewYConstraint;
	UIView* _ongoingView;
	NSLayoutConstraint* _ongoingViewYConstraint;
	UILabel* _ongoingBodyLabel;
	UIView* _minimizedView;
	NSLayoutConstraint* _minimizedViewYConstraint;

}

@property (assign,nonatomic) int viewState;                                                        //@synthesize viewState=_viewState - In the implementation block
@property (assign,nonatomic) char didAppear;                                                       //@synthesize didAppear=_didAppear - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * heightConstraint;                                //@synthesize heightConstraint=_heightConstraint - In the implementation block
@property (nonatomic,retain) UIView * retryingView;                                                //@synthesize retryingView=_retryingView - In the implementation block
@property (nonatomic,retain) GLActivityIndicatorView * retryingActivityIndicatorView;              //@synthesize retryingActivityIndicatorView=_retryingActivityIndicatorView - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * retryingViewYConstraint;                         //@synthesize retryingViewYConstraint=_retryingViewYConstraint - In the implementation block
@property (nonatomic,retain) UIView * ongoingView;                                                 //@synthesize ongoingView=_ongoingView - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * ongoingViewYConstraint;                          //@synthesize ongoingViewYConstraint=_ongoingViewYConstraint - In the implementation block
@property (nonatomic,retain) UILabel * ongoingBodyLabel;                                           //@synthesize ongoingBodyLabel=_ongoingBodyLabel - In the implementation block
@property (nonatomic,retain) UIView * minimizedView;                                               //@synthesize minimizedView=_minimizedView - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * minimizedViewYConstraint;                        //@synthesize minimizedViewYConstraint=_minimizedViewYConstraint - In the implementation block
@property (assign,nonatomic) int iCloudEmergencyState;                                             //@synthesize iCloudEmergencyState=_iCloudEmergencyState - In the implementation block
-(NSLayoutConstraint *)retryingViewYConstraint;
-(UIView *)retryingView;
-(void)setRetryingViewYConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)ongoingViewYConstraint;
-(UIView *)ongoingView;
-(void)setOngoingViewYConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)minimizedViewYConstraint;
-(UIView *)minimizedView;
-(void)setMinimizedViewYConstraint:(NSLayoutConstraint *)arg1 ;
-(GLActivityIndicatorView *)retryingActivityIndicatorView;
-(void)_minimize:(id)arg1 ;
-(void)setRetryingView:(UIView *)arg1 ;
-(void)setRetryingActivityIndicatorView:(GLActivityIndicatorView *)arg1 ;
-(id)_foregroundContentColor;
-(float)_retryingLabelFontSize;
-(float)_retryingActivityAndLabelHorizontalSpacing;
-(float)_retryingTopAndBottomMargin;
-(float)_retryingSideMargin;
-(void)setOngoingView:(UIView *)arg1 ;
-(float)_ongoingTitleLabelFontSize;
-(void)setOngoingBodyLabel:(UILabel *)arg1 ;
-(UILabel *)ongoingBodyLabel;
-(float)_ongoingBodyLabelFontSize;
-(float)_ongoingTroubleshootingButtonFontSize;
-(void)_troubleshoot:(id)arg1 ;
-(float)_ongoingTroubleshootingButtonMinimumWidth;
-(float)_ongoingTroubleshootingButtonHeight;
-(float)_ongoingTroubleshootingButtonTitleMargin;
-(float)_ongoingTopMargin;
-(float)_ongoingTitleAndBodyVerticalSpacing;
-(float)_ongoingBodyAndTroubleshootingButtonVerticalSpacing;
-(float)_ongoingSideMargin;
-(float)_ongoingBottomMargin;
-(void)_maximize:(id)arg1 ;
-(void)setMinimizedView:(UIView *)arg1 ;
-(float)_minimizedLabelFontSize;
-(float)_minimizedTopAndBottomMargin;
-(void)_setupRetryingView;
-(void)_setupOngoingView;
-(void)_setupMinimizedView;
-(int)_convertStateToViewState:(int)arg1 ;
-(void)setDidAppear:(char)arg1 ;
-(int)iCloudEmergencyState;
-(float)_ongoingBodyLabelHorizontalMargin;
-(void)_didFinishAnimationsToViewState:(int)arg1 ;
-(void)setICloudEmergencyState:(int)arg1 ;
-(void)didFinishAnimationsToState:(int)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(void)dealloc;
-(void)viewWillAppear:(char)arg1 ;
-(void)viewDidDisappear:(char)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(NSLayoutConstraint *)heightConstraint;
-(void)setHeightConstraint:(NSLayoutConstraint *)arg1 ;
-(char)didAppear;
-(int)viewState;
-(void)setViewState:(int)arg1 ;
@end

