/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NIMultiViewRatioRangeInfo : NSObject {

	char _snaps;
	char _snapsWhileDragging;
	float _ratio;
	float _minRatio;
	float _maxRatio;
	float _snapRatio;
	float _leftEdgePriorityOnLeftView;
	float _rightEdgePriorityOnLeftView;
	float _leftEdgePriorityOnRightView;
	float _rightEdgePriorityOnRightView;

}

@property (assign,nonatomic) float ratio;                                     //@synthesize ratio=_ratio - In the implementation block
@property (assign,nonatomic) float minRatio;                                  //@synthesize minRatio=_minRatio - In the implementation block
@property (assign,nonatomic) float maxRatio;                                  //@synthesize maxRatio=_maxRatio - In the implementation block
@property (assign,nonatomic) char snaps;                                      //@synthesize snaps=_snaps - In the implementation block
@property (assign,nonatomic) char snapsWhileDragging;                         //@synthesize snapsWhileDragging=_snapsWhileDragging - In the implementation block
@property (assign,nonatomic) float snapRatio;                                 //@synthesize snapRatio=_snapRatio - In the implementation block
@property (assign,nonatomic) float leftEdgePriorityOnLeftView;                //@synthesize leftEdgePriorityOnLeftView=_leftEdgePriorityOnLeftView - In the implementation block
@property (assign,nonatomic) float rightEdgePriorityOnLeftView;               //@synthesize rightEdgePriorityOnLeftView=_rightEdgePriorityOnLeftView - In the implementation block
@property (assign,nonatomic) float leftEdgePriorityOnRightView;               //@synthesize leftEdgePriorityOnRightView=_leftEdgePriorityOnRightView - In the implementation block
@property (assign,nonatomic) float rightEdgePriorityOnRightView;              //@synthesize rightEdgePriorityOnRightView=_rightEdgePriorityOnRightView - In the implementation block
-(float)snappedRatioForDragging:(char)arg1 ;
-(float)alphaForLeftView:(char)arg1 ;
-(float)marginForMaxMargin:(float)arg1 forLeftView:(char)arg2 ;
-(float)widthForLeftView:(char)arg1 multiViewWidth:(float)arg2 separatorWidth:(float)arg3 ;
-(float)leftEdgePriorityOnLeftView;
-(float)rightEdgePriorityOnLeftView;
-(float)leftEdgePriorityOnRightView;
-(float)rightEdgePriorityOnRightView;
-(float)minRatio;
-(float)maxRatio;
-(void)setMinRatio:(float)arg1 ;
-(void)setMaxRatio:(float)arg1 ;
-(void)setSnaps:(char)arg1 ;
-(void)setSnapsWhileDragging:(char)arg1 ;
-(void)setSnapRatio:(float)arg1 ;
-(void)setLeftEdgePriorityOnLeftView:(float)arg1 ;
-(void)setRightEdgePriorityOnLeftView:(float)arg1 ;
-(void)setLeftEdgePriorityOnRightView:(float)arg1 ;
-(void)setRightEdgePriorityOnRightView:(float)arg1 ;
-(char)snaps;
-(char)snapsWhileDragging;
-(float)snapRatio;
-(float)ratio;
-(void)setRatio:(float)arg1 ;
@end

