/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/NINoteViewTopToolbar.h>
#import <Notability/GLPopoverControllerDelegate.h>
#import <UIKit/UINavigationControllerDelegate.h>
#import <Notability/InsertMediaPopoverManager.h>
#import <Notability/NIInputToolDelegate.h>
#import <Notability/GLUndoRedoButtonDelegate.h>
#import <Notability/ToggleColorPalettePencilInteractionTarget.h>

@class NBButton, InsertMediaPopoverViewController, GLPopoverController, UINavigationController, UIView, NSArray, NSString;

@interface NINoteViewTopToolbar_iPad : NINoteViewTopToolbar <GLPopoverControllerDelegate, UINavigationControllerDelegate, InsertMediaPopoverManager, NIInputToolDelegate, GLUndoRedoButtonDelegate, ToggleColorPalettePencilInteractionTarget> {

	NBButton* exportButton;
	NBButton* insertMediaButton;
	InsertMediaPopoverViewController* mediaPopoverViewController;
	GLPopoverController* mediaPopover;
	UINavigationController* mediaNavigationController;
	CGSize mediaNavControllerBaseSize;
	NBButton* pageNavigatorButton;
	NBButton* noteNavigatorButton;
	char _configureForMediumSizeClass;
	GLPopoverController* _popoverToRedisplay;
	UIView* _undoSpacer1;
	UIView* _undoSpacer2;
	UIView* _recordingSpacer1;
	UIView* _recordingSpacer2;
	NSArray* _pageManagerOpenAnimationCachedImages;
	NSArray* _pageManagerCloseAnimationCachedImages;

}

@property (nonatomic,retain) GLPopoverController * popoverToRedisplay;                     //@synthesize popoverToRedisplay=_popoverToRedisplay - In the implementation block
@property (nonatomic,retain) UIView * undoSpacer1;                                         //@synthesize undoSpacer1=_undoSpacer1 - In the implementation block
@property (nonatomic,retain) UIView * undoSpacer2;                                         //@synthesize undoSpacer2=_undoSpacer2 - In the implementation block
@property (nonatomic,retain) UIView * recordingSpacer1;                                    //@synthesize recordingSpacer1=_recordingSpacer1 - In the implementation block
@property (nonatomic,retain) UIView * recordingSpacer2;                                    //@synthesize recordingSpacer2=_recordingSpacer2 - In the implementation block
@property (nonatomic,retain) NSArray * pageManagerOpenAnimationCachedImages;               //@synthesize pageManagerOpenAnimationCachedImages=_pageManagerOpenAnimationCachedImages - In the implementation block
@property (nonatomic,retain) NSArray * pageManagerCloseAnimationCachedImages;              //@synthesize pageManagerCloseAnimationCachedImages=_pageManagerCloseAnimationCachedImages - In the implementation block
@property (assign,nonatomic) char configureForMediumSizeClass;                             //@synthesize configureForMediumSizeClass=_configureForMediumSizeClass - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)mdmConfigurationChanged;
-(void)togglePageManager;
-(void)setConfigureForMediumSizeClass:(char)arg1 ;
-(void)setTopToolbarDelegate:(id)arg1 ;
-(void)tearDownBeforeUniversalSizeClassChange;
-(void)setUpUtilityPopover;
-(void)exportButtonAction:(id)arg1 ;
-(void)navigationManagerWillOpen;
-(void)navigationManagerWillClose;
-(void)toggleColorPalette;
-(id)customViewToolbarItemsForSizeAndState;
-(void)setPopoverToRedisplay:(GLPopoverController *)arg1 ;
-(GLPopoverController *)popoverToRedisplay;
-(void)insertMediaPopover:(id)arg1 wantsToPresentCameraController:(id)arg2 ;
-(void)insertMediaPopoverShouldBeDismissed:(id)arg1 ;
-(void)eraserButtonAction;
-(void)selectButtonAction;
-(void)undoRedoButtonWillShowActionSheet:(id)arg1 ;
-(void)inputToolView:(id)arg1 didSelectItem:(id)arg2 isPencil:(char)arg3 ;
-(void)textModeButtonAction;
-(void)updateConstraintsEditAllowed;
-(void)showMediaMenu;
-(CGRect)exportButtonRect;
-(UIView *)undoSpacer1;
-(UIView *)undoSpacer2;
-(UIView *)recordingSpacer1;
-(UIView *)recordingSpacer2;
-(void)setUndoSpacer1:(UIView *)arg1 ;
-(void)setUndoSpacer2:(UIView *)arg1 ;
-(void)setRecordingSpacer1:(UIView *)arg1 ;
-(void)setRecordingSpacer2:(UIView *)arg1 ;
-(char)configureForMediumSizeClass;
-(void)displayMediaPopover;
-(void)penButtonAction:(char)arg1 ;
-(void)highlighterButtonAction:(char)arg1 ;
-(void)readOnlyAction;
-(NSArray *)pageManagerOpenAnimationCachedImages;
-(void)setPageManagerOpenAnimationCachedImages:(NSArray *)arg1 ;
-(NSArray *)pageManagerCloseAnimationCachedImages;
-(void)setPageManagerCloseAnimationCachedImages:(NSArray *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(char)arg3 ;
@end

