/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@class NSArray, UIView;

@interface NINomadView : UIView {

	char _inAltTransition;
	char _inHomeTransition;
	NSArray* _homeStateConstraints;
	UIView* _homeParentView;
	NSArray* _alternateStateConstraints;
	UIView* _alternateParentView;
	/*^block*/id _extraAnimationsForEnteringAlternateState;
	/*^block*/id _extraAnimationsForEnteringHomeState;
	int _numberOfInFlightTransitions;

}

@property (assign,nonatomic) int numberOfInFlightTransitions;                        //@synthesize numberOfInFlightTransitions=_numberOfInFlightTransitions - In the implementation block
@property (assign,nonatomic) char inAltTransition;                                   //@synthesize inAltTransition=_inAltTransition - In the implementation block
@property (assign,nonatomic) char inHomeTransition;                                  //@synthesize inHomeTransition=_inHomeTransition - In the implementation block
@property (nonatomic,retain) NSArray * homeStateConstraints;                         //@synthesize homeStateConstraints=_homeStateConstraints - In the implementation block
@property (assign,nonatomic,__weak) UIView * homeParentView;                         //@synthesize homeParentView=_homeParentView - In the implementation block
@property (nonatomic,retain) NSArray * alternateStateConstraints;                    //@synthesize alternateStateConstraints=_alternateStateConstraints - In the implementation block
@property (assign,nonatomic,__weak) UIView * alternateParentView;                    //@synthesize alternateParentView=_alternateParentView - In the implementation block
@property (nonatomic,copy) id extraAnimationsForEnteringAlternateState;              //@synthesize extraAnimationsForEnteringAlternateState=_extraAnimationsForEnteringAlternateState - In the implementation block
@property (nonatomic,copy) id extraAnimationsForEnteringHomeState;                   //@synthesize extraAnimationsForEnteringHomeState=_extraAnimationsForEnteringHomeState - In the implementation block
+(char)requiresConstraintBasedLayout;
-(void)setExtraAnimationsForEnteringHomeState:(id)arg1 ;
-(void)setExtraAnimationsForEnteringAlternateState:(id)arg1 ;
-(void)setHomeParentView:(UIView *)arg1 ;
-(void)travelToAlternateStateWithExtraAnimations:(/*^block*/id)arg1 completion:(/*^block*/id)arg2 ;
-(void)travelToHomeStateWithExtraAnimations:(/*^block*/id)arg1 completion:(/*^block*/id)arg2 ;
-(UIView *)alternateParentView;
-(void)setAlternateParentView:(UIView *)arg1 ;
-(void)setAlternateStateConstraints:(NSArray *)arg1 ;
-(void)setHomeStateConstraints:(NSArray *)arg1 ;
-(void)travelToHomeState;
-(char)inAltTransition;
-(char)inHomeTransition;
-(void)setInAltTransition:(char)arg1 ;
-(NSArray *)alternateStateConstraints;
-(id)extraAnimationsForEnteringAlternateState;
-(void)travelToNewView:(id)arg1 constraintsToAdd:(id)arg2 extraAnimations:(/*^block*/id)arg3 completion:(/*^block*/id)arg4 ;
-(void)setInHomeTransition:(char)arg1 ;
-(UIView *)homeParentView;
-(NSArray *)homeStateConstraints;
-(id)extraAnimationsForEnteringHomeState;
-(void)travelToAlternateState;
-(int)numberOfInFlightTransitions;
-(void)setNumberOfInFlightTransitions:(int)arg1 ;
-(void)setHidden:(char)arg1 ;
@end

