/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:09 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIScrollView.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <UIKit/UIScrollViewDelegate.h>

@protocol NINoteScrollViewContentView, NINoteScrollViewDelegate;
@class UIView, NSTimer, NIPalmGestureRecognizer, NSString;

@interface NINoteScrollView : UIScrollView <UIGestureRecognizerDelegate, UIScrollViewDelegate> {

	UIView*<NINoteScrollViewContentView> viewToZoom;
	id<NINoteScrollViewDelegate> zoomDelegate;
	float _absoluteZoomScale;
	float interfaceZoomFactor;
	char isZoomEnabled;
	char ignoreScrollCallback;
	NSTimer* reenableAnimatedScrollingTimer;
	char isAnimatingScrollRectToVisible;
	NIPalmGestureRecognizer* _palmGestureRecognizer;
	char _ignoreContentAndZoomAdjustments;
	char _allowPanningWithStylus;
	float absoluteZoomScale;
	float _absMinZoom;
	float _absMaxZoom;

}

@property (assign,nonatomic) char ignoreContentAndZoomAdjustments;                          //@synthesize ignoreContentAndZoomAdjustments=_ignoreContentAndZoomAdjustments - In the implementation block
@property (nonatomic,retain) UIView*<NINoteScrollViewContentView> viewToZoom; 
@property (assign,nonatomic,__weak) id<NINoteScrollViewDelegate> zoomDelegate; 
@property (assign,nonatomic) float absoluteZoomScale; 
@property (assign,nonatomic) float interfaceZoomFactor; 
@property (assign,nonatomic) float absMinZoom;                                              //@synthesize absMinZoom=_absMinZoom - In the implementation block
@property (assign,nonatomic) float absMaxZoom;                                              //@synthesize absMaxZoom=_absMaxZoom - In the implementation block
@property (nonatomic,readonly) float absMinInterfaceZoom; 
@property (nonatomic,readonly) float absMaxInterfaceZoom; 
@property (assign,nonatomic) char ignoreScrollCallback; 
@property (assign,nonatomic) char allowPanningWithStylus;                                   //@synthesize allowPanningWithStylus=_allowPanningWithStylus - In the implementation block
@property (retain) NIPalmGestureRecognizer * palmGestureRecognizer; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)didTransitionToSize:(CGSize)arg1 ;
-(NIPalmGestureRecognizer *)palmGestureRecognizer;
-(void)setPalmGestureRecognizer:(NIPalmGestureRecognizer *)arg1 ;
-(void)setViewToZoom:(UIView*<NINoteScrollViewContentView>)arg1 ;
-(void)setAbsoluteZoomScale:(float)arg1 ;
-(void)cancelPanZoom:(id)arg1 ;
-(void)resetZoomAnimated:(char)arg1 ;
-(void)resetZoomAnimated:(char)arg1 allowRedraw:(char)arg2 ;
-(float)absMinZoom;
-(float)absMaxZoom;
-(void)updateMinimumAndMaximumZoomScales;
-(float)interfaceZoomFactor;
-(char)ignoreContentAndZoomAdjustments;
-(CGPoint)centeredIfNecessaryContentOffsetForContentOffset:(CGPoint)arg1 bounds:(CGRect)arg2 contentSize:(CGSize)arg3 ;
-(void)setIgnoreContentAndZoomAdjustments:(char)arg1 ;
-(char)allowPanningWithStylus;
-(void)reenableAnimatedScrolling;
-(void)setMinimumNumberTouchesForPanning:(int)arg1 ;
-(void)enableZooming:(char)arg1 ;
-(void)setInterfaceZoomFactor:(float)arg1 ;
-(float)absoluteZoomScale;
-(float)absMinInterfaceZoom;
-(float)absMaxInterfaceZoom;
-(void)ignoreContentAndZoomAdjustmentsWithBlock:(/*^block*/id)arg1 ;
-(float)minZoomForDevice;
-(UIView*<NINoteScrollViewContentView>)viewToZoom;
-(char)ignoreScrollCallback;
-(void)setIgnoreScrollCallback:(char)arg1 ;
-(void)setAbsMinZoom:(float)arg1 ;
-(void)setAbsMaxZoom:(float)arg1 ;
-(void)setAllowPanningWithStylus:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(char)arg2 ;
-(void)scrollViewWillBeginDecelerating:(id)arg1 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(void)scrollViewDidEndScrollingAnimation:(id)arg1 ;
-(id)viewForZoomingInScrollView:(id)arg1 ;
-(void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2 ;
-(void)scrollViewDidEndZooming:(id)arg1 withView:(id)arg2 atScale:(float)arg3 ;
-(char)gestureRecognizerShouldBegin:(id)arg1 ;
-(char)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(char)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2 ;
-(char)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(void)scrollRectToVisible:(CGRect)arg1 animated:(char)arg2 ;
-(void)didMoveToSuperview;
-(void)setContentOffset:(CGPoint)arg1 ;
-(void)setZoomScale:(float)arg1 animated:(char)arg2 ;
-(void)resetZoom;
-(void)setZoomDelegate:(id<NINoteScrollViewDelegate>)arg1 ;
-(id<NINoteScrollViewDelegate>)zoomDelegate;
@end

