/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class NSMutableArray;

@interface NITouchStatistics : NSObject {

	NSMutableArray* _touchRadiusArray;
	NSMutableArray* _touchLocationsArray;
	NSMutableArray* _touchDatesArray;
	float _distanceTraveled;
	float _wiggliness;
	float _maxRadius;
	float _minRadius;

}

@property (retain) NSMutableArray * touchRadiusArray;                 //@synthesize touchRadiusArray=_touchRadiusArray - In the implementation block
@property (retain) NSMutableArray * touchLocationsArray;              //@synthesize touchLocationsArray=_touchLocationsArray - In the implementation block
@property (retain) NSMutableArray * touchDatesArray;                  //@synthesize touchDatesArray=_touchDatesArray - In the implementation block
@property (assign) float distanceTraveled;                            //@synthesize distanceTraveled=_distanceTraveled - In the implementation block
@property (assign) float wiggliness;                                  //@synthesize wiggliness=_wiggliness - In the implementation block
@property (assign) float maxRadius;                                   //@synthesize maxRadius=_maxRadius - In the implementation block
@property (assign) float minRadius;                                   //@synthesize minRadius=_minRadius - In the implementation block
-(id)initWithDataPoint:(float)arg1 location:(CGPoint)arg2 ;
-(void)addDataPointWithRadius:(float)arg1 location:(CGPoint)arg2 ;
-(float)minRadius;
-(float)standardDeviationRadius;
-(float)medianRadius;
-(float)distanceTraveled;
-(void)setTouchRadiusArray:(NSMutableArray *)arg1 ;
-(void)setTouchLocationsArray:(NSMutableArray *)arg1 ;
-(void)setTouchDatesArray:(NSMutableArray *)arg1 ;
-(void)setDistanceTraveled:(float)arg1 ;
-(void)setWiggliness:(float)arg1 ;
-(void)setMaxRadius:(float)arg1 ;
-(void)setMinRadius:(float)arg1 ;
-(NSMutableArray *)touchRadiusArray;
-(NSMutableArray *)touchLocationsArray;
-(NSMutableArray *)touchDatesArray;
-(void)accumulateWigglinessForLastTouchLocation;
-(void)updateMaxRadiusWithRadius:(float)arg1 ;
-(void)updateMinRadiusWithRadius:(float)arg1 ;
-(id)sortedDataPoints;
-(float)meanRadius;
-(CGPoint)filteredDifference:(int)arg1 filterAmount:(int)arg2 ;
-(float)wiggliness;
-(CGPoint)filteredLocation:(int)arg1 filterAmount:(int)arg2 ;
-(CGPoint)initialLocation;
-(float)averageSpeed;
-(double)age;
-(float)maxRadius;
@end

