/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface Notability.SupportStats : NSObject {

	 iCloudStats;
	 lock;
	 logsParentUrl;

}

@property (readonly,nonatomic) double librarySize; 
@property (readonly,nonatomic) NSString * appVersionSupportString; 
@property (readonly,nonatomic) NSString * iOSVersionSupportString; 
@property (readonly,nonatomic) NSString * supportString; 
+(id)shared;
+(void)setup;
-(void)updateICloudStatsWithItem:(id)arg1 uuid:(id)arg2 ;
-(NSString *)supportString;
-(void)supportAttachmentZipData:(/*^block*/id)arg1 ;
-(void)saveStackTraceInfoForException:(id)arg1 ;
-(double)librarySize;
-(NSString *)appVersionSupportString;
-(NSString *)iOSVersionSupportString;
-(id)init;
@end

