/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class NSURL, NBNoteDocument, NSString, NSArray;

@interface Notability.GLPDFSharedDocument : NSObject {

	 url;
	 noteDocument;
	 pdfName;
	 _glPdfDocument;

}

@property (readonly,nonatomic) NSURL * url; 
@property (assign,__weak,nonatomic) NBNoteDocument * noteDocument; 
@property (readonly,nonatomic) NSString * pdfName; 
@property (readonly,nonatomic) int count; 
@property (readonly,nonatomic) CGPDFDocumentRef document; 
@property (readonly,nonatomic) NSArray * pages; 
@property (readonly,nonatomic) NSArray * pagesMetadata; 
@property (readonly,nonatomic) int loadedPagesCount; 
-(NBNoteDocument *)noteDocument;
-(void)setNoteDocument:(NBNoteDocument *)arg1 ;
-(id)initWithNote:(id)arg1 pdfName:(id)arg2 ;
-(void)releaseDocument;
-(int)loadedPagesCount;
-(NSArray *)pagesMetadata;
-(NSString *)pdfName;
-(CGPDFPageRef)pageAt:(int)arg1 ;
-(void)releasePages;
-(id)init;
-(int)count;
-(NSURL *)url;
-(CGPDFDocumentRef)document;
-(NSArray *)pages;
@end

