/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSDictionary;

@interface Notability.GLFontFamilyManager : NSObject {

	 queue;
	 _families;
	 _familiesForPreferredLocales;
	 _recentlyUsedFamilies;
	 familyNamesForPreferredLocales.storage;

}

@property (readonly,nonatomic) NSArray * fontSizeDefaults; 
@property (readonly,nonatomic) float minimumFontSize; 
@property (readonly,nonatomic) float maximumFontSize; 
@property (readonly,nonatomic) NSDictionary * families; 
@property (readonly,nonatomic) NSDictionary * familiesForPreferredLocales; 
@property (readonly,nonatomic) NSArray * recentlyUsedFamilies; 
@property (readonly,nonatomic) NSArray * familyNames; 
@property (copy,nonatomic) NSArray * familyNamesForPreferredLocales; 
+(id)languagesFontMap;
+(id)defaultFontFamily;
+(id)defaultFont;
+(id)shared;
-(float)maximumFontSize;
-(id)fontSizeDefaultsIncludingSize:(float)arg1 ;
-(NSArray *)fontSizeDefaults;
-(float)minimumFontSize;
-(id)familyNamed:(id)arg1 ;
-(id)familyFallingBackToDefaultNamed:(id)arg1 ;
-(NSArray *)familyNamesForPreferredLocales;
-(NSArray *)recentlyUsedFamilies;
-(void)useFamily:(id)arg1 ;
-(NSDictionary *)families;
-(NSDictionary *)familiesForPreferredLocales;
-(void)setFamilyNamesForPreferredLocales:(NSArray *)arg1 ;
-(NSArray *)familyNames;
-(id)init;
@end

