/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/NBImportOperationDelegate.h>

@protocol NBOrganizerDataStore;
@class NSMutableDictionary, NSMutableArray, NSString;

@interface NotabilityImporter : NSObject <NBImportOperationDelegate> {

	NSMutableDictionary* exportedFiles;
	char _isPresentingController;
	NSMutableArray* _importOperations;
	id<NBOrganizerDataStore> _dataSource;
	NSMutableArray* _controllersToPresent;

}

@property (nonatomic,retain) NSMutableArray * importOperations;                       //@synthesize importOperations=_importOperations - In the implementation block
@property (assign,nonatomic,__weak) id<NBOrganizerDataStore> dataSource;              //@synthesize dataSource=_dataSource - In the implementation block
@property (assign) char isPresentingController;                                       //@synthesize isPresentingController=_isPresentingController - In the implementation block
@property (nonatomic,retain) NSMutableArray * controllersToPresent;                   //@synthesize controllersToPresent=_controllersToPresent - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(int)numPagesForPDFAtPath:(id)arg1 ;
+(id)titleForPDFAtPath:(id)arg1 ;
+(id)importer;
-(void)importDocumentsAtPaths:(id)arg1 importOperation:(id)arg2 ;
-(void)importDocumentAtURL:(id)arg1 importOperation:(id)arg2 ;
-(void)importDocumentsAtURLs:(id)arg1 importOperation:(id)arg2 ;
-(void)addExportedFile:(id)arg1 ;
-(void)importOperation:(id)arg1 finishedUnpackagingWithErrors:(char)arg2 ;
-(void)importOperation:(id)arg1 finishedSavingWithErrors:(id)arg2 ;
-(void)importDocumentsFromDocumentsDirectory;
-(void)setImportOperations:(NSMutableArray *)arg1 ;
-(id)addImportOperation:(id)arg1 withURLs:(id)arg2 ;
-(void)doImportOfDocumentAtURL:(id)arg1 operation:(id)arg2 ;
-(void)presentImportUIForNoteAtURL:(id)arg1 importOperation:(id)arg2 formatDelegate:(Class)arg3 ;
-(void)doImportOfDocumentAtURL:(id)arg1 toExistingNote:(id)arg2 operation:(id)arg3 ;
-(void)handleImportUIResultWithContentsURL:(id)arg1 importActionType:(int)arg2 targetNote:(id)arg3 importOperation:(id)arg4 viewController:(id)arg5 ;
-(id)organizerPickerWithOperation:(id)arg1 formatDelegate:(Class)arg2 contentsURL:(id)arg3 ;
-(void)presentControllers;
-(NSMutableArray *)importOperations;
-(void)removeImportOperation:(id)arg1 ;
-(char)fileWasExportedByNotability:(id)arg1 ;
-(void)importDocumentAtPath:(id)arg1 importOperation:(id)arg2 ;
-(char)isPresentingController;
-(void)setIsPresentingController:(char)arg1 ;
-(NSMutableArray *)controllersToPresent;
-(void)setControllersToPresent:(NSMutableArray *)arg1 ;
-(id)init;
-(void)setDataSource:(id<NBOrganizerDataStore>)arg1 ;
-(void)dealloc;
-(id<NBOrganizerDataStore>)dataSource;
@end

