/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, NSString, NSTimer;

@interface Notability.NIZoomLevelView : UIView {

	 zoomLabel.storage;
	 text;
	 isShowing;
	 isShowingCounter;
	 hideViewTimer;

}

@property (retain,nonatomic) UILabel * zoomLabel; 
@property (copy,nonatomic) NSString * text; 
@property (assign,nonatomic) char isShowing; 
@property (assign,nonatomic) unsigned isShowingCounter; 
@property (retain,nonatomic) NSTimer * hideViewTimer; 
-(UILabel *)zoomLabel;
-(void)setZoomLabel:(UILabel *)arg1 ;
-(unsigned)isShowingCounter;
-(void)setIsShowingCounter:(unsigned)arg1 ;
-(NSTimer *)hideViewTimer;
-(void)setHideViewTimer:(NSTimer *)arg1 ;
-(void)showViewWithDelayed:(char)arg1 ;
-(void)hideViewWithAnimated:(char)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(char)isShowing;
-(void)setIsShowing:(char)arg1 ;
@end

