/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/NBPageManagerTableViewCell.h>

@interface Notability.NBPageManagerIndexStatusCell : NBPageManagerTableViewCell {

	 needsIndexing;
	 indexRunning;
	 indexProgress;
	 indexProgressView;
	 indexLabel;

}

@property (assign,nonatomic) char needsIndexing; 
@property (assign,nonatomic) char indexRunning; 
@property (assign,nonatomic) float indexProgress; 
-(char)needsIndexing;
-(void)setNeedsIndexing:(char)arg1 ;
-(char)indexRunning;
-(void)setIndexRunning:(char)arg1 ;
-(float)indexProgress;
-(void)setIndexProgress:(float)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
@end

