/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>

@interface Notability.NoteIndexingHeaderView : UIView {

	 label;
	 progressView;
	 collapseButton;
	 fullViewButton;
	 animateDisclosureArrow;
	 activityIndicatorView;
	 helpButton;
	 delegate;
	 popoverController;
	 collapsed;
	 modelData;
	 notesToIndex;
	 overallProgress;

}

@property (assign,nonatomic) char animateDisclosureArrow; 
@property (assign,nonatomic) char collapsed; 
@property (assign,nonatomic) double overallProgress; 
+(char)enableProgressView;
+(char)enableCollapse;
-(char)animateDisclosureArrow;
-(void)setAnimateDisclosureArrow:(char)arg1 ;
-(void)dismissHelpPopoverWithAnimated:(char)arg1 ;
-(void)helpAction:(id)arg1 ;
-(void)setOverallProgress:(double)arg1 ;
-(id)init;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(char)collapsed;
-(void)setCollapsed:(char)arg1 ;
-(double)overallProgress;
@end

