/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/HandwritingObjectCurveBuilder.h>

@interface Notability.HandwritingObjectCircleBuilder : HandwritingObjectCurveBuilder {

	 radius;
	 center;
	 _curves;
	 _hasCurrentStroke;

}

@property (assign,nonatomic) float radius; 
@property (assign,nonatomic) CGPoint center; 
@property (readonly,nonatomic) char supportsAnimatedPlayback; 
-(void)cancelStroke;
-(void)closeStroke;
-(void)addControlPointsToStroke:(id)arg1 ;
-(CGPoint)startingPoint;
-(CGPoint)endingPoint;
-(id)currentStroke;
-(char)hasCurrentStroke;
-(char)supportsAnimatedPlayback;
-(id)initWithRadius:(float)arg1 center:(CGPoint)arg2 ;
-(id)init;
-(CGPoint)center;
-(void)setCenter:(CGPoint)arg1 ;
-(void)setRadius:(float)arg1 ;
-(float)radius;
-(void)beginStroke;
@end

