/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:15 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Notability.RecordingsRecovery : NSObject {

	 lock;
	 cachedRecordings;
	 combineQueue;
	 cache;
	 recoveriesInProgress;

}
+(id)shared;
-(void)removeCachedRecordingWithIdentifier:(id)arg1 ;
-(id)recoverRecordingWithIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)recoverRecordingIdentifierForNoteNamed:(id)arg1 ;
-(id)recoverRecordingCreatedDateForNoteNamed:(id)arg1 ;
-(unsigned)recoverRecordingInfoIdForNoteNamed:(id)arg1 ;
-(void)removeRecoverableRecordingForNoteNamed:(id)arg1 ;
-(void)storeRecoverableRecordingWithIdentifier:(id)arg1 noteNamed:(id)arg2 recordingInfoId:(unsigned)arg3 ;
-(id)init;
@end

