/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:13 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>

@protocol NoteCellThumbnailViewDelegate;
@class UILongPressGestureRecognizer, GLThumbnailImageView, NoteCellProgressView, GLAlignedImageView, UIActivityIndicatorView;

@interface NoteCellThumbnailView : UIView {

	id<NoteCellThumbnailViewDelegate> delegate;
	UILongPressGestureRecognizer* longPressGestureRecognizer;
	GLThumbnailImageView* thumbnailImageView;
	NoteCellProgressView* _progressView;
	GLAlignedImageView* _checkmarkView;
	UIActivityIndicatorView* _activityIndicator;
	char _showCheckmark;

}

@property (nonatomic,readonly) GLAlignedImageView * checkmarkView; 
@property (nonatomic,readonly) NoteCellProgressView * progressView; 
@property (nonatomic,readonly) UIActivityIndicatorView * activityIndicator; 
@property (assign,nonatomic,__weak) id<NoteCellThumbnailViewDelegate> delegate; 
@property (assign) char showProgressView; 
@property (assign) float progress; 
@property (assign,nonatomic) char showCheckmark;                                             //@synthesize showCheckmark=_showCheckmark - In the implementation block
-(void)setGestureRecognizerEnabled:(char)arg1 ;
-(void)setShowProgressView:(char)arg1 ;
-(char)showProgressView;
-(void)longPressGestureRecognized;
-(void)resetStateForReuseOrInit;
-(void)setupInitialConstraints;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setImage:(id)arg1 ;
-(void)setDelegate:(id<NoteCellThumbnailViewDelegate>)arg1 ;
-(id<NoteCellThumbnailViewDelegate>)delegate;
-(id)image;
-(CGSize)intrinsicContentSize;
-(void)setProgress:(float)arg1 ;
-(void)prepareForReuse;
-(float)progress;
-(GLAlignedImageView *)checkmarkView;
-(UIActivityIndicatorView *)activityIndicator;
-(NoteCellProgressView *)progressView;
-(char)showCheckmark;
-(void)setShowCheckmark:(char)arg1 ;
@end

