/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@interface OFCharacterScanner : NSObject {

	unsigned rewindMarkOffsets[8];
	unsigned short rewindMarkCount;
	unsigned firstNonASCIIOffset;
	unsigned short* inputBuffer;
	unsigned short* scanLocation;
	unsigned short* scanEnd;
	unsigned inputStringPosition;
	char freeInputBuffer;
	OFCaseConversionBuffer* caseBuffer;

}
+(void)initialize;
-(char)fetchMoreData;
-(char)fetchMoreDataFromString:(id)arg1 ;
-(id)readTokenFragmentWithDelimiterOFCharacterSet:(id)arg1 ;
-(id)readFullTokenWithDelimiterOFCharacterSet:(id)arg1 forceLowercase:(char)arg2 ;
-(id)readFullTokenWithDelimiterOFCharacterSet:(id)arg1 ;
-(unsigned)scanHexadecimalNumberMaximumDigits:(unsigned)arg1 ;
-(char)scanString:(id)arg1 peek:(char)arg2 ;
-(char)fetchMoreDataFromCharacters:(unsigned short*)arg1 length:(unsigned)arg2 offset:(unsigned)arg3 freeWhenDone:(char)arg4 ;
-(void)_rewindCharacterSource;
-(void)setRewindMark;
-(void)rewindToMark;
-(id)readFullTokenWithDelimiters:(id)arg1 forceLowercase:(char)arg2 ;
-(char)scanUpToString:(id)arg1 ;
-(id)readCharacterCount:(unsigned)arg1 ;
-(unsigned)scanUnsignedIntegerMaximumDigits:(unsigned)arg1 ;
-(void)discardRewindMark;
-(unsigned short)peekCharacter;
-(void)skipPeekedCharacter;
-(unsigned short)readCharacter;
-(void)skipCharacters:(unsigned)arg1 ;
-(char)hasScannedNonASCII;
-(char)scanUpToCharacter:(unsigned short)arg1 ;
-(char)scanUpToCharacterInSet:(id)arg1 ;
-(char)scanUpToStringCaseInsensitive:(id)arg1 ;
-(id)readTokenFragmentWithDelimiterCharacter:(unsigned short)arg1 ;
-(id)readTokenFragmentWithDelimiters:(id)arg1 ;
-(id)readFullTokenWithDelimiterCharacter:(unsigned short)arg1 forceLowercase:(char)arg2 ;
-(id)readFullTokenWithDelimiterCharacter:(unsigned short)arg1 ;
-(id)readFullTokenOfSet:(id)arg1 ;
-(id)readFullTokenUpToString:(id)arg1 ;
-(id)readLine;
-(id)readRemainingBufferedCharacters;
-(int)scanIntegerMaximumDigits:(unsigned)arg1 ;
-(char)scanDouble:(double*)arg1 maximumLength:(unsigned)arg2 exponentLength:(unsigned)arg3 ;
-(char)scanStringCaseInsensitive:(id)arg1 peek:(char)arg2 ;
-(id)init;
-(void)dealloc;
-(void)setScanLocation:(unsigned)arg1 ;
-(unsigned)scanLocation;
@end

