/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OUIRTFReaderTestDelegate;
#import <Notability/Notability-Structs.h>
@class NSMutableAttributedString, OFStringScanner, OUIRTFReaderState, NSMutableArray, NSMutableDictionary, OUIRTFListLevel, OUIRTFList, OUIRTFListOverride, NSAttributedString;

@interface OUIRTFReader : NSObject {

	NSMutableAttributedString* _attributedString;
	OFStringScanner* _scanner;
	OUIRTFReaderState* _currentState;
	NSMutableArray* _pushedStates;
	NSMutableArray* _colorTable;
	NSMutableDictionary* _fontTable;
	NSMutableDictionary* _listTable;
	NSMutableDictionary* _listOverrideTable;
	NSMutableArray* _multimediaItems;
	NSMutableDictionary* _currentMultimediaItemDictionary;
	OUIRTFListLevel* _currentListLevel;
	OUIRTFList* _currentList;
	OUIRTFListOverride* _currentListOverride;
	short _colorTableRedComponent;
	short _colorTableGreenComponent;
	short _colorTableBlueComponent;
	id<OUIRTFReaderTestDelegate> _delegate;

}

@property (nonatomic,retain) NSAttributedString * attributedString;              //@synthesize attributedString=_attributedString - In the implementation block
@property (assign,nonatomic) id<OUIRTFReaderTestDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)parseRTFString:(id)arg1 delegate:(id)arg2 ;
+(id)parseRTFDString:(id)arg1 multimediaItems:(id)arg2 delegate:(id)arg3 ;
+(void)_registerKeyword:(id)arg1 action:(id)arg2 ;
+(void)initialize;
-(void)_actionSkipDestination;
-(void)_actionSetUnicodeSkipCount:(int)arg1 ;
-(void)_actionInsertUnicodeCharacter:(int)arg1 ;
-(void)_actionInsertPageBreak;
-(void)_actionBackgroundColor:(int)arg1 ;
-(void)_actionForegroundColor:(int)arg1 ;
-(void)_actionBold:(int)arg1 ;
-(void)_actionItalic:(int)arg1 ;
-(void)_actionFontSize:(int)arg1 ;
-(void)_actionFontNumber:(int)arg1 ;
-(void)_actionUnderline:(int)arg1 ;
-(void)_actionUnderlineStyle:(int)arg1 ;
-(void)_actionNewParagraph;
-(void)_actionParagraphDefault;
-(void)_actionParagraphAlignCenter;
-(void)_actionParagraphAlignJustify;
-(void)_actionParagraphAlignLeft;
-(void)_actionParagraphAlignRight;
-(void)_actionParagraphFirstLineIndent:(int)arg1 ;
-(void)_actionParagraphLeftIndent:(int)arg1 ;
-(void)_actionParagraphRightIndent:(int)arg1 ;
-(void)_actionReadListTable;
-(void)_actionAddListTableEntry;
-(void)_actionListTableID:(int)arg1 ;
-(void)_actionListTableTemplateID:(int)arg1 ;
-(void)_actionListReadLevel;
-(void)_actionListLevelStartAt:(int)arg1 ;
-(void)_actionListLevelStyle:(int)arg1 ;
-(void)_actionReadListOverrideTable;
-(void)_actionListOverride;
-(void)_actionListOverrideCount:(int)arg1 ;
-(void)_actionListOverrideIndex:(int)arg1 ;
-(void)_actionListSetLevel:(int)arg1 ;
-(void)_actionReadColorTable;
-(void)_actionReadColorTableRedValue:(int)arg1 ;
-(void)_actionReadColorTableGreenValue:(int)arg1 ;
-(void)_actionReadColorTableBlueValue:(int)arg1 ;
-(void)_actionReadFontTable;
-(void)_actionReadFontCharacterSet:(int)arg1 ;
-(void)_actionRQuote;
-(void)_actionLQuote;
-(void)_actionRDoubleQuote;
-(void)_actionLDoubleQuote;
-(void)_actionReadMultimediaItem;
-(void)_actionReadMultimediaItemWidth:(int)arg1 ;
-(void)_actionReadMultimediaItemHeight:(int)arg1 ;
-(id)_initWithRTFString:(id)arg1 multimediaItems:(id)arg2 delegate:(id)arg3 ;
-(void)_parseRTF;
-(CGColorRef)_newCurrentColorTableCGColor;
-(void)_resetCurrentColorTableColor;
-(void)_addColorTableEntry;
-(void)_parseRTFGroupWithSemicolonAction:(id)arg1 ;
-(void)_addFontTableEntry;
-(void)_closeAndAddListTableEntry;
-(void)_parseRTFGroupWithPrePopStateAction:(id)arg1 ;
-(void)_closeAndAddListLevel;
-(void)_closeAndAddListTableOverrideEntry;
-(void)_parseControlSymbol;
-(void)_parseKeyword;
-(void)_popRTFState;
-(CGColorRef)_colorAtIndex:(int)arg1 ;
-(unsigned long)_fontEncodingAtIndex:(int)arg1 ;
-(void)_actionAppendString:(id)arg1 ;
-(void)_handleKeyword:(id)arg1 ;
-(void)_handleKeyword:(id)arg1 parameter:(int)arg2 ;
-(void)_parseHexByte;
-(void)_parseRTFGroupWithSemicolonAction:(id)arg1 prePopStateAction:(id)arg2 ;
-(void)_pushRTFState;
-(id)_fontNameAtIndex:(int)arg1 ;
-(void)setDelegate:(id<OUIRTFReaderTestDelegate>)arg1 ;
-(void)dealloc;
-(id<OUIRTFReaderTestDelegate>)delegate;
-(void)setAttributedString:(NSAttributedString *)arg1 ;
-(NSAttributedString *)attributedString;
@end

