/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/OUIRTFReaderSelectorAction.h>

@interface OUIRTFReaderSelectorActionIntParam : OUIRTFReaderSelectorAction {

	/*function pointer*/void* _implementation;
	int _defaultValue;
	char _forceValue;

}
-(id)initWithSelector:(SEL)arg1 value:(int)arg2 ;
-(void)performActionWithParser:(id)arg1 ;
-(void)performActionWithParser:(id)arg1 parameter:(int)arg2 ;
-(id)initWithSelector:(SEL)arg1 defaultValue:(int)arg2 ;
-(id)initWithSelector:(SEL)arg1 ;
@end

