/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/DrawObject.h>

@class NSMutableArray;

@interface PaintObject : DrawObject {

	NSMutableArray* strokesArray;
	NSMutableArray* currentStroke;
	NSMutableArray* deletedStrokesArray;

}

@property (nonatomic,retain) NSMutableArray * strokesArray; 
-(void)drawWithContext:(id)arg1 ;
-(void)setDrawingParametersForContext:(id)arg1 ;
-(int)pathDrawingMode;
-(CGRect)handleEvent:(id)arg1 withView:(id)arg2 converter:(id)arg3 offset:(CGPoint)arg4 ;
-(void)cancelStroke;
-(CGAffineTransform)transformToMapSrcRect:(CGRect)arg1 toDestRect:(CGRect)arg2 ;
-(void)redoStroke;
-(void)undoStroke;
-(void)setStrokesArray:(NSMutableArray *)arg1 ;
-(NSMutableArray *)strokesArray;
-(CGRect)computeBoundingBox;
-(CGPathRef)pathForPointArray:(id)arg1 ;
-(void)endStroke:(id)arg1 ;
-(id)vectorizedArrayFromPoints:(id)arg1 withConverter:(id)arg2 ;
-(void)recompute;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)addPoint:(CGPoint)arg1 ;
-(void)createPath;
-(void)beginStroke;
@end

