/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@protocol PDFFileCompatibilityDelegate, NBNoteDocumentContentSource;
@class _TtC10Notability19GLPDFSharedDocument, NSArray, NSString, PDFDocumentPool, NBNoteDocument;

@interface PDFFile : NSObject <NSCoding> {

	_TtC10Notability19GLPDFSharedDocument* _sharedPdfDocument;
	NSArray* _pageNumbers;
	NSString* _pdfFileName;
	id<PDFFileCompatibilityDelegate> _compatiblityDelegate;
	id<NBNoteDocumentContentSource> _contentSource;
	NSArray* _highlights;
	PDFDocumentPool* _documentPool;
	int _contentBoxVersion;
	NSArray* _pagesMetadata;

}

@property (retain) NSString * pdfFileName;                                                 //@synthesize pdfFileName=_pdfFileName - In the implementation block
@property (retain) _TtC10Notability19GLPDFSharedDocument * sharedPdfDocument;              //@synthesize sharedPdfDocument=_sharedPdfDocument - In the implementation block
@property (retain) PDFDocumentPool * documentPool;                                         //@synthesize documentPool=_documentPool - In the implementation block
@property (assign) int contentBoxVersion;                                                  //@synthesize contentBoxVersion=_contentBoxVersion - In the implementation block
@property (retain) NSArray * pagesMetadata;                                                //@synthesize pagesMetadata=_pagesMetadata - In the implementation block
@property (readonly) NSArray * columns; 
@property (retain) NSArray * highlights;                                                   //@synthesize highlights=_highlights - In the implementation block
@property (readonly) NSArray * pageNumbers;                                                //@synthesize pageNumbers=_pageNumbers - In the implementation block
@property (__weak) id<PDFFileCompatibilityDelegate> compatiblityDelegate;                  //@synthesize compatiblityDelegate=_compatiblityDelegate - In the implementation block
@property (__weak) id<NBNoteDocumentContentSource> contentSource;                          //@synthesize contentSource=_contentSource - In the implementation block
@property (readonly) NBNoteDocument * noteDocument; 
@property (readonly) int numberOfLoadedPages; 
@property (readonly) int numberOfPages; 
+(id)highlightsFromCopyablePageContents:(id)arg1 ;
+(id)pdfPageNumbersFromCopyablePageContents:(id)arg1 ;
+(char)areSourcePDFColumns:(id)arg1 andDestinationPDFColumns:(id)arg2 equalEnoughForHighlight:(id)arg3 forPDFPageNumber:(unsigned)arg4 ;
-(NBNoteDocument *)noteDocument;
-(id)initWithPDFFileName:(id)arg1 ;
-(void)setCompatiblityDelegate:(id<PDFFileCompatibilityDelegate>)arg1 ;
-(void)setContentSource:(id<NBNoteDocumentContentSource>)arg1 ;
-(NSString *)pdfFileName;
-(void)documentContentAccessWillBeDisabled;
-(id<NBNoteDocumentContentSource>)contentSource;
-(void)releaseDocument;
-(void)_memoryWarning;
-(void)setContentBoxVersion:(int)arg1 ;
-(id<PDFFileCompatibilityDelegate>)compatiblityDelegate;
-(int)contentBoxVersion;
-(NSArray *)highlights;
-(void)drawPage:(int)arg1 inContext:(id)arg2 poolSize:(int)arg3 ;
-(_TtC10Notability19GLPDFSharedDocument *)sharedPdfDocument;
-(PDFDocumentPool *)documentPool;
-(void)setDocumentPool:(PDFDocumentPool *)arg1 ;
-(NSArray *)pagesMetadata;
-(void)setPagesMetadata:(NSArray *)arg1 ;
-(void)_loadPagesMetadataIfNecessary;
-(id)columnsForPage:(int)arg1 ;
-(void)setHighlights:(NSArray *)arg1 ;
-(void)setSharedPdfDocument:(_TtC10Notability19GLPDFSharedDocument *)arg1 ;
-(void)drawPage:(int)arg1 inContext:(id)arg2 ;
-(int)numberOfLoadedPages;
-(id)getPageMetadata:(int)arg1 ;
-(id)serializedPDFFileWrapper;
-(id)pageRectArraysForSearchString:(id)arg1 onPage:(int)arg2 ;
-(id)highlightsFromSelectionsForPDFPageNumbers:(id)arg1 newHighlightColor:(id)arg2 ;
-(void)replaceHighlights:(id)arg1 withHighlights:(id)arg2 ;
-(id)copyablePageContentsOfPartialHighlightsForPages:(id)arg1 ;
-(NSArray *)pageNumbers;
-(void)setPdfFileName:(NSString *)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(id)description;
-(int)numberOfPages;
-(NSArray *)columns;
@end

