/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class NSArray, PDFKittenFontDescriptor, NSString, NSDictionary;

@interface PDFKittenFont : NSObject {

	NSArray* _toUnicodeMaps;
	PDFKittenFontDescriptor* _fontDescriptor;
	NSString* _baseFontName;
	float _widthOfSpace;
	NSDictionary* _widths;

}

@property (assign,nonatomic) float widthOfSpace;                                      //@synthesize widthOfSpace=_widthOfSpace - In the implementation block
@property (nonatomic,readonly) NSDictionary * widths;                                 //@synthesize widths=_widths - In the implementation block
@property (nonatomic,retain) NSArray * toUnicodeMaps;                                 //@synthesize toUnicodeMaps=_toUnicodeMaps - In the implementation block
@property (nonatomic,readonly) PDFKittenFontDescriptor * fontDescriptor;              //@synthesize fontDescriptor=_fontDescriptor - In the implementation block
@property (nonatomic,readonly) float minY; 
@property (nonatomic,readonly) float maxY; 
@property (nonatomic,readonly) CGSize fontMatrix; 
@property (nonatomic,readonly) NSString * baseFontName;                               //@synthesize baseFontName=_baseFontName - In the implementation block
+(id)fontWithDictionary:(CGPDFDictionaryRef)arg1 ;
-(float)widthOfGlyph:(unsigned short)arg1 unicodeCharacters:(id)arg2 ;
-(id)widthsWithFontDictionary:(CGPDFDictionaryRef)arg1 ;
-(id)initWithFontDictionary:(CGPDFDictionaryRef)arg1 ;
-(void)setToUnicodeMaps:(NSArray *)arg1 ;
-(NSArray *)toUnicodeMaps;
-(id)unicodeStringForCID:(unsigned short)arg1 ;
-(id)stringWithPDFString:(CGPDFStringRef)arg1 ;
-(unsigned short)cidForUnicodeCharacter:(unsigned short)arg1 ;
-(NSString *)baseFontName;
-(id)fontDescriptorWithFontDictionary:(CGPDFDictionaryRef)arg1 ;
-(CGSize)fontMatrix;
-(float)widthOfSpace;
-(void)setWidthOfSpace:(float)arg1 ;
-(id)description;
-(PDFKittenFontDescriptor *)fontDescriptor;
-(NSDictionary *)widths;
-(float)maxY;
-(float)minY;
@end

