/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, PDFKittenRenderingState;

@interface PDFKittenRenderingStateStack : NSObject {

	NSMutableArray* _stack;

}

@property (nonatomic,retain) NSMutableArray * stack;                                     //@synthesize stack=_stack - In the implementation block
@property (nonatomic,readonly) PDFKittenRenderingState * topRenderingState; 
-(PDFKittenRenderingState *)topRenderingState;
-(void)pushCopyOfTopRenderingState;
-(id)popRenderingState;
-(void)_populateRootRenderStateIfNecessary;
-(void)setStack:(NSMutableArray *)arg1 ;
-(NSMutableArray *)stack;
-(id)init;
@end

