/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@class PDFKittenRenderingStateStack, NSMutableArray;

@interface PDFKittenScanner : NSObject {

	PDFKittenRenderingStateStack* _renderingStateStack;
	CGPDFOperatorTableRef _operatorTable;
	NSMutableArray* _streamContexts;
	NSMutableArray* _rows;

}

@property (nonatomic,readonly) PDFKittenRenderingStateStack * renderingStateStack;              //@synthesize renderingStateStack=_renderingStateStack - In the implementation block
@property (nonatomic,readonly) CGPDFOperatorTableRef operatorTable;                             //@synthesize operatorTable=_operatorTable - In the implementation block
@property (nonatomic,retain) NSMutableArray * streamContexts;                                   //@synthesize streamContexts=_streamContexts - In the implementation block
@property (nonatomic,retain) NSMutableArray * rows;                                             //@synthesize rows=_rows - In the implementation block
-(PDFKittenRenderingStateStack *)renderingStateStack;
-(id)currentRenderingState;
-(NSMutableArray *)streamContexts;
-(id)fontCollection;
-(CGPDFOperatorTableRef)operatorTable;
-(id)scanPage:(CGPDFPageRef)arg1 ;
-(void)didEndPDFString:(id)arg1 ;
-(void)setStreamContexts:(NSMutableArray *)arg1 ;
-(id)init;
-(void)dealloc;
-(NSMutableArray *)rows;
-(void)setRows:(NSMutableArray *)arg1 ;
-(id)currentFont;
@end

