/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:12 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/ThumbnailCacheOperationsManager.h>

@class NSMutableArray, NSOperationQueue, NSString;

@interface ProformanceOperationQueueManager : NSObject <ThumbnailCacheOperationsManager> {

	char _isSchedulingBatchOperations;
	NSMutableArray* _batchOperations;
	NSOperationQueue* _operationQueue;

}

@property (retain) NSMutableArray * batchOperations;                        //@synthesize batchOperations=_batchOperations - In the implementation block
@property (retain) NSOperationQueue * operationQueue;                       //@synthesize operationQueue=_operationQueue - In the implementation block
@property (assign,nonatomic) char isSchedulingBatchOperations;              //@synthesize isSchedulingBatchOperations=_isSchedulingBatchOperations - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedInstance;
-(void)beginBatchOperationCreation;
-(void)commitBatchOperations;
-(void)setIsSchedulingBatchOperations:(char)arg1 ;
-(void)setBatchOperations:(NSMutableArray *)arg1 ;
-(NSMutableArray *)batchOperations;
-(char)isSchedulingBatchOperations;
-(void)thumbnailCache:(id)arg1 addOperation:(id)arg2 ;
-(id)init;
-(void)setOperationQueue:(NSOperationQueue *)arg1 ;
-(NSOperationQueue *)operationQueue;
-(void)addOperation:(id)arg1 ;
@end

