/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTBorderStyle : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(void)Destroy;
-(double)GetHR;
-(void)SetHR:(double)arg1 ;
-(double)GetVR;
-(void)SetVR:(double)arg1 ;
-(double)GetWidth;
-(void)SetWidth:(double)arg1 ;
-(id)GetDash;
-(void)SetDash:(id)arg1 ;
-(id)initWithS:(int)arg1 b_width:(double)arg2 b_hr:(double)arg3 b_vr:(double)arg4 ;
-(id)initWithS:(int)arg1 b_width:(double)arg2 b_hr:(double)arg3 b_vr:(double)arg4 b_dash:(id)arg5 ;
-(void)SetStyle:(int)arg1 ;
-(int)GetStyle;
-(void)dealloc;
@end

