/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:17 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@interface PTConvert : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
+(id)WordToPDFConversion:(id)arg1 in_filename:(id)arg2 options:(id)arg3 ;
+(void)FromXpsWithFilename:(id)arg1 in_filename:(id)arg2 ;
+(void)FromXpsWithBuffer:(id)arg1 buf:(id)arg2 buf_sz:(unsigned long)arg3 ;
+(void)FromEmf:(id)arg1 in_filename:(id)arg2 ;
+(void)FromText:(id)arg1 in_filename:(id)arg2 in_options:(id)arg3 ;
+(void)ToEmfWithPDFDoc:(id)arg1 in_filename:(id)arg2 ;
+(void)ToEmfWithPage:(id)arg1 in_filename:(id)arg2 ;
+(void)ToSvg:(id)arg1 in_filename:(id)arg2 ;
+(void)ToSvgWithPDFDoc:(id)arg1 in_filename:(id)arg2 in_options:(id)arg3 ;
+(void)ToSvgWithPage:(id)arg1 in_filename:(id)arg2 in_options:(id)arg3 ;
+(void)ToXps:(id)arg1 in_filename:(id)arg2 ;
+(void)ToXpsWithPDFDoc:(id)arg1 in_filename:(id)arg2 options:(id)arg3 ;
+(void)ToXpsWithFilename:(id)arg1 in_outputFilename:(id)arg2 options:(id)arg3 ;
+(void)ToXod:(id)arg1 out_filename:(id)arg2 ;
+(void)ToXodWithFilename:(id)arg1 out_filename:(id)arg2 options:(id)arg3 ;
+(void)ToXodWithPDFDoc:(id)arg1 out_filename:(id)arg2 options:(id)arg3 ;
+(void)ToHtml:(id)arg1 out_path:(id)arg2 ;
+(void)ToHtmlWithFilename:(id)arg1 out_path:(id)arg2 options:(id)arg3 ;
+(void)ToHtmlWithPDFDoc:(id)arg1 out_path:(id)arg2 options:(id)arg3 ;
+(void)ToEpub:(id)arg1 out_path:(id)arg2 ;
+(void)ToEpubWithFilename:(id)arg1 out_path:(id)arg2 html_options:(id)arg3 epub_options:(id)arg4 ;
+(void)ToEpubWithPDFDoc:(id)arg1 out_path:(id)arg2 html_options:(id)arg3 epub_options:(id)arg4 ;
+(void)ToTiff:(id)arg1 out_path:(id)arg2 ;
+(id)ToXodWithFilenameToStream:(id)arg1 options:(id)arg2 ;
+(id)ToXodWithPDFDocToStream:(id)arg1 options:(id)arg2 ;
+(id)ToXodWithMonitor:(id)arg1 ;
+(id)ToXodWithMonitorAndOptions:(id)arg1 options:(id)arg2 ;
+(void)WordToPDF:(id)arg1 in_filename:(id)arg2 options:(id)arg3 ;
+(void)OfficeToPDF:(id)arg1 in_filename:(id)arg2 options:(id)arg3 ;
+(id)StreamingPDFConversionWithDoc:(id)arg1 in_filename:(id)arg2 options:(id)arg3 ;
+(id)StreamingPDFConversion:(id)arg1 options:(id)arg2 ;
+(void)ToPdf:(id)arg1 in_filename:(id)arg2 ;
+(char)RequiresPrinter:(id)arg1 ;
+(id)setupConversionWebView:(CGSize)arg1 pdfFile:(id)arg2 completion:(/*^block*/id)arg3 ;
+(void)convertOfficeToPDFWithURL:(id)arg1 paperSize:(CGSize)arg2 completion:(/*^block*/id)arg3 ;
+(void)convertHTMLStringToPDF:(id)arg1 baseURL:(id)arg2 paperSize:(CGSize)arg3 completion:(/*^block*/id)arg4 ;
+(void)convertOfficeToPDF:(id)arg1 paperSize:(CGSize)arg2 completion:(/*^block*/id)arg3 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(void)dealloc;
@end

