/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/TRN_date.h>

@interface PTDate : TRN_date
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(id)initWithD:(id)arg1 ;
-(char)Update:(id)arg1 ;
-(char)IsValid;
-(void)Attach:(id)arg1 ;
-(void)SetCurrentTime;
-(unsigned short)GetYear;
-(unsigned char)GetMonth;
-(unsigned char)GetDay;
-(unsigned char)GetHour;
-(unsigned char)GetMinute;
-(unsigned char)GetSecond;
-(unsigned char)GetUT;
-(unsigned char)GetUTHour;
-(unsigned char)GetUTMin;
-(id)init;
-(void)dealloc;
-(id)initWithYear:(unsigned short)arg1 month:(char)arg2 day:(char)arg3 hour:(char)arg4 minute:(char)arg5 second:(char)arg6 ;
@end

