/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTGState : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
+(int)GetRenderingIntentType:(id)arg1 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(void)Concat:(double)arg1 b:(double)arg2 c:(double)arg3 d:(double)arg4 h:(double)arg5 v:(double)arg6 ;
-(id)GetTransform;
-(id)GetStrokeColorSpace;
-(id)GetFillColorSpace;
-(id)GetStrokeColor;
-(id)GetStrokePattern;
-(id)GetFillColor;
-(id)GetFillPattern;
-(double)GetFlatness;
-(int)GetLineCap;
-(int)GetLineJoin;
-(double)GetLineWidth;
-(double)GetMiterLimit;
-(id)GetDashes;
-(double)GetPhase;
-(double)GetCharSpacing;
-(double)GetWordSpacing;
-(double)GetHorizontalScale;
-(double)GetLeading;
-(id)GetFont;
-(double)GetFontSize;
-(int)GetTextRenderMode;
-(double)GetTextRise;
-(char)IsTextKnockout;
-(int)GetRenderingIntent;
-(int)GetBlendMode;
-(double)GetFillOpacity;
-(double)GetStrokeOpacity;
-(char)GetAISFlag;
-(id)GetSoftMask;
-(id)GetSoftMaskTransform;
-(char)GetStrokeOverprint;
-(char)GetFillOverprint;
-(int)GetOverprintMode;
-(char)GetAutoStrokeAdjust;
-(double)GetSmoothnessTolerance;
-(id)GetTransferFunct;
-(id)GetBlackGenFunct;
-(id)GetUCRFunct;
-(id)GetHalftone;
-(void)SetTransformWithMatrix:(id)arg1 ;
-(void)SetTransform:(double)arg1 b:(double)arg2 c:(double)arg3 d:(double)arg4 h:(double)arg5 v:(double)arg6 ;
-(void)ConcatWithMatrix:(id)arg1 ;
-(void)SetStrokeColorSpace:(id)arg1 ;
-(void)SetFillColorSpace:(id)arg1 ;
-(void)SetStrokeColorWithColorPt:(id)arg1 ;
-(void)SetStrokeColorWithPattern:(id)arg1 ;
-(void)SetStrokeColorWithPatternAndColorPt:(id)arg1 c:(id)arg2 ;
-(void)SetFillColorWithColorPt:(id)arg1 ;
-(void)SetFillColorWithPattern:(id)arg1 ;
-(void)SetFillColorWithPatternAndColorPt:(id)arg1 c:(id)arg2 ;
-(void)SetFlatness:(double)arg1 ;
-(void)SetLineCap:(int)arg1 ;
-(void)SetLineJoin:(int)arg1 ;
-(void)SetLineWidth:(double)arg1 ;
-(void)SetMiterLimit:(double)arg1 ;
-(void)SetDashPattern:(id)arg1 phase:(double)arg2 ;
-(void)SetCharSpacing:(double)arg1 ;
-(void)SetWordSpacing:(double)arg1 ;
-(void)SetHorizontalScale:(double)arg1 ;
-(void)SetLeading:(double)arg1 ;
-(void)SetFont:(id)arg1 font_sz:(double)arg2 ;
-(void)SetTextRenderMode:(int)arg1 ;
-(void)SetTextRise:(double)arg1 ;
-(void)SetTextKnockout:(char)arg1 ;
-(void)SetRenderingIntent:(int)arg1 ;
-(void)SetBlendMode:(int)arg1 ;
-(void)SetFillOpacity:(double)arg1 ;
-(void)SetStrokeOpacity:(double)arg1 ;
-(void)SetAISFlag:(char)arg1 ;
-(void)SetSoftMask:(id)arg1 ;
-(void)SetStrokeOverprint:(char)arg1 ;
-(void)SetFillOverprint:(char)arg1 ;
-(void)SetOverprintMode:(int)arg1 ;
-(void)SetAutoStrokeAdjust:(char)arg1 ;
-(void)SetSmoothnessTolerance:(double)arg1 ;
-(void)SetBlackGenFunct:(id)arg1 ;
-(void)SetUCRFunct:(id)arg1 ;
-(void)SetTransferFunct:(id)arg1 ;
-(void)SetHalftone:(id)arg1 ;
-(id)init;
-(void)dealloc;
@end

