/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:17 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTHighlight : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(void)setPage_num:(int)arg1 ;
-(int)getPage_num;
-(int)getPosition;
-(int)getLength;
-(id)initWithPg:(int)arg1 pos:(int)arg2 len:(int)arg3 ;
-(id)init;
-(void)dealloc;
-(void)setPosition:(int)arg1 ;
-(void)setLength:(int)arg1 ;
@end

