/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTHTML2PDF : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
+(void)SetModulePath:(id)arg1 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(void)Destroy;
-(void)SetDPI:(int)arg1 ;
-(void)InsertFromURL:(id)arg1 ;
-(void)InsertFromURLWithSettings:(id)arg1 settings:(id)arg2 ;
-(void)InsertFromHtmlString:(id)arg1 ;
-(void)InsertFromHtmlStringWithSettings:(id)arg1 settings:(id)arg2 ;
-(void)InsertTOC;
-(void)InsertTOCWithSettings:(id)arg1 ;
-(char)Convert:(id)arg1 ;
-(int)GetHTTPErrorCode;
-(void)SetQuiet:(char)arg1 ;
-(id)GetLog;
-(void)SetPaperSize:(id)arg1 ;
-(void)SetPaperSizeWithWidthAndHeight:(id)arg1 height:(id)arg2 ;
-(void)SetLandscape:(char)arg1 ;
-(void)SetOutline:(char)arg1 depth:(int)arg2 ;
-(void)DumpOutline:(id)arg1 ;
-(void)SetPDFCompression:(char)arg1 ;
-(void)SetMargins:(id)arg1 bottom:(id)arg2 left:(id)arg3 right:(id)arg4 ;
-(void)SetImageDPI:(int)arg1 ;
-(void)SetImageQuality:(int)arg1 ;
-(void)SetCookieJar:(id)arg1 ;
-(id)init;
-(void)dealloc;
@end

