/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTImage : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
+(id)CreateWithFile:(id)arg1 filename:(id)arg2 encoder_hints:(id)arg3 ;
+(id)Create:(id)arg1 filename:(id)arg2 ;
+(id)CreateWithData:(id)arg1 buf:(id)arg2 buf_size:(unsigned long)arg3 width:(int)arg4 height:(int)arg5 bpc:(int)arg6 color_space:(id)arg7 encoder_hints:(id)arg8 ;
+(id)CreateWithFilterData:(id)arg1 image_data:(id)arg2 width:(int)arg3 height:(int)arg4 bpc:(int)arg5 color_space:(id)arg6 encoder_hints:(id)arg7 ;
+(id)CreateWithDataSimple:(id)arg1 buf:(id)arg2 buf_size:(unsigned long)arg3 encoder_hints:(id)arg4 ;
+(id)CreateWithFilterDataSimple:(id)arg1 image_data:(id)arg2 encoder_hints:(id)arg3 ;
+(id)CreateImageMaskWithBuffer:(id)arg1 buf:(id)arg2 buf_size:(unsigned long)arg3 width:(int)arg4 height:(int)arg5 encoder_hints:(id)arg6 ;
+(id)CreateImageMask:(id)arg1 buf:(id)arg2 buf_size:(unsigned long)arg3 width:(int)arg4 height:(int)arg5 ;
+(id)CreateImageMaskWithStream:(id)arg1 image_data:(id)arg2 width:(int)arg3 height:(int)arg4 encoder_hints:(id)arg5 ;
+(id)CreateSoftMaskWithBuffer:(id)arg1 buf:(id)arg2 buf_size:(unsigned long)arg3 width:(int)arg4 height:(int)arg5 bpc:(int)arg6 encoder_hints:(id)arg7 ;
+(id)CreateSoftMask:(id)arg1 buf:(id)arg2 buf_size:(unsigned long)arg3 width:(int)arg4 height:(int)arg5 bpc:(int)arg6 ;
+(id)CreateSoftMaskWithStream:(id)arg1 image_data:(id)arg2 width:(int)arg3 height:(int)arg4 bpc:(int)arg5 encoder_hints:(id)arg6 ;
+(id)CreateWithStreamAndFormat:(id)arg1 image_data:(id)arg2 width:(int)arg3 height:(int)arg4 bpc:(int)arg5 color_space:(id)arg6 input_format:(int)arg7 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(char)IsValid;
-(id)GetSDFObj;
-(id)GetImageData;
-(int)GetImageDataSize;
-(id)GetImageColorSpace;
-(int)GetImageWidth;
-(int)GetImageHeight;
-(id)GetDecodeArray;
-(int)GetBitsPerComponent;
-(char)IsImageMask;
-(char)IsImageInterpolate;
-(id)GetMask;
-(void)SetMaskWithImage:(id)arg1 ;
-(void)SetMaskWithColor:(id)arg1 ;
-(int)GetImageRenderingIntent;
-(int)ExportToFile:(id)arg1 ;
-(int)ExportToStream:(id)arg1 ;
-(void)ExportAsTiffFile:(id)arg1 ;
-(void)ExportAsTiffStream:(id)arg1 ;
-(void)ExportAsPngFile:(id)arg1 ;
-(void)ExportAsPngStream:(id)arg1 ;
-(id)GetSoftMask;
-(void)SetSoftMask:(id)arg1 ;
-(int)GetComponentNum;
-(id)initWithImage_xobject:(id)arg1 ;
-(void)dealloc;
@end

