/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/PTMarkup.h>

@interface PTInk : PTMarkup
+(id)Create:(id)arg1 pos:(id)arg2 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(int)GetPathCount;
-(int)GetPointCount:(unsigned)arg1 ;
-(id)GetPoint:(unsigned)arg1 pointindex:(unsigned)arg2 ;
-(void)SetPoint:(unsigned)arg1 pointindex:(unsigned)arg2 pt:(id)arg3 ;
-(char)Erase:(id)arg1 pt2:(id)arg2 width:(double)arg3 ;
-(id)initWithD:(id)arg1 ;
-(id)initWithAnn:(id)arg1 ;
-(id)init;
-(void)dealloc;
@end

