/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/PTMarkup.h>

@interface PTLineAnnot : PTMarkup
+(id)Create:(id)arg1 pos:(id)arg2 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(id)initWithD:(id)arg1 ;
-(id)initWithAnn:(id)arg1 ;
-(id)GetStartPoint;
-(void)SetStartPoint:(id)arg1 ;
-(id)GetEndPoint;
-(void)SetEndPoint:(id)arg1 ;
-(int)GetStartStyle;
-(void)SetStartStyle:(int)arg1 ;
-(int)GetEndStyle;
-(void)SetEndStyle:(int)arg1 ;
-(double)GetLeaderLineLength;
-(void)SetLeaderLineLength:(double)arg1 ;
-(double)GetLeaderLineExtensionLength;
-(void)SetLeaderLineExtensionLength:(double)arg1 ;
-(char)GetShowCaption;
-(void)SetShowCaption:(char)arg1 ;
-(int)GetIntentType;
-(void)SetIntentType:(int)arg1 ;
-(double)GetLeaderLineOffset;
-(void)SetLeaderLineOffset:(double)arg1 ;
-(int)GetCaptionPosition;
-(void)SetCaptionPosition:(int)arg1 ;
-(double)GetTextHOffset;
-(void)SetTextHOffset:(double)arg1 ;
-(double)GetTextVOffset;
-(void)SetTextVOffset:(double)arg1 ;
-(id)init;
-(void)dealloc;
@end

