/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:17 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/PTAnnot.h>

@interface PTLink : PTAnnot
+(id)Create:(id)arg1 pos:(id)arg2 ;
+(id)CreateWithAction:(id)arg1 pos:(id)arg2 action:(id)arg3 ;
+(id)GetNormalizedUrl:(id)arg1 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(id)initWithD:(id)arg1 ;
-(id)initWithAnn:(id)arg1 ;
-(int)GetHighlightingMode;
-(void)SetHighlightingMode:(int)arg1 ;
-(id)GetAction;
-(void)SetAction:(id)arg1 ;
-(void)RemoveAction;
-(int)GetQuadPointCount;
-(id)GetQuadPoint:(int)arg1 ;
-(void)SetQuadPoint:(int)arg1 qp:(id)arg2 ;
-(id)init;
-(void)dealloc;
@end

