/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:17 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/PTFilter.h>

@interface PTMappedFile : PTFilter
+(char)Equivalent:(id)arg1 ph2:(id)arg2 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(unsigned long)FileSize;
-(void)dealloc;
-(id)initWithFilename:(id)arg1 ;
-(char)isEqualTo:(id)arg1 ;
@end

