/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:17 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTPDFACompliance : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
+(id)GetPDFAErrorMessage:(int)arg1 ;
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(void)Destroy;
-(void)SaveAsFile:(id)arg1 linearized:(char)arg2 ;
-(void)SaveAs:(id)arg1 ;
-(id)SaveAsMemBuf:(char)arg1 ;
-(unsigned long)GetErrorCount;
-(int)GetError:(unsigned long)arg1 ;
-(unsigned long)GetRefObjCount:(int)arg1 ;
-(unsigned long)GetRefObj:(int)arg1 err_idx:(unsigned long)arg2 ;
-(id)initWithConvert:(char)arg1 file_path:(id)arg2 password:(id)arg3 conf:(int)arg4 exceptions:(int)arg5 num_exceptions:(int)arg6 max_ref_objs:(int)arg7 first_stop:(char)arg8 ;
-(id)initWithConvert:(char)arg1 file_path:(id)arg2 password:(id)arg3 conf:(int)arg4 exceptions:(int)arg5 num_exceptions:(int)arg6 max_ref_objs:(int)arg7 ;
-(id)initWithConvert:(char)arg1 buf:(id)arg2 buf_size:(unsigned long)arg3 password:(id)arg4 conf:(int)arg5 exceptions:(int)arg6 num_exceptions:(int)arg7 max_ref_objs:(int)arg8 first_stop:(char)arg9 ;
-(void)dealloc;
@end

