/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTPDFDocViewPrefs : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(id)initWithTr:(id)arg1 ;
-(void)SetInitialPage:(id)arg1 ;
-(void)SetPageMode:(int)arg1 ;
-(int)GetPageMode;
-(void)SetLayoutMode:(int)arg1 ;
-(int)GetLayoutMode;
-(void)SetPref:(int)arg1 value:(char)arg2 ;
-(char)GetPref:(int)arg1 ;
-(void)SetNonFullScreenPageMode:(int)arg1 ;
-(int)GetNonFullScreenPageMode;
-(void)SetDirection:(char)arg1 ;
-(char)GetDirection;
-(void)SetViewArea:(int)arg1 ;
-(int)GetViewArea;
-(void)SetViewClip:(int)arg1 ;
-(int)GetViewClip;
-(void)SetPrintArea:(int)arg1 ;
-(int)GetPrintArea;
-(void)SetPrintClip:(int)arg1 ;
-(int)GetPrintClip;
-(id)GetSDFObj;
-(void)dealloc;
@end

