/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Notability/Notability-Structs.h>
@interface PTPDFViewIOSCpp : NSObject {

	auto_ptr<pdftron::PDF::PDFDoc>* m_doc_ptr;
	PDFView* m_cpp_pdf_view;
	id delegate;
	char _invalidated;

}
-(void)JavascriptCallback:(const char*)arg1 json:(const char*)arg2 ;
-(void)GetThumbAsync:(int)arg1 ;
-(id)GetThumbInCache:(int)arg1 ;
-(void)FindTextCallback:(char)arg1 withSelection:(void*)arg2 ;
-(id)GetQuadsFromSelection:(id)arg1 ;
-(void)softInvalidate;
-(id)initWithPdfView:(void*)arg1 ;
-(void)setDoc:(id)arg1 ;
-(char)SetZoomX:(int)arg1 Y:(int)arg2 Zoom:(double)arg3 ;
-(id)GetRectsOnCanvas:(int)arg1 ;
-(id)GetRects:(CGRect)arg1 ;
-(char)Select:(float)arg1 y1:(float)arg2 x2:(float)arg3 y2:(float)arg4 ;
-(id)GetSelectedTextFromPage:(int)arg1 ToPage:(int)arg2 ;
-(id)GetQuadsFromPage:(int)arg1 ToPage:(int)arg2 ;
-(char)Select:(float)arg1 y1:(float)arg2 pageNumber1:(int)arg3 x2:(float)arg4 y2:(float)arg5 pageNumber2:(int)arg6 ;
-(void)Update:(void*)arg1 ;
-(void)Update:(void*)arg1 onPage:(int)arg2 ;
-(void)DoAction:(void*)arg1 ;
-(void)deluxeCreateTile:(void*)arg1 buffer:(char*)arg2 size:(CGSize)arg3 stride:(unsigned)arg4 pageNumber:(unsigned)arg5 locationOfPage:(CGPoint)arg6 locationInPage:(CGPoint)arg7 zoomedPageSize:(CGSize)arg8 tileID:(unsigned)arg9 canvasID:(int)arg10 remainingTiles:(int)arg11 tileType:(int)arg12 sequenceNumber:(int)arg13 ;
-(void)CreateTile:(void*)arg1 Buffer:(char*)arg2 OriginX:(int)arg3 OrginY:(int)arg4 Width:(int)arg5 Height:(int)arg6 CanvasNumber:(int)arg7 CellNumber:(long long)arg8 FinalRender:(char)arg9 PredictedRender:(char)arg10 TilesRemaining:(int)arg11 ThumbnailId:(int)arg12 ;
-(void)RequestRenderInWorkerThread;
-(void)PartDownloaded:(int)arg1 Doc:(void*)arg2 PageNumber:(unsigned)arg3 ObjectNumber:(unsigned)arg4 ;
-(void)annotBitmapProcWithBitmap:(int)arg1 buffer:(char*)arg2 width:(unsigned)arg3 height:(unsigned)arg4 stride:(unsigned)arg5 page_num:(unsigned)arg6 annot_index:(unsigned)arg7 annot_key:(void*)arg8 x_in_page:(long long)arg9 y_in_page:(long long)arg10 x_offset:(int)arg11 y_offset:(int)arg12 remaining_tiles:(int)arg13 sequence_number:(int)arg14 ;
-(void)RemoveTile:(int)arg1 CellNumber:(long long)arg2 ThumbnailId:(int)arg3 SequenceNumber:(int)arg4 ;
-(void)GetThumbCallback:(int)arg1 WasThumbFound:(char)arg2 ThumbBuf:(const char*)arg3 ThumbWidth:(int)arg4 ThumbHeight:(int)arg5 ;
-(id)init;
-(void)invalidate;
-(void)setDelegate:(id)arg1 ;
-(void)dealloc;
@end

