/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:17 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTSecurityHandler : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(char)IsValid;
-(char)IsModified;
-(char)GetPermission:(int)arg1 ;
-(int)GetKeyLength;
-(int)GetEncryptionAlgorithmID;
-(id)GetHandlerDocName;
-(void)SetModified:(char)arg1 ;
-(void)ChangeUserPasswordASCII:(id)arg1 ;
-(void)ChangeUserPasswordWithLength:(id)arg1 pwd_length:(unsigned long)arg2 ;
-(void)ChangeUserPassword:(id)arg1 ;
-(id)GetUserPassword;
-(unsigned long)GetUserPasswordSize;
-(void)ChangeMasterPasswordASCII:(id)arg1 ;
-(void)ChangeMasterPasswordWithLength:(id)arg1 pwd_length:(unsigned long)arg2 ;
-(void)ChangeMasterPassword:(id)arg1 ;
-(id)GetMasterPassword;
-(unsigned long)GetMasterPasswordSize;
-(void)SetPermission:(int)arg1 value:(char)arg2 ;
-(void)ChangeRevisionNumber:(int)arg1 ;
-(void)SetEncryptMetadata:(char)arg1 ;
-(int)GetRevisionNumber;
-(char)IsUserPasswordRequired;
-(char)IsMasterPasswordRequired;
-(char)IsAES;
-(char)IsAESWithStream:(id)arg1 ;
-(char)IsRC4;
-(void)AuthorizeFailed;
-(char)Authorize:(int)arg1 ;
-(char)GetAuthorizationData:(int)arg1 ;
-(char)EditSecurityData:(id)arg1 ;
-(id)FillEncryptDict:(id)arg1 ;
-(id)Clone:(id)arg1 ;
-(void)InitPasswordASCII:(id)arg1 ;
-(void)InitPasswordWithLength:(id)arg1 pwd_length:(unsigned long)arg2 ;
-(void)InitPassword:(id)arg1 ;
-(void)SetDerived:(unsigned)arg1 ;
-(id)GetDerived;
-(id)initWithCrypt_type:(int)arg1 ;
-(id)initWithName:(id)arg1 key_len:(int)arg2 enc_code:(int)arg3 ;
-(id)init;
-(void)dealloc;
@end

