/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:17 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTSignatureHandler : NSObject {

	void* m_cPtr;

}
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(id)GetName;
-(void)unsetCPtr;
-(void)AppendData:(id)arg1 ;
-(char)Reset;
-(id)CreateSignature;
-(id)init;
-(void)dealloc;
@end

