/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PTSVGOutputOptions : NSObject {

	void* swigCPtr;
	char swigCMemOwn;

}
-(id)initWithCptr:(void*)arg1 ;
-(void*)getCptr;
-(void)setSwigCMemOwn:(char)arg1 ;
-(void)SetOverprint:(id)arg1 ;
-(void)SetEmbedImages:(char)arg1 ;
-(void)SetNoFonts:(char)arg1 ;
-(void)SetSvgFonts:(char)arg1 ;
-(void)SetEmbedFonts:(char)arg1 ;
-(void)SetNoUnicode:(char)arg1 ;
-(void)SetIndividualCharPlacement:(char)arg1 ;
-(void)SetRemoveCharPlacement:(char)arg1 ;
-(void)SetFlattenDPI:(unsigned)arg1 ;
-(void)SetFlattenMaximumImagePixels:(unsigned)arg1 ;
-(void)SetCompress:(char)arg1 ;
-(void)SetCreateXmlWrapper:(char)arg1 ;
-(void)SetDtd:(char)arg1 ;
-(void)SetAnnots:(char)arg1 ;
-(void)SetOutputThumbnails:(char)arg1 ;
-(void)SetThumbnailSize:(unsigned)arg1 ;
-(void)SetFlattenContent:(int)arg1 ;
-(void)SetFlattenThreshold:(int)arg1 ;
-(id)init;
-(void)dealloc;
@end

