/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIImageView.h>

@interface PTTileView : UIImageView {

	int tileNumber;
	unsigned pageNumber;
	unsigned sequenceNumber;
	CGPoint originalOrigin;
	CGSize originalPageSize;
	CGSize controlFrameSize;

}

@property (assign,nonatomic) int tileNumber; 
@property (assign,nonatomic) unsigned pageNumber; 
@property (assign,nonatomic) unsigned sequenceNumber; 
@property (assign,nonatomic) CGSize originalPageSize; 
@property (assign,nonatomic) CGSize controlFrameSize; 
@property (assign,nonatomic) CGPoint originalOrigin; 
-(int)tileNumber;
-(CGPoint)originalOrigin;
-(CGSize)originalPageSize;
-(void)setTileNumber:(int)arg1 ;
-(void)setOriginalOrigin:(CGPoint)arg1 ;
-(void)setOriginalPageSize:(CGSize)arg1 ;
-(CGSize)controlFrameSize;
-(void)setControlFrameSize:(CGSize)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)printInfo;
-(unsigned)pageNumber;
-(void)setSequenceNumber:(unsigned)arg1 ;
-(unsigned)sequenceNumber;
-(void)setPageNumber:(unsigned)arg1 ;
@end

