/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:16 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class PTDocumentConversion, PTPDFViewCtrl, NSMutableArray;

@interface PTUniversalDocManager : NSObject {

	PTDocumentConversion* _documentConversion;
	PTPDFViewCtrl* _pdfViewCtrl;
	NSMutableArray* _eventQueue;

}

@property (assign,nonatomic) PTPDFViewCtrl * pdfViewCtrl;                            //@synthesize pdfViewCtrl=_pdfViewCtrl - In the implementation block
@property (nonatomic,retain) NSMutableArray * eventQueue;                            //@synthesize eventQueue=_eventQueue - In the implementation block
@property (nonatomic,retain) PTDocumentConversion * documentConversion;              //@synthesize documentConversion=_documentConversion - In the implementation block
-(PTPDFViewCtrl *)pdfViewCtrl;
-(void)setPdfViewCtrl:(PTPDFViewCtrl *)arg1 ;
-(void)addPageEvent:(id)arg1 ;
-(id)initWithPDFViewCtrl:(id)arg1 ;
-(void)addPageEventWithSDFDoc:(id)arg1 pageNumber:(unsigned)arg2 objNumber:(unsigned)arg3 message:(id)arg4 ;
-(PTDocumentConversion *)documentConversion;
-(void)setDocumentConversion:(PTDocumentConversion *)arg1 ;
-(void)reset;
-(NSMutableArray *)eventQueue;
-(void)setEventQueue:(NSMutableArray *)arg1 ;
-(void)processEventQueue;
@end

