/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:10 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol RichMediaToolbarTextDelegate <NSObject>
@required
-(void)unindent:(id)arg1;
-(void)toggleNumberedListStyle;
-(void)toggleBulletListStyle;
-(void)toggleChecklistStyle;
-(void)moveCaretForward;
-(void)moveCaretBackward;
-(void)moveCaretToEndOfWord;
-(void)moveCaretToStartOfWord;
-(void)refreshInputView;
-(void)refreshInputAssistantItemWithLeadingGroups:(id)arg1 trailingGroups:(id)arg2;
-(void)setListStyle:(int)arg1;
-(void)indent:(id)arg1;
-(void)hideKeyboard;
-(void)setAccessoryView:(id)arg1;

@end

