/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:10 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/GLDraggable.h>
#import <Notability/GLDraggableWithCurves.h>
#import <Notability/GLDroppable.h>

@protocol GLDroppableView, SnapProvider, ImageProvider;
@class NSItemProvider, NSString, NBNoteController, NSArray, SelectionRepresentation, _TtC10Notability10PenManager, NBNoteViewState, RichMediaDocument, UIImage, HandwritingObject;

@interface SelectionManager : NSObject <GLDraggable, GLDraggableWithCurves, GLDroppable> {

	NSArray* selectedCurves;
	CGPoint translation;
	float xScale;
	float yScale;
	float rotation;
	char isTransforming;
	SelectionRepresentation* _selectionRepresentation;
	char translationEnabled;
	char translatingForMediaObject;
	char shouldEnsureSelectionModeOnSelectionChange;
	char _isDragging;
	char _isDropping;
	char _isDropped;
	char _isDropCancelled;
	_TtC10Notability10PenManager* _penManager;
	NBNoteViewState* _noteViewState;
	RichMediaDocument* _document;
	int _dropOperation;
	id<GLDroppableView> _dropView;
	NBNoteController* _dragNoteController;
	NSArray* _dragCurves;
	SelectionRepresentation* _dragSelectionRepresentation;
	UIImage* _dragImage;
	float _lineSnapThresholdDocumentContent;
	float _pointSnapThresholdDocumentContent;
	id<SnapProvider> _snapProvider;
	id<ImageProvider> _imageProvider;
	NSArray* _snapPrimitives;
	HandwritingObject* _dragHandwritingObject;
	float _dragPenWidthScaleFactor;
	CGPoint _dropLocation;
	CGPoint _pivot;

}

@property (retain) SelectionRepresentation * selectionRepresentation; 
@property (retain) NSArray * snapPrimitives;                                                                 //@synthesize snapPrimitives=_snapPrimitives - In the implementation block
@property (nonatomic,retain) NSArray * dragCurves;                                                           //@synthesize dragCurves=_dragCurves - In the implementation block
@property (nonatomic,retain) HandwritingObject * dragHandwritingObject;                                      //@synthesize dragHandwritingObject=_dragHandwritingObject - In the implementation block
@property (nonatomic,retain) SelectionRepresentation * dragSelectionRepresentation;                          //@synthesize dragSelectionRepresentation=_dragSelectionRepresentation - In the implementation block
@property (assign,nonatomic) float dragPenWidthScaleFactor;                                                  //@synthesize dragPenWidthScaleFactor=_dragPenWidthScaleFactor - In the implementation block
@property (nonatomic,retain) UIImage * dragImage;                                                            //@synthesize dragImage=_dragImage - In the implementation block
@property (assign,nonatomic) char isDropping;                                                                //@synthesize isDropping=_isDropping - In the implementation block
@property (assign,nonatomic) char isDropped;                                                                 //@synthesize isDropped=_isDropped - In the implementation block
@property (assign,nonatomic) char isDropCancelled;                                                           //@synthesize isDropCancelled=_isDropCancelled - In the implementation block
@property (assign,getter=isTranslationEnabled,nonatomic) char translationEnabled; 
@property (assign,getter=isTranslatingForMediaObject,nonatomic) char translatingForMediaObject; 
@property (assign,nonatomic) char shouldEnsureSelectionModeOnSelectionChange; 
@property (__weak) _TtC10Notability10PenManager * penManager;                                                //@synthesize penManager=_penManager - In the implementation block
@property (nonatomic,retain) NBNoteViewState * noteViewState;                                                //@synthesize noteViewState=_noteViewState - In the implementation block
@property (assign,nonatomic,__weak) RichMediaDocument * document;                                            //@synthesize document=_document - In the implementation block
@property (nonatomic,readonly) HandwritingObject * handwritingObject; 
@property (nonatomic,readonly) char canDrag; 
@property (assign,nonatomic) char isDragging;                                                                //@synthesize isDragging=_isDragging - In the implementation block
@property (nonatomic,readonly) char allowDragMove; 
@property (assign,nonatomic) int dropOperation;                                                              //@synthesize dropOperation=_dropOperation - In the implementation block
@property (nonatomic,readonly) float dragAlpha; 
@property (nonatomic,readonly) int dragContent; 
@property (nonatomic,readonly) NSItemProvider * dragItemProvider; 
@property (nonatomic,copy,readonly) NSString * dragSuggestedName; 
@property (assign,nonatomic) CGPoint dropLocation;                                                           //@synthesize dropLocation=_dropLocation - In the implementation block
@property (assign,nonatomic,__weak) id<GLDroppableView> dropView;                                            //@synthesize dropView=_dropView - In the implementation block
@property (assign,nonatomic,__weak) NBNoteController * dragNoteController;                                   //@synthesize dragNoteController=_dragNoteController - In the implementation block
@property (assign) float lineSnapThresholdDocumentContent;                                                   //@synthesize lineSnapThresholdDocumentContent=_lineSnapThresholdDocumentContent - In the implementation block
@property (assign) float pointSnapThresholdDocumentContent;                                                  //@synthesize pointSnapThresholdDocumentContent=_pointSnapThresholdDocumentContent - In the implementation block
@property (readonly) char isTransforming; 
@property (assign) CGPoint pivot;                                                                            //@synthesize pivot=_pivot - In the implementation block
@property (__weak) id<SnapProvider> snapProvider;                                                            //@synthesize snapProvider=_snapProvider - In the implementation block
@property (__weak) id<ImageProvider> imageProvider;                                                          //@synthesize imageProvider=_imageProvider - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setPenManager:(_TtC10Notability10PenManager *)arg1 ;
-(char)hasSelectedCurves;
-(SelectionRepresentation *)selectionRepresentation;
-(void)setSelectionRepresentation:(SelectionRepresentation *)arg1 ;
-(CGRect)selectionBoundsForZoom:(float)arg1 includeSelectionRepresentation:(char)arg2 includeCurves:(char)arg3 ;
-(_TtC10Notability10PenManager *)penManager;
-(void)drawSelectedCurvesWithContext:(id)arg1 ;
-(char)isTransforming;
-(void)completeTransform;
-(void)setSelectionRepresentation:(id)arg1 selectedCurves:(id)arg2 shouldAutoSelect:(char)arg3 shouldRegisterUndo:(char)arg4 ;
-(id)selectedCurves;
-(void)refreshSnaps;
-(void)setTranslation:(CGPoint)arg1 scale:(float)arg2 rotation:(float)arg3 shouldApplySnapping:(char)arg4 ;
-(void)cancelTransform;
-(void)setPointSnapThresholdDocumentContent:(float)arg1 ;
-(void)setLineSnapThresholdDocumentContent:(float)arg1 ;
-(void)setTranslation:(CGPoint)arg1 xScale:(float)arg2 yScale:(float)arg3 rotation:(float)arg4 shouldApplySnapping:(char)arg5 ;
-(void)cancelDrop;
-(void)setIsDropping:(char)arg1 ;
-(void)setIsDropCancelled:(char)arg1 ;
-(void)resetForDrop;
-(void)setIsDropped:(char)arg1 ;
-(id)dropWithCompletion:(/*^block*/id)arg1 ;
-(char)isDropping;
-(char)isDropped;
-(char)isDropCancelled;
-(char)allowDragMove;
-(void)copySelectionAsImageToGeneralPasteboard;
-(HandwritingObject *)handwritingObject;
-(id)selectionAsImageForCopy;
-(void)_updateSnapPrimitivesForSelectedCurves;
-(id<SnapProvider>)snapProvider;
-(void)setSnapPrimitives:(NSArray *)arg1 ;
-(void)resetTransformState;
-(void)unsetSelectionDoNotNotify;
-(void)setShouldEnsureSelectionModeOnSelectionChange:(char)arg1 ;
-(void)ensureHandwritingAndSelectionMode;
-(NBNoteViewState *)noteViewState;
-(float)selectionWidth;
-(CGPathRef)selectionPath;
-(NSArray *)snapPrimitives;
-(float)lineSnapThresholdDocumentContent;
-(char)canTransform;
-(CGPoint)_snappedTranslationFromTranslation:(CGPoint)arg1 ;
-(char)isTranslatingForMediaObject;
-(int)dropOperation;
-(void)updateHandwritingObjectForDragChange;
-(NSArray *)dragCurves;
-(HandwritingObject *)dragHandwritingObject;
-(SelectionRepresentation *)dragSelectionRepresentation;
-(id)selectionAsImageWithViewScale:(float)arg1 ;
-(NSString *)dragSuggestedName;
-(NSItemProvider *)dragItemProvider;
-(NBNoteController *)dragNoteController;
-(void)setDragCurves:(NSArray *)arg1 ;
-(void)setDragHandwritingObject:(HandwritingObject *)arg1 ;
-(void)setDragSelectionRepresentation:(SelectionRepresentation *)arg1 ;
-(void)setDragPenWidthScaleFactor:(float)arg1 ;
-(void)setDragNoteController:(NBNoteController *)arg1 ;
-(id<GLDroppableView>)dropView;
-(float)dragPenWidthScaleFactor;
-(CGPoint)dropLocation;
-(void)setDropView:(id<GLDroppableView>)arg1 ;
-(void)setDropLocation:(CGPoint)arg1 ;
-(void)prepareForDragWithNoteController:(id)arg1 ;
-(id)dragItemWithPreviewProvider:(/*^block*/id)arg1 ;
-(id)targetedDragPreviewWithContainer:(id)arg1 ;
-(void)resetForDrag;
-(char)canDrag;
-(void)setDropOperation:(int)arg1 ;
-(int)dragContent;
-(void)cutSelection;
-(void)copySelectionAsImage;
-(void)copySelection;
-(void)setSelectionWidth:(float)arg1 ;
-(char)hasSelectionAtDocumentContentPoint:(CGPoint)arg1 ;
-(float)dragAlpha;
-(CGRect)draggedBoundsForZoom:(float)arg1 includeSelectionRepresentation:(char)arg2 includeCurves:(char)arg3 ;
-(char)isTranslationEnabled;
-(void)setTranslationEnabled:(char)arg1 ;
-(void)setTranslatingForMediaObject:(char)arg1 ;
-(char)shouldEnsureSelectionModeOnSelectionChange;
-(void)setNoteViewState:(NBNoteViewState *)arg1 ;
-(float)pointSnapThresholdDocumentContent;
-(void)setSnapProvider:(id<SnapProvider>)arg1 ;
-(void)recognizeSelectedHandwritingWithConfiguration:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)deleteSelection;
-(id)init;
-(void)dealloc;
-(char)isDragging;
-(id)undoManager;
-(float)scale;
-(CGAffineTransform)affineTransform;
-(char)hasSelection;
-(void)clearSelection;
-(float)rotation;
-(void)inputModeDidChange:(id)arg1 ;
-(id)selectionColor;
-(void)setSelectionColor:(id)arg1 ;
-(RichMediaDocument *)document;
-(void)setDocument:(RichMediaDocument *)arg1 ;
-(CGPoint)translation;
-(id<ImageProvider>)imageProvider;
-(void)setImageProvider:(id<ImageProvider>)arg1 ;
-(CGPoint)pivot;
-(void)setPivot:(CGPoint)arg1 ;
-(void)setDragImage:(UIImage *)arg1 ;
-(UIImage *)dragImage;
-(void)setIsDragging:(char)arg1 ;
-(float)xScale;
-(float)yScale;
@end

