/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:10 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@class NSString, NSArray;

@interface SerializableObject : NSObject <NSCoding> {

	NSString* _identifier;

}

@property (readonly) NSArray * allSavedProperties; 
@property (retain) NSString * identifier;                       //@synthesize identifier=_identifier - In the implementation block
@property (readonly) NSArray * savedProperties; 
-(NSArray *)savedProperties;
-(NSArray *)allSavedProperties;
-(char)hasProperty:(id)arg1 readwrite:(char)arg2 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(char)isEqual:(id)arg1 ;
-(unsigned)hash;
-(NSString *)identifier;
-(void)setIdentifier:(NSString *)arg1 ;
@end

