/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:09 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SubjectListViewDelegate
@required
-(char)subjectListView:(id)arg1 requestsDeleteSubject:(id)arg2;
-(char)subjectListView:(id)arg1 requestsMoveNotes:(id)arg2 toSubject:(id)arg3;
-(void)subjectListView:(id)arg1 selectedNotesMovedSuccess:(char)arg2;
-(char)subjectListView:(id)arg1 requestsDeleteCategory:(id)arg2;
-(char)subjectListView:(id)arg1 requestsMoveNote:(id)arg2 toSubject:(id)arg3;
-(id)subjectListViewRequestsEditSelectedNotes:(id)arg1;
-(id)subjectListViewRequestsCloudSelectedNotes:(id)arg1;

@end

