/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:11 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <Notability/CanvasMediaObject.h>
#import <Notability/NBTextMappingProtocol.h>
#import <Notability/NBTextRedrawingProtocol.h>

@class FormattedString, NBTextBlockController, NBCPEventManager, NSString;

@interface TextBlockMediaObject : CanvasMediaObject <NBTextMappingProtocol, NBTextRedrawingProtocol> {

	char editingText;
	char shouldEditOnSelection;
	char resizingForLayoutWhileTyping;
	char _suppressMenuOnSelection;
	FormattedString* _textStore;
	NBTextBlockController* _controller;
	float _absMinInterfaceZoom;
	float _parentPageWidth;
	NBCPEventManager* _contentPlaybackEventManager;

}

@property (nonatomic,retain) FormattedString * textStore;                                                          //@synthesize textStore=_textStore - In the implementation block
@property (nonatomic,retain) NBCPEventManager * contentPlaybackEventManager;                                       //@synthesize contentPlaybackEventManager=_contentPlaybackEventManager - In the implementation block
@property (nonatomic,retain) NBTextBlockController * controller;                                                   //@synthesize controller=_controller - In the implementation block
@property (assign,getter=isEditingText,nonatomic) char editingText; 
@property (assign,nonatomic) char shouldEditOnSelection; 
@property (assign,nonatomic) char suppressMenuOnSelection;                                                         //@synthesize suppressMenuOnSelection=_suppressMenuOnSelection - In the implementation block
@property (assign,getter=isResizingForLayoutWhileTyping,nonatomic) char resizingForLayoutWhileTyping; 
@property (assign,nonatomic) float absMinInterfaceZoom;                                                            //@synthesize absMinInterfaceZoom=_absMinInterfaceZoom - In the implementation block
@property (assign,nonatomic) float parentPageWidth;                                                                //@synthesize parentPageWidth=_parentPageWidth - In the implementation block
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)writableTypeIdentifiersForItemProvider;
-(FormattedString *)textStore;
-(NBCPEventManager *)contentPlaybackEventManager;
-(void)setNoteDocument:(id)arg1 ;
-(char)isResizingForLayoutWhileTyping;
-(void)redrawMediaViewInDocumentRects:(id)arg1 async:(char)arg2 ;
-(float)absMinInterfaceZoom;
-(void)setTextStore:(FormattedString *)arg1 ;
-(void)setContentPlaybackEventManager:(NBCPEventManager *)arg1 ;
-(id)dragSuggestedName;
-(void)drawContentInContext:(id)arg1 inRect:(CGRect)arg2 shouldDoCompleteRender:(char)arg3 shouldRenderCaption:(char)arg4 ;
-(void)resizeWithStartingSize:(CGSize)arg1 delta:(CGSize)arg2 mode:(int)arg3 ;
-(void)drawContentInContext:(id)arg1 inRect:(CGRect)arg2 shouldDoCompleteRender:(char)arg3 shouldRenderCaption:(char)arg4 renderFlags:(unsigned)arg5 ;
-(void)noteControllerDocumentPageCountDidChangeAsync:(char)arg1 ;
-(void)redrawPaperAndPDFForPagesBelowIndex:(unsigned)arg1 ;
-(void)redrawMediaViewForMediaObject:(id)arg1 ;
-(unsigned)characterIndexForPoint:(CGPoint)arg1 noteController:(id*)arg2 ;
-(id)nonTextBlockMediaObjectForPoint:(CGPoint)arg1 ;
-(void)setEditingText:(char)arg1 ;
-(unsigned)characterIndexForViewPoint:(CGPoint)arg1 isBelowContent:(char*)arg2 ;
-(void)setResizingForLayoutWhileTyping:(char)arg1 ;
-(void)updateSavedFontAttributes;
-(void)setupDefaultFont;
-(void)deselect;
-(void)setShouldEditOnSelection:(char)arg1 ;
-(void)redrawMediaView;
-(id)writableTypeIdentifiersForItemProvider;
-(id)loadDataWithTypeIdentifier:(id)arg1 forItemProviderCompletionHandler:(/*^block*/id)arg2 ;
-(void)setParentPageWidth:(float)arg1 ;
-(void)configureForSingleLineHeightWithWidth:(float)arg1 ;
-(void)redrawForDrag;
-(char)shouldEditOnSelection;
-(char)suppressMenuOnSelection;
-(void)setSuppressMenuOnSelection:(char)arg1 ;
-(void)setAbsMinInterfaceZoom:(float)arg1 ;
-(float)parentPageWidth;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NBTextBlockController *)controller;
-(void)setController:(NBTextBlockController *)arg1 ;
-(void)setDesiredSize:(CGSize)arg1 ;
-(char)isEditingText;
@end

