/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:07 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIPageViewControllerDelegate <NSObject>
@optional
-(void)pageViewController:(id)arg1 willTransitionToViewControllers:(id)arg2;
-(void)pageViewController:(id)arg1 didFinishAnimating:(char)arg2 previousViewControllers:(id)arg3 transitionCompleted:(char)arg4;
-(int)pageViewController:(id)arg1 spineLocationForInterfaceOrientation:(int)arg2;
-(unsigned)pageViewControllerSupportedInterfaceOrientations:(id)arg1;
-(int)pageViewControllerPreferredInterfaceOrientationForPresentation:(id)arg1;

@end

