/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:07 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UISearchBarDelegate <UIBarPositioningDelegate>
@optional
-(void)searchBar:(id)arg1 textDidChange:(id)arg2;
-(void)searchBar:(id)arg1 selectedScopeButtonIndexDidChange:(int)arg2;
-(char)searchBarShouldBeginEditing:(id)arg1;
-(char)searchBarShouldEndEditing:(id)arg1;
-(void)searchBarCancelButtonClicked:(id)arg1;
-(void)searchBarBookmarkButtonClicked:(id)arg1;
-(void)searchBarResultsListButtonClicked:(id)arg1;
-(void)searchBarTextDidBeginEditing:(id)arg1;
-(void)searchBarTextDidEndEditing:(id)arg1;
-(void)searchBarSearchButtonClicked:(id)arg1;
-(char)searchBar:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3;

@end

