/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:14 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/ImageMediaObject.h>

@class NSString, NSMutableArray;

@interface WebMediaObject : ImageMediaObject {

	NSString* url;
	NSMutableArray* URLNavigationArray;
	int URLNavigationIndex;
	NSString* siteTitle;

}

@property (nonatomic,retain) NSString * url; 
@property (nonatomic,retain) NSMutableArray * URLNavigationArray; 
@property (assign,nonatomic) int URLNavigationIndex; 
@property (nonatomic,retain) NSString * siteTitle; 
+(id)writableTypeIdentifiersForItemProvider;
-(id)dragSuggestedName;
-(NSMutableArray *)URLNavigationArray;
-(id)editMenuItems;
-(id)writableTypeIdentifiersForItemProvider;
-(id)loadDataWithTypeIdentifier:(id)arg1 forItemProviderCompletionHandler:(/*^block*/id)arg2 ;
-(void)setSiteTitle:(NSString *)arg1 ;
-(int)URLNavigationIndex;
-(void)setURLNavigationIndex:(int)arg1 ;
-(void)editButtonAction:(id)arg1 ;
-(void)setURLNavigationArray:(NSMutableArray *)arg1 ;
-(NSString *)siteTitle;
-(void)browseButtonAction:(id)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSString *)url;
-(char)canPerformAction:(SEL)arg1 withSender:(id)arg2 ;
-(void)setUrl:(NSString *)arg1 ;
@end

