/*
* This header is generated by classdump-dyld 1.0
* on Saturday, January 7, 2023 at 9:05:08 PM Indochina Time
* Operating System: Version 10.3.4 (Build 14G61)
* Image Source: /var/containers/Bundle/Application/1CFA07C5-D48B-45F0-A604-A4F98727D809/Notability.app/Notability
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Notability/Notability-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIWebViewDelegate.h>

@protocol WebViewerDelegate;
@class UIWebView, NSURLRequest, NSString;

@interface WebViewer : UIView <UIWebViewDelegate> {

	id<WebViewerDelegate> delegate;
	UIWebView* webView;
	NSURLRequest* _pendingExternallyRequestedURLRequest;

}

@property (retain) NSURLRequest * pendingExternallyRequestedURLRequest;              //@synthesize pendingExternallyRequestedURLRequest=_pendingExternallyRequestedURLRequest - In the implementation block
@property (assign,nonatomic,__weak) id<WebViewerDelegate> delegate; 
@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setPendingExternallyRequestedURLRequest:(NSURLRequest *)arg1 ;
-(void)introspectWithLayer:(id)arg1 level:(int)arg2 ;
-(void)introspectWithView:(id)arg1 level:(int)arg2 ;
-(NSURLRequest *)pendingExternallyRequestedURLRequest;
-(void)setWebContentInsets:(UIEdgeInsets)arg1 ;
-(id)currentPageTitle;
-(id)init;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<WebViewerDelegate>)arg1 ;
-(void)dealloc;
-(id<WebViewerDelegate>)delegate;
-(id)snapshot;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(char)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3 ;
-(void)webViewDidStartLoad:(id)arg1 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(void)_sharedInit;
-(void)loadURL:(id)arg1 ;
@end

